### ISSUE TITLE
Can't use model files found in PSACNN

### ISSUE THREAD

**Issue by pedrob37** [freesurfer/freesurfer#1004]
I'm trying to run the PSACNN pipeline on some T1w images, but when I do so I get the following error:

```traits.trait_errors.TraitError: The 'model_file' trait of a PSACNNInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/FreeSurfer/psacnn_brain_segmentation/model_files/t1t2_psacnn_p96_v1.h5' <class 'str'> was specified```

Checking the model_files directory reveals that the h5 files are merely symbolic links, and I'm unsure how to get the actual model files from them. I should say that I ran into errors running setup.py, so I have just manually created a virtual environment with the required packages. Would appreciate any help solving this issue.

**Comment by avnishks** [comment]
Hi Pedro,

The model_files directory only contains the symlinks to the actual data files in git-annex. During your installation you can get these files as such:
1. setup remote data repo: 
`git remote add datasrc https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git`

2. get the data:
`git fetch datasrc`
`git-annex get psacnn_brain_segmentation/model_files/t1t2_psacnn_p96_v1.h5`

For more information about the installation steps, please refer to this freesurfer build guide: https://surfer.nmr.mgh.harvard.edu/fswiki/BuildGuide

**Comment by buildqa** [comment]
Closing as no new activity.
