### ISSUE TITLE
recon-all -i $T1 -T2 $T2 -autorecon1 attempts to run -T2pial

### ISSUE THREAD

**Issue by effigies** [freesurfer/freesurfer#1010]
Just want to check in on these lines in recon-all in FreeSurfer 7+:

https://github.com/freesurfer/freesurfer/blob/e61d4e8f1dd9b55ac756b053c5cdad29ae698e47/scripts/recon-all#L5776-L5779

This seems an intentional decision to make `-T2` activate `-T2pial` (and similar for `-FLAIR`), presumably under the assumption that people will just run `recon-all -i $T1 -T2 $T2 -all` and may forget to add `-T2pial`. Would you all consider this a bug or a caveat emptor kind of situation?

Would it make sense to add the following to `-autorecon1` and `-autorecon2`?

```diff
diff --git a/scripts/recon-all b/scripts/recon-all
index 4b98118264..0655097ab9 100755
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -6869,6 +6869,7 @@ while( $#argv != 0 )
       breaksw
 
     case "-autorecon1":
+      set DoT2pial         = 0;
       set DoCreateBaseInput = 1;
       set DoMotionCor      = 1;
       set DoTalairach      = 1;
@@ -6911,6 +6912,7 @@ while( $#argv != 0 )
       set DoRemoveNeck     = 0;
       set DoSkullLTA       = 0;
       set DoSegStats       = 0;
+      set DoT2pial         = 0;
       set DoCANormalize    = 1;
       set DoGCAReg         = 1;
       set DoCALabel        = 1;
```

In any case, my solution for now will be to add `-noT2pial` and `-noFLAIRpial` to `-T2` calls that aren't `-all` as well, which seems safe for writing commands that will work for both FreeSurfer 6 and 7.

**Comment by buildqa** [comment]
If this is still an issue, then please post to the freesurfer list, freesurfer@nmr.mgh.harvard.edu, where more developers/users are likely to read it.

**Comment by buildqa** [comment]
Please post to the above list if still an issue.
