### ISSUE TITLE
Cortical Thickness measures using different ways of processing

### ISSUE THREAD

**Issue by arianafei** [freesurfer/freesurfer#1011]
Hi,

We are recently trying to get cortical thickness from freesurfer and converting them to 32k. A problem we notice is that after converting to 32k, all the cortical thickness values become negative. However, when we load freesurfer thickness files in freeview, everything appears normal. We wonder if merely inverting what we currently in 32k would be a good idea. Alternatively, we also calculated the Euclidean distance of pial and white after they have been converted into 32k space, which should be cortical thickness. However, when comparing the inverted values and the pial-white values, we find that there is some difference (shown by the scatter plot and correlation). In this case, has anyone ever had similar issues and have suggestions on which one to trust?

Thanks!
<img width="659" alt="Screen Shot 2022-07-19 at 4 20 34 PM" src="https://user-images.githubusercontent.com/91152947/179853916-bf9b5ab1-4164-46da-85a7-a11a42dfb0d7.png">
correlation~0.94

**Comment by dngreve** [comment]
Please post this to the freesufer list

On 7/19/2022 5:44 PM, arianafei wrote:
>
>         External Email - Use Caution
>
> Hi,
>
> We are recently trying to get cortical thickness from freesurfer and 
> converting them to 32k. A problem we notice is that after converting 
> to 32k, all the cortical thickness values become negative. However, 
> when we load freesurfer thickness files in freeview, everything 
> appears normal. We wonder if merely inverting what we currently in 32k 
> would be a good idea. Alternatively, we also calculated the Euclidean 
> distance of pial and white after they have been converted into 32k 
> space, which should be cortical thickness. However, when comparing the 
> inverted values and the pial-white values, we find that there is some 
> difference (shown by the scatter plot and correlation). In this case, 
> has anyone ever had similar issues and have suggestions on which one 
> to trust?
>
> Thanks!
> Screen Shot 2022-07-19 at 4 20 34 PM 
> <https://secure-web.cisco.com/1CmO3BFnwsdfWJUK2ToEk6iW0EHNYlZmPn3_lqYUHNRutC252mEHpSUYNhIBCmSsXO83yZAekLF9BN_ZrPOrWbTKjICrglcIHX9wO3U69WCnUF8xcaP77wHSYafDCcABvAK3cnUe_R6rdkjYiFxpC40SCkrPpc8ab8iBcsiPkON6Hut9y8udEoVGPv5rtnil0if4_5k91MqppDBnjT4QBFWAr7m3hSdqkzHSAToplbETpqgQbVWhPPLacFL0wL35baiGisAg6L1LICClkj74_KCJH0j1QmSFTsXM0d6rNm8PwsukkAADS7zukzW3uDV5e/https%3A%2F%2Fuser-images.githubusercontent.com%2F91152947%2F179853916-bf9b5ab1-4164-46da-85a7-a11a42dfb0d7.png>
> correlation~0.94
>
> —
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1yWWIZ66AkNsxZ-CDlIhTEVPuORTPlTQCNXDE3j_ZEPuu4PWgBWC4E0M1jyJCXgaJWTKuiqRA7V8xZQq34UoPtMPYYvVUERVjF2kKCAuWFw8ueMgbejMq4LktxG8RN8QMZnJdBpghrb4Y2XUGQlVTN49f2kdWmtItaRLQPYTve48sJkIQU93GihelY9Tj4Zb2WO1pVdr8m6EO1kdCawocn9tQYbiUCILwKiKmp6iKXcJS0Wv7PaGU9t8AGbDRspEr-adXfqVUSH7WJjYHSSQyPGLHukA1QW-ZHLg1m5m2Y2pQs-JlqmUBJEAxwR9lWgHK/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1011>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1if2yp7TzXRCRie0wDHNycOl3bdDZNSRSjOKsuo3KBwxyaITT2fLRzf3cdpo6y-4vEN9ne6BYvOdzctmu0H3cp3qLejY8EDRTzCHRrI4qt-zX6_f2QmwmCXnnyCCqI-7LgewTeho8LfeNAdScYYpmV6z6_b6HrtvHsWvdESFkN_1AxwA0k_21VyCPWnwuAWjrymrMSCJ6mG-ogl9fNgVRK0V3VHwBgFjzszlIEAjY_KOOL8bolSGt3Q6o4CJkPLMc7hZjtnMydHm6jT9qbWy6KFJsiYZkPVw3l84357BYEY3UmoWmPC6tMQmLOBXYabWd/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VSTMMXAMTJ3SWTVJP3VU4OVLANCNFSM54BNT6LA>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>
>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by buildqa** [comment]
Closing as we expect user to post this to the fressurfer list, freesurfer@nmr.mgh.harvard.edu (you will need to register)
