### ISSUE TITLE
SynthStrip generates corrupted files

### ISSUE THREAD

**Issue by mbrzus** [freesurfer/freesurfer#1015]
Hello,

I am working with Clinical MRI data. I am using the SynthStrip on T1w, T2w, Flair, and Diffusion Tensor Images (ADC and Trace-weighted) images. Overall, the SynthStrip works great! 

However, for some datasets, SynthStrip runs smoothly without errors but produces corrupted images. Trying to read the output images with ITK results in error:

> 
> RuntimeError: /work/ITK-source/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
> ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

I would expect the output image (both mask and the SkullStripped volume) to have the same metadata as the input image (origin, spacing, and the direction cosine). 

<details>
  <summary>Expand The input image information</summary>

Using Python3 "itk.imread(image_path)" command:

 Image (0x60a71f0)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 418
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 232
  UpdateMTime: 417
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 23]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 23]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 23]
  Spacing: [0.4297, 0.4297, 6]
  Origin: [-113.929, 95.626, -64.0056]
  Direction: 
0.996489 -0.0464802 0.069648
-0.0529496 -0.994122 0.0944249
-0.0648517 0.0977825 0.993093

  IndexToPointMatrix: 
0.428191 -0.0199725 0.417888
-0.0227524 -0.427174 0.566549
-0.0278668 0.0420171 5.95856

  PointToIndexMatrix: 
2.31903 -0.123271 -0.150919
-0.108123 -2.31353 0.227557
0.011608 0.0157375 0.165515

  Inverse Direction: 
0.996488 -0.0529695 -0.0648498
-0.0464603 -0.994123 0.0977812
0.069648 0.0944249 0.993093

  PixelContainer: 
    ImportImageContainer (0x5f86ce0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 414
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f95d7b16010
      Container manages memory: true
      Size: 6029312
      Capacity: 6029312

</details>

ANy help with the issue would be great. Thanks!

**Comment by mbrzus** [comment]
UPDATE:

inspecting the input and output files using nifty_tool gave more insight to the problem:

> ➜  nifti_tool_testing nifti_tool -diff_hdr -infiles input.nii.gz output.nii.gz 
>   name                offset  nvals  values
>   ------------------- ------  -----  ------
>   regular               38      1    r
>   regular               38      1    
>   dim_info              39      1    54
>   dim_info              39      1    0
>   dim                   40      8    3 512 512 23 1 1 1 1
>   dim                   40      8    4 512 512 23 1 1 1 1
>   pixdim                76      8    -1.0 0.4297 0.4297 6.0 9.502 0.0 0.0 0.0
>   pixdim                76      8    -1.0 0.4297 0.4297 6.0 1.0 1.0 1.0 1.0
>   xyzt_units           123      1    10
>   xyzt_units           123      1    0
>   descrip              148     80    TE=1.2e+02;Time=143108.000
>   descrip              148     80    
>   qform_code           252      1    1
>   qform_code           252      1    0
>   sform_code           254      1    1
>   sform_code           254      1    2
>   quatern_b            256      1    0.024908
>   quatern_b            256      1    0.024908

FIX:
1. Using nifty_tool I was able to split the .nii.gz files into header and image files (.hdr and .img)
   
    > nifti_tool -copy_im -prefix input.hdr -infiles input.nii.gz
    > nifti_tool -copy_im -prefix output.hdr -infiles output.nii.gz

2. Overwrite the output header file
    > cp input.hdr output.hdr

3. Converting the new output header file with the output image file to new nifti image fixed the problem
 > nifti_tool -copy_im -prefix output-fixed.nii.gz -infiles output.hdr

**Comment by ahoopes** [comment]
Thanks for pointing this out. Looks like surfa was not setting the nifti qform and sform codes to 'scanner' when saving. Should be [fixed](https://github.com/freesurfer/surfa/commit/f5643c1f4014b158478c1caa104a2df850b47c6e) in surfa 0.3.1. I updated the synthstrip container to account for this, and the fix should appear in the freesurfer development builds within a couple days (any new release after Aug 5 2022). I mentioned this bug on the [doc page](https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/) too. Feel free to reopen if you find there are still issues.

**Comment by mbrzus** [comment]
Great! Thank you for looking into this @ahoopes!
