### ISSUE TITLE
vox2ras_tkreg.m produces matrix inconsistent with tkregister2

### ISSUE THREAD

**Issue by Jialiang-Lu** [freesurfer/freesurfer#1020]
For example, when loading the D99 Saleem Macaque Brain Atlas to tkregister2, the Tmov is:

-0.25000   0.00000   0.00000   34.37500;
 0.00000   0.00000   0.25000  -30.62500;
 0.00000  -0.25000   0.00000   43.37500;
 0.00000   0.00000   0.00000   1.00000;

However, when loading the same volume using `MRIread()`, the `tkrvox2ras` becomes:

-0.25000   0.00000   0.00000   43.37500;
 0.00000   0.00000   0.25000  -30.62500;
 0.00000  -0.25000   0.00000   34.37500;
 0.00000   0.00000   0.00000   1.00000;

I have to change 
https://github.com/freesurfer/freesurfer/blob/6449341377bcc1e9a3fabb3e9cbd241b910ed0a0/matlab/vox2ras_tkreg.m#L38-L46

to
`T(1,1) = -voxres(2);`
`T(1,4) = voxres(2)*voldim(2)/2;`
`T(2,3) = voxres(3);`
`T(2,4) = -voxres(3)*voldim(3)/2;`
`T(3,2) = -voxres(1);`
`T(3,4) = voxres(1)*voldim(1)/2;`

to solve this mismatch in dimensions.

**Comment by buildqa** [comment]
If this is still an issue, then please post this to freesurfer@nmr.mgh.harvard.edu (you will need to register) where more developers/users are likely to read.

**Comment by buildqa** [comment]
Please post to the above list if still an issue.
