### ISSUE TITLE
Bug: mri_brainvol_stats fails if subjectname is "subject"

### ISSUE THREAD

**Issue by m-reuter** [freesurfer/freesurfer#1022]
recon-all is does not complain when the subject id is "subject", yet when mri_brainvol_stats is called here:
https://github.com/freesurfer/freesurfer/blob/e5ee495b3a2714a55cf0509a519f35b82524095e/scripts/recon-all#L4706 
like so:
`mri_brainvol_stats subject`
it throws this error: 
> error: not enough inputs supplied to 'subject'

Probably the parser cannot deal with "subject" as a subject id:https://github.com/freesurfer/freesurfer/blob/e5ee495b3a2714a55cf0509a519f35b82524095e/mri_brainvol_stats/mri_brainvol_stats.cpp#L17
 
This has been also observed in 
https://github.com/Deep-MI/FastSurfer/issues/186

**Comment by dngreve** [comment]
Fixed this by requiring brainvol stats to take --subject. Changed recon-all to match.
