### ISSUE TITLE
Missing official container image for FreeSurfer version 7.3

### ISSUE THREAD

**Issue by ghisvail** [freesurfer/freesurfer#1024]
At the time of posting, the latest available tag on [dockerhub](https://hub.docker.com/r/freesurfer/freesurfer/tags) corresponds to version `7.2.0`.

It would be nice to publish a new image for the latest version (`7.3.2` as of today) and perhaps provide rolling tags for `7.3` and `7`.

For a little bit of context, I am the maintainer of [pydra-freesurfer](https://github.com/aramis-lab/pydra-freesurfer) which provides interfaces for FreeSurfer as Pydra tasks (successor to Nipype). One desirable feature of Pydra is its support for running commands inside Docker containers. I would like to use this feature as part of the project's CI to facilitate testing of multiple FreeSurfer versions and catch potential regressions earlier.

Thanks,
Ghis

**Comment by ghisvail** [comment]
And yes I know I could built my own by adjusting the existing recipe or using `neurodocker`. The emphasis here is on using an **official** image.

**Comment by ghisvail** [comment]
I have tweaked the existing recipe to use the official `quay.io/centos/centos:stream8` base image and produce less intermediate layers.

I can provide a PR to update the current one which used the old and now deprecated `centos:7` base image from Dockerhub, if you're interested.

**Comment by pwighton** [comment]
Hi @ghisvail, I'm working on updating dockerhub now.  I've created a branch [here](https://github.com/pwighton/freesurfer/tree/20221012-docker/docker) with a docker subfolder to hold dockerfiles for multiple versions, and perhaps multiple base containers at some point.

Just curious, when updating your containers for centos8, did you have to make any other changes other than the `FROM` statement?

**Comment by ghisvail** [comment]
> Hi @ghisvail, I'm working on updating dockerhub now.

Awesome! Thank you 🙏 

> with a docker subfolder to hold dockerfiles for multiple versions, and perhaps multiple base containers at some point.

For that, you might want to investigate [build arguments](https://docs.docker.com/engine/reference/builder/#arg) to avoid unnecessary duplication. I think they would be particularly useful for switching between versions to download.

> Just curious, when updating your containers for centos8, did you have to make any other changes other than the FROM statement?

I used `quay.io/centos/centos:stream8` as the base image, which is now the officially supported one.

I also used [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) to first download and untar the sources to `/usr/local/src`, and then copy them to a fresh container with only the necessary runtime dependencies under `$FREESURFER_HOME`.

Finally, I batched all the ENV instructions into a handful to avoid creating superfluous layers each time.

Another area of improvement would be image size. In my current experiment, the image weighs 15 GB which is quite large. For applications which just need the command-line tools, I wonder how much could be reduced by removing the UI specific parts for instance. This could become another build argument for the image, in addition to the targeted FreeSurfer's version.

Hope this helps, happy to contribute my work if you want to.

**Comment by ghisvail** [comment]
> I think they would be particularly useful for switching between versions to download.

For instance [here](https://github.com/pwighton/freesurfer/blob/4821e1dc972050e52e26cc5b12edc91801122011/docker/Dockerfile.7.3.3#L15) where the image says the version is 7.3.3 but the downloaded version is actually 7.3.2.

**Comment by buildqa** [comment]
There  was a PR to neurodocker to support FreeSufer 7.3.2
https://github.com/ReproNim/neurodocker/pull/469

Once integrated, that can be used that to build the container `pwighton/freesurfer:7.3.2`. 

You'll have to mount your FreeSurfer license file and tell FreeSurfer where it's located, e.g.
```
docker run -it --rm \
  -v ~/Downloads/license.txt:/license.txt:ro \
  -e FS_LICENSE='/license.txt' \
  ...
  pwighton/freesurfer:7.3.2 \
    ...
```  

For reference, the container `pwighton/freesurfer:7.3.2` was built using the following command:
```
docker run pwighton/neurodocker:20220822 generate docker \
  --base-image ubuntu:xenial \
  --pkg-manager apt \
  --yes \
  --freesurfer \
    method=binaries \
    version=7.3.2 \
| docker build --no-cache --network host -t pwighton/freesurfer:7.3.2 -

**Comment by pwighton** [comment]
[freesurfer/freesurfer](https://hub.docker.com/repository/docker/freesurfer/freesurfer/tags?page=1&ordering=last_updated) now has containers for versions 7.3.0, 7.3.1 and 7.3.2.  I can add a container for 7.3.3 [once there is a centos8 release](https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.3.3/)

> For that, you might want to investigate build arguments to avoid unnecessary duplication. I think they would be particularly useful for switching between versions to download.

I'm not sure how I feel about build arguments.  At some point, the dependencies for FreeSurfer will change and there doesn't seem to be a way to manage this with build arguments.  So we would end up with several dockerfiles each one building a set of versions.  That seems harder to manage than a one-to-one mapping of versions-to-dockerfiles.

> I wonder how much could be reduced by removing the UI specific parts for instance.

It can be reduced by quite a lot! :smile: There is a recon-all only [version of 7.1.1](https://hub.docker.com/layers/pwighton/freesurfer/7.1.1-min/images/sha256-d6b94ae6ff7a2490ded07bacba1eacd04d02f259cdfb94167dcccdaaf02c446d?context=explore) that is only 360 MB!  We used `neurodocker minify` to create this (details [here](https://github.com/pwighton/fs-docker/blob/master/notes/20201127-fs711-neurodocker-min.md)).  I've been trying to maintain FreeSurfer support in neurodocker because I think it's the best way to deal with specific use cases like this.  e.g. some folks will want a minified container with only recon-all, some will want samseg, some will want all the dependencies to run tracula or the infant stream, etc.

I've been keeping notes on how to use (neuro)docker for a variety of use cases at [pwighton/fs-docker](https://github.com/pwighton/fs-docker) and would be happy to take suggestions or PRs!

**Comment by buildqa** [comment]
As of this writing, we do not know when the next point release will be out.  There is currently no 7.3.3 release and the link reference above has been removed.

**Comment by ghisvail** [comment]
> I'm not sure how I feel about build arguments.

They would sure enable less repetition. The download stage is sufficiently common between all recipes to be factored out, especially if you use multi-stage builds.

> So we would end up with several dockerfiles each one building a set of versions.

Just a single Dockerfile parameterized over the FS version to download, afaik.

>  I've been trying to maintain FreeSurfer support in neurodocker [...]

I agree with you on the value proposition offered by neurodocker for tailormade images with a specific set of tools. I was more thinking in the general sense, users reaching for an official container would either want it for `Freeview` and tools, or just the command-line tools. My proposal was for providing a "nogui" image (with a restricted set of RPM packages installed) in addition to the existing "full" one in the official offering.

**Comment by buildqa** [comment]
It does work to create a standalone, e.g., appimage, of freeview.  It's not clear to me where the line would be drawn w.r.t distributing [freeview + maybe some commands] and then [all other commands] - whether or not things are installed in a container.  It would increase the number of packages to support and the complexity for some users.

**Comment by ghisvail** [comment]
@buildqa I believe projects not using the GUI tools (like nipype / pydra / any CLI pipeline tool meant to be run on clusters) would benefit a lot from a no-gui variant of the official container image. This would certainly be the case for [pydra-freesurfer](https://github.com/aramis-lab/pydra-freesurfer/) which I am currently working on.

**Comment by buildqa** [comment]
Currently I believe pwighton is looking out to make something of a generic container image available on neurodocker when new FS releases happen.  I"m not sure we can provide more support than that however.
