### ISSUE TITLE
FreeSurfer 7.2.0 Bug: -nuintensitycor for UltraHighField + sub-millimeter optimized pipeline

### ISSUE THREAD

**Issue by mafortin** [freesurfer/freesurfer#1028]
Hi all,

I am currently trying the FreeSurfer 'optimized' pipeline for 7T data (exactly: (0.6mm)3 7T 1Tx MPRAGE) as described in this link: https://surfer.nmr.mgh.harvard.edu/fswiki/HighFieldRecon

1) However, I am facing issues with the B1+ inhomogeneity correction done during autorecon1. In fact, the '-nuintensitycorr' step between orig.mgz -> nu.mgz completely destroys the B1+ homogeneity gained from the SPM12 BiasField Correction applied beforehand. 

The exact command line I'm using is:

$ recon-all -all -s 001bc -hires -i BC_MPRAGE.nii -expert expert-file.opts

      - where BC_MPRAGE.nii is the output of SPM12 BiasField Correction (i.e., the bias field corrected MPRAGE image) and expert-file.opts the file containing ''mris_inflate -n 100" as recommended from the link above. 

The whole recon-all runs properly without errors, but the B1+ homogeneity is worse after the NU intensity correction... See screenshots below (orig.mgz VS nu.mgz).

Orig.mgz:
![001_orig](https://user-images.githubusercontent.com/51452174/196982539-66fda55c-a259-4684-aa46-b01daff44864.png)
Nu.mgz:
![001_nu](https://user-images.githubusercontent.com/51452174/196982573-3cfec015-5dbf-4615-9c2e-2efac675ed9f.png)

I have tested the '-nonuintensitycor' flag, but it exited with errors. I also tried to set the number of iterations to 0, but the same problem of increasing the B1+ inhomogeneity was still there.

Moreover, I tried the exact same pipeline but without passing the data through SPM12 beforehand (i.e., the same MPRAGE image but not preprocessed). It did the same thing (i.e., increase B1+ inhomogeneity), but to an even worse level since the input image was more B1+ inhonogeneous to start with.

I also tested in another healthy subject to verify if it was not a subejct-specific bug, but it produced the exact same thing.

Question: How can the **inhomogeneity correction** process **increase** the inhomogeneity instead of reducing it?

In addition, I tried the 'normal' FreeSurfer recon-all pipeline without adding any '-hires' or '-expert' flags on the bias field corrected MPRAGE to see if the results were different for the two pipelines given the same input. Both results were visually comparable and decent/usable. However, I did the same thing for the unprocessed MPRAGE (i.e., **not** put through SPM12 before giving it as input to FreeSurfer), and the difference between aseg.mgz results from both pipelines are quite striking:

FreeSurfer 'normal' recon-all pipeline aseg.mgz (on top of input MPRAGE image):
![image](https://user-images.githubusercontent.com/51452174/196989731-c3ba5f78-8f48-40f3-90c8-9b5dd15eb390.png)

FreeSurfer 7T recon-all pipeline aseg.mgz (on top of input MPRAGE image): 
![image](https://user-images.githubusercontent.com/51452174/196989501-9a72c22c-9246-4197-9eda-94e37e526dfd.png)

Q: how can the FreeSurfer proposed 7T pipeline be worse than the 'normal' FreeSurfer pipeline even in regions unaffected by large B1+ inhomogeneities? Q: how can the recon-all exits without error while procuding very low quality results as shown with the screenshot above?

----
2) Still related, but slightly on another matter, in the link above about the FreeSurfer pipeline for 7T data, the following part is unclear:

"""
Recommended bias-correction parameters:

Bias FWHM = 18
Sampling distance = 2
"""

A Bias FWHM of 18 mm is simply not possible with SPM12 (minimum being 30 mm). Q: is it for SPM12 or something as part of recon-all? For the sampling distance, it's fine with the 2 mm in SPM12.

I am using FS version 7.2.0 (freesurfer-linux-ubuntu18_x86_64-7.2.0-20210721-aa8f76b) on Linux Ubuntu 18.04 bionic.

Have a great day! 🙂

Marc-Antoine

**Comment by buildqa** [comment]
If your issues are still not answered, you should post to the Freesurfer help list where more people are likely to see it.

**Comment by buildqa** [comment]
Author should post above to freesurfer@nmr.mgh.harvard.edu, so closing here.
