### ISSUE TITLE
fs_time args check issue

### ISSUE THREAD

**Issue by slieped** [freesurfer/freesurfer#1030]
**Issue**:
I had several subjects within a same folder that tried to re-run. However, recon-all was failing for all of them, in the same exact step: BA_exvivo labels. Concretely, to the mri_label2label command.

After going though the recon-all and fs_time script, I realized that the second one does an initial ARGS check to identify if the user has request `-help `or `-version `string.

If the `$SUBJECTS_DIR` contains the word `-version` (as it was my case), then, fs_run only echo the version and exit. Thus, the actual mri_label2label command is not. 

The subjects were initially recon-all-ed in a different folder with different name. Thus, this issue did not happened in the initial run.

**Freesurfer version:**
freesurfer-linux-centos7_x86_64-7.1.1-20200723-8b40551

**Reproduce error:**
1) Recon-all one subject
2) Move to a folder that do have "*-version*" in its name (path-name)
3) Try to re-run again ( using the -autoreconX or --balabels flag)

**Potential (easy) solution:**
Instead of doing a grep to "-version", check for " -version " (with pre and post whitespace)

**Comment by yhuang43** [comment]
This should be fix in commit https://github.com/freesurfer/freesurfer/commit/0ee6c3beb95a1ebc194faa5f322f51695591dae8
