### ISSUE TITLE
Question about the unit of CSF in aseg.stats

### ISSUE THREAD

**Issue by alx080** [freesurfer/freesurfer#1031]
Hello everybody,

is the cerebrospinal spinal fluid unit also mm3? Or which CSF is specified here? In all MRI's it's as low as in the picture.

BR, Alex

![csf](https://user-images.githubusercontent.com/95551024/199091631-b447e5cf-3951-4945-84a8-44387cf46ab1.jpg)

**Comment by dngreve** [comment]
Please post non-code related questions to the FS list freesurfer@nmr.mgh.harvard.edu. To answer your question, yes.
