### ISSUE TITLE
Error running mri_synthseg from a docker

### ISSUE THREAD

**Issue by devDonnn** [freesurfer/freesurfer#1036]
I try to run mri_synthseg from a docker image but I get the following error:

>  docker run --rm -it --platform linux/amd64 freesurfer/freesurfer:7.3.2 mri_synthseg

`F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] > bucket_limits_[i - 1] (0 vs. 10)
qemu: uncaught target signal 6 (Aborted) - core dumped`

Any ideas how to fix it? I have Apple's M1 Max chip.

**Comment by pwighton** [comment]
I'm guessing this is a Mac M1 issue.  I'm not getting that behavior on my x86_64 Linux machine:

```
(base) paul@paul-7550:~$ docker run --rm -it freesurfer/freesurfer:7.3.2 mri_synthseg
usage: mri_synthseg [-h] [--i I] [--o O] [--parc] [--robust] [--fast] [--vol VOL] [--qc QC] [--post POST]
                    [--resample RESAMPLE] [--crop CROP [CROP ...]] [--threads THREADS] [--cpu] [--v1]

SynthSeg

optional arguments:
  -h, --help            show this help message and exit
  --i I                 Image(s) to segment. Can be a path to an image or to a folder.
  --o O                 Segmentation output(s). Must be a folder if --i designates a folder.
  --parc                (optional) Whether to perform cortex parcellation.
  --robust              (optional) Whether to use robust predictions (slower).
  --fast                (optional) Bypass some processing for faster prediction.
  --vol VOL             (optional) Output CSV file with volumes for all structures and subjects.
  --qc QC               (optional) Output CSV file with qc scores for all subjects.
  --post POST           (optional) Posteriors output(s). Must be a folder if --i designates a folder.
  --resample RESAMPLE   (optional) Resampled image(s). Must be a folder if --i is a folder.
  --crop CROP [CROP ...]
                        (optional) Only analyse an image patch of the given size.
  --threads THREADS     (optional) Number of cores to be used. Default is 1.
  --cpu                 (optional) Enforce running with CPU rather than GPU.
  --v1                  (optional) Use SynthSeg 1.0 (updated 25/06/22).
```

This seems related to [this issue](https://github.com/tensorflow/tensorflow/issues/52845), which I'm not sure how to resolve in FreeSurfer.

@buildqa, Do FreeSurfer builds support Apple M1 chips?  E.g. would `mri_synthseg` work on a Mac M1 with a native install of either https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.3.2/freesurfer-darwin-macOS-7.3.2.tar.gz or https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.3.2/freesurfer-darwin-macOS-7.3.2.pkg?  I don't have access to an Apple M1 machine, so I can't test it myself.

Once we understand how to get mri_synthseg working natively on an M1 chip, we can see if it would be possible to get it working in a container as well.

**Comment by buildqa** [comment]
I would expect to see an error like "illegal instruction" if you are trying to run non-compatible Intel binaries on an ARM machine, e.g., they contain AVX instructions that cannot be translated to run on ARM.    But this post https://github.com/docker/for-mac/issues/6264 seems to indicate that error is a bug in quemu virtualization trying to run Intel instructions on arm processor.    I would test your commands directly by installing freesurfer on MacOS and bypass the container to see if you get "illegal instruction" when you run them.

**Comment by devDonnn** [comment]
I have downloaded and installed FS v7.3.2 release (freesurfer-darwin-macOS-7.3.2.tar.gz). Now I get "zsh: illegal hardware instruction  mri_synthseg". Is there a way to solve it?

**Comment by buildqa** [comment]
For a machine with Apple Silicon (M1 or M2 chip) running MacOS Monterey (12.X) with the freesurfer 7.3.2 release installed, you can try modifying the fspython distribution as follows.  Make sure you have set FREESURFER_HOME and have already source'd the appropriate freesurfer environment setup script SetUpFreeSurfer.{sh,csh} for your login shell.
1) uninstall the current version of tensorflow with
$ sudo $FREESURFER_HOME/python/bin/python3 -m pip uninstall tensorflow
... apart from any warnings you should see the output ...
Successfully uninstalled tensorflow-2.4.1
2) download tensorflow-2.4.1-py3-none-any.whl from https://drive.google.com/file/d/15Qeve5FIA137KON67ehKIOyXy1N0PbAC/view?usp=share_link   For the command below it has been downloaded into the current directory where the command is being run.
$ sudo -H $FREESURFER_HOME/python/bin/python3 -m pip install ./tensorflow-2.4.1-py3-none-any.whl
... apart from warnings and output about requirements (which should all be satisfied) you should see the output ...
Successfully installed tensorflow-2.4.1

Then try running mri_synthseg again.  You may want to consider subscribing to the freesurfer help list for ongoing updates and/or discussions as that info is not on GitHub.

**Comment by devDonnn** [comment]
Works well! Thanks a lot.
