### ISSUE TITLE
ERROR: GetDICOMInfo(): dcmGetDWIParams() 7

### ISSUE THREAD

**Issue by mc0514** [freesurfer/freesurfer#104]
When I using the command dcmunpack -targ sess01 -run 101 bold nii f.nii -run 301 bold nii f.nii ....
Errors occurred likes below:
mri_convert.bin DICOM/XX_0003 sesso1/bold/101/f.nii --nskip 0 --ndrop 0 
nskip = 0
ndrop = 0
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from DICOM/XX_0003...
Starting DICOMRead2()
dcmfile = DICOM/XX_0003
dcmdir = DICOM
WARNING: tag image orientation not found in DICOM/XX_0003
ERROR: GetDICOMInfo(): dcmGetDWIParams() 7
DICOM File: DICOM/XX_0003
break DICOMRead.c:5228
Ref Series No = 101
ERROR: bits = 0 not supported.
My OS is LINUX 16.04 and FreeSurfer is V6.0.0

**Comment by zkaufman** [comment]
The "Issues" section of the freesurfer github page is generally reserved for source code, build, test, and platform related issues. For general support using the official releases of the freesurfer application, please submit your issue/question to the freesurfer support list:

  https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport

Thanks.

**Comment by mc0514** [comment]
@zkaufman Thans for your notification. I have send my question to the mailing list.

**Comment by zkaufman** [comment]
Link to the thread:

  http://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg53860.html

Hope you get a suitable response.

Marking this issue closed
