### ISSUE TITLE
Python module 'surfa' is not found in dev version

### ISSUE THREAD

**Issue by devDonnn** [freesurfer/freesurfer#1040]
I have downloaded the development version of FreeSurfer (freesurfer-darwin-macOS-dev.tar.gz | 2022-12-13 08:35 | 5.4G) and tried mri_synthstrip:
`Traceback (most recent call last):
  File "/Applications/freesurfer/dev/python/scripts/mri_synthstrip", line 10, in <module>
    import surfa as sf
ModuleNotFoundError: No module named 'surfa'`

I also have FS v7.3.2 which does have this 'surfa' module. Why is it not within the dev version? I need it since 'surfa' has been updated for mri_synthstrip v1.3.

**Comment by avnishks** [comment]
Hi,

We had to remove surfa from the packages list due to a bug. It has been fixed now. Please try again.

**Comment by devDonnn** [comment]
Works well, thanks!
