### ISSUE TITLE
ERROR: thresh = 2,0, must be 1.3, 2.0, 2.3, 3.0, 3.3, 4.0

### ISSUE THREAD

**Issue by qumaciel** [freesurfer/freesurfer#1059]
Hi there,

I'm trying to run a MC [Clusterwise Correction for Multiple Comparisons](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/MultipleComparisonsV6.0) for a t-test `g2v0`.

```
> cat group.diff.mtx
1 -1
```

First I run for the uncorrected data:
```
mri_glmfit \
  --y lh.adctrl.thickness.10.mgh \
  --fsgd g2v0.fsgd dods \
  --C group.diff.mtx \
  --surf fsaverage lh \
  --cortex \
  --glmdir lh.adctrl.t-test.glmdir \
  --eres-save
```

Then, I correct
```
mri_glmfit-sim \
  --glmdir lh.adctrl.t-test.glmdir \
  --mczsim 2.3 pos \
  --cwp 0.99 \
  --overwrite \
  --bg 6 \
  --2spaces
```

`mri_glmfit-sim` exits and I get the following output:
```
gdfRead(): reading g2v0.fsgd
INFO: gd2mtx_method is dods
Reading source surface /home/leonardo/Desktop/Luciano_Apathy/freesurfer/fsaverage/surf/lh.white
Number of vertices 163842
Number of faces    327680
Total area         65417.000000
AvgVtxArea       0.399269
AvgVtxDist       0.721953
StdVtxDist       0.195472

dev
cwd /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0
cmdline mri_glmfit --y lh.adctrl.thickness.10.mgh --fsgd g2v0.fsgd dods --C group.diff.mtx --surf fsaverage lh --cortex --glmdir lh.adctrl.t-test.glmdir --eres-save 
sysname  Linux
hostname leonardo-Precision-Tower-3420
machine  x86_64
user     leonardo
FixVertexAreaFlag = 1
UseMaskWithSmoothing     1
OneSampleGroupMean 0
y    /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0/lh.adctrl.thickness.10.mgh
logyflag 0
usedti  0
FSGD g2v0.fsgd
labelmask  /home/leonardo/Desktop/Luciano_Apathy/freesurfer/fsaverage/label/lh.cortex.label
maskinv 0
glmdir lh.adctrl.t-test.glmdir
IllCondOK 0
ReScaleX 1
DoFFx 0
Creating output directory lh.adctrl.t-test.glmdir
Loading y from /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0/lh.adctrl.thickness.10.mgh
   ... done reading.
INFO: gd2mtx_method is dods
Saving design matrix to lh.adctrl.t-test.glmdir/Xg.dat
Computing normalized matrix
Normalized matrix condition is 1
Matrix condition is 1.05263
Found 149955 points in label.
Pruning voxels by thr: 1.175494e-38
Found 146359 voxels in mask
Saving mask to lh.adctrl.t-test.glmdir/mask.mgh
Reshaping mriglm->mask...
search space = 72894.413619
DOF = 37
Starting fit and test
Fit completed in 0.00911667 minutes
Computing spatial AR1 on surface
Residual: ar1mn=0.995579, ar1std=0.001626, gstd=6.079885, fwhm=14.317036
Writing results
  group.diff
    maxvox sig=5.68692  F=31.5805  at  index 113704 0 0    seed=1674525509
Computing efficiency
mri_glmfit done
ERROR: thresh = 2,3, must be 1.3, 2.0, 2.3, 3.0, 3.3, 4.0

``` 

There is something wrong with the input handling of   `--mczsim 2.3 pos`. Somehow the decimal separator  `2.3` changes to `2,3`.
Did I miss something here?

Ubuntu 18.04.6 LTS
kernel: 4.15.0-202-generic
Freesurfer-nightly

**Comment by dngreve** [comment]
use 2.3 not "2,3"
also, better to submit these types of things to the freesurfer list 
***@***.***

On 1/17/2023 3:04 PM, qumaciel wrote:
>
>         External Email - Use Caution
>
> Hi there,
>
> I'm trying to run a MC Clusterwise Correction for Multiple Comparisons 
> <https://secure-web.cisco.com/1zdaegXCpNHPDwIcSTuq2s9KV7CB9OnEfOVRcUR9fOZlmdG2H3l1GkFqyQ1SMIRI3BO09Kjo8PB-rMQf_c33wHXeh_b67nBzwVcJaKCAgElp2iU65SlSvwkE6lU1lTOcI6N5fO7SY6MYl6OSmmRR0VacM62FM_nbgWCOxGbat7ntOKx-3xZDEmWGMHNbavQ6J-TAaQO8feZyuUXBKuURdZkw7u7BLHlMZ6MZBp_5XRXcCTeL0AtmqbdTS0rRER3InMz0xf81W3GxxYAxSscwiYENzCRt7KyW7W8gTCST8zT_XVG0V9uLLONBCAFyCvQZj/https%3A%2F%2Fsurfer.nmr.mgh.harvard.edu%2Ffswiki%2FFsTutorial%2FMultipleComparisonsV6.0> 
> for a t-test |g2v0|.
>
> |> cat group.diff.mtx 1 -1 |
>
> First I run for the uncorrected data:
>
> |mri_glmfit \ --y lh.adctrl.thickness.10.mgh \ --fsgd g2v0.fsgd dods \ 
> --C group.diff.mtx \ --surf fsaverage lh \ --cortex \ --glmdir 
> lh.adctrl.t-test.glmdir \ --eres-save |
>
> Then, I correct
>
> |mri_glmfit-sim \ --glmdir lh.adctrl.t-test.glmdir \ --mczsim 2.3 pos 
> \ --cwp 0.99 \ --overwrite \ --bg 6 \ --2spaces |
>
> |mri_glmfit-sim| exits and I get the following output:
>
> |gdfRead(): reading g2v0.fsgd INFO: gd2mtx_method is dods Reading 
> source surface 
> /home/leonardo/Desktop/Luciano_Apathy/freesurfer/fsaverage/surf/lh.white 
> Number of vertices 163842 Number of faces 327680 Total area 
> 65417.000000 AvgVtxArea 0.399269 AvgVtxDist 0.721953 StdVtxDist 
> 0.195472 dev cwd /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0 
> cmdline mri_glmfit --y lh.adctrl.thickness.10.mgh --fsgd g2v0.fsgd 
> dods --C group.diff.mtx --surf fsaverage lh --cortex --glmdir 
> lh.adctrl.t-test.glmdir --eres-save sysname Linux hostname 
> leonardo-Precision-Tower-3420 machine x86_64 user leonardo 
> FixVertexAreaFlag = 1 UseMaskWithSmoothing 1 OneSampleGroupMean 0 y 
> /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0/lh.adctrl.thickness.10.mgh 
> logyflag 0 usedti 0 FSGD g2v0.fsgd labelmask 
> /home/leonardo/Desktop/Luciano_Apathy/freesurfer/fsaverage/label/lh.cortex.label 
> maskinv 0 glmdir lh.adctrl.t-test.glmdir IllCondOK 0 ReScaleX 1 DoFFx 
> 0 Creating output directory lh.adctrl.t-test.glmdir Loading y from 
> /home/leonardo/Desktop/Luciano_Apathy/freesurfer/g2v0/lh.adctrl.thickness.10.mgh 
> ... done reading. INFO: gd2mtx_method is dods Saving design matrix to 
> lh.adctrl.t-test.glmdir/Xg.dat Computing normalized matrix Normalized 
> matrix condition is 1 Matrix condition is 1.05263 Found 149955 points 
> in label. Pruning voxels by thr: 1.175494e-38 Found 146359 voxels in 
> mask Saving mask to lh.adctrl.t-test.glmdir/mask.mgh Reshaping 
> mriglm->mask... search space = 72894.413619 DOF = 37 Starting fit and 
> test Fit completed in 0.00911667 minutes Computing spatial AR1 on 
> surface Residual: ar1mn=0.995579, ar1std=0.001626, gstd=6.079885, 
> fwhm=14.317036 Writing results group.diff maxvox sig=5.68692 F=31.5805 
> at index 113704 0 0 seed=1674525509 Computing efficiency mri_glmfit 
> done ERROR: thresh = 2,3, must be 1.3, 2.0, 2.3, 3.0, 3.3, 4.0 |
>
> There is something wrong with the input handling of |--mczsim 2.3 
> pos|. Somehow the decimal separator |2.3| changes to |2,3|.
> Did I miss something here?
>
> Ubuntu 18.04.6 LTS
> kernel: 4.15.0-202-generic
> Freesurfer-nightly
>
> —
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1NlB5EAqkZtFaxKfFMEilJlNqIR9R0nuYUEucvRCyItJ-mp-W9Gl-uK2nMHzFOp9lbaSQ0yKZ3gX15ynDtcZkQb1vyBjN0Fx7quAui9HuvGix-a0z60l4Ipv-dWw0gthMZ3EL1_kzPXooD80uMhsRztkffye7NFxcaHzBtHrUy-DPV86f4bdzycSaB6N56i6uYFD7tDlMi6LWKhav-6oKYocqlLrqz-OHFMOWUlGXB4kq2s6ur3bovSqq9koGsysnqvV8_EsPxmCw2KPK2Yih3ebdE-sm81c29JWP2HuSr4jUqfk4hmMpVUlQcCzOnvrt/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1059>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1VTG3jaFiDJ2gxYHIfAdC8zBwwPik_3ia0tbSimvpO3Xi5I-G5BgFFUYI5gVPTRDtBst1RPWkx3JMbtAJhs6AhgTgBuwguNrSJGFHBDQfv89x2pjBbe5zEVoUCFK2TSmgPWEPafjpbgw_q2PLmC7r-UKROjEXcYbQ_C0TlxX5ozXHeg9_7bzM_R9nTb3ut2pfc9RG9bfAPqsX3cA3qS1XLlC-pSpJtDEkaQD9PN40AZmU0LJtY_dgZcfJRsxMFlM1NE_UlxggWpBpPOfXV07BAfjIZel0V2uCDH0hRHH8zqohMF92PSxymTWonH9pt4zJ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VT2CAGHTVOJ2TYAO33WS33OLANCNFSM6AAAAAAT6ITJJU>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>
>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by qumaciel** [comment]
> use 2.3 not "2,3" 

That is the thing. I used 2.3 but somehow the code changed my input and replaced the dot by a comma.

**Comment by dngreve** [comment]
it is probably your locale. which verison of FS are you running?

On 1/18/2023 10:42 AM, qumaciel wrote:
>
>         External Email - Use Caution
>
>     use 2.3 not "2,3"
>
> That is the thing. I used 2.3 but somehow the code changed my input 
> and replaced the dot by a comma.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1cjDP2hQv7AutKplghPcvyf2_XbkxnMWNYSB25e6JbxlficHPBrBQBK0iU458-IE9Ah2J4NWPqRlna4B1c7xTP4SXI87roo8pYLHY9iNoXdxJUtVxyWySt5Hld4dZwXtcN7ilpl2gOSLSQvhszEjflWRAJ8uvo9jUVpL_RcScV-2yB7Fltz2jo_gnoD43736DWMU2y79uwjmbn8nHpQn18rGnqLqg1UszYeEpapZx-K76Yh3s9lIr-pdwrLXVIrqUkaKA4sRhysEkif3Natlmp42VmaFDMtkWKkoHReYC4UONjk8a1Z_Iyn_uN-QOKQmrh5e-4hIstIdOb0Navq9czw/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1059%23issuecomment-1387275785>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1eA-lowK2R1cuVN0VkfHxgURbq3VrXO2_IckuDcCJqo-Ta1ibVVabT4kAoJuEiDROVkwYT3_fNkHRey3nAyVRxiYubH2IQO2uvjyNEsRTMZoVoh_9nZ_ZGbitwHT59gWhQxVVU-EGqM_fCbLHatm-nPfBgZk_6qHKF-kCDWLszW0Y6s-SMzPP_gHinqKD9a3GLWkgoIB9cklIEzKF7CJHxkDlMYcbDkU2Gcr8NhzqePgaeSHq0i6a1O3eGUriEtWotOkezqDfkJxuc2iOH1Suk49BnIm3tyBI51_ZM1XYJTauvIXViZaC0jN7fMZyZHWSPU8W9Qb6aZls4ndiCmZuHQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VXYQJVEW5XV2TTAPADWTAFP5ANCNFSM6AAAAAAT6ITJJU>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by qumaciel** [comment]
> it is probably your locale. 

That is exactly why I'm posting this here. I think the input handling of this should account for this possibility. 
In case the user hard type "2.3" it should interpret correctly, independent of worstation's locale.

> which verison of FS are you running?

I'm using the nightly snapshot freesurfer-linux-ubuntu18_x86_64-7-dev.tar.gz from 2023-01-17.
Same happens with the  7.3.2 release from Aug 2022.

**Comment by buildqa** [comment]
I assume you are running on Ubuntu 18.  There are postings about Ubuntu OS 18 updates affecting locale settings on the askubuntu.com web site, but one that matches what you are seeing is, https://askubuntu.com/questions/924750/period-has-become-a-comma-after-update

We can't control what locales are installed on your machine or what your current locale is set to.  But in general, if you want to modify the locale in your current shell, you can try the following.

Get a list of the locales currently available on your machine by looking at the output from,
$ locale -a

From that list choose a locale.  Set the environment variable LC_ALL to your chosen locale, e.g., in bash shell
$ export LC_ALL=en_US.UTF8

The output of "locale" should then show other LC environment variables have been set to that locale, e.g.,  something like,

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

The LANG and LC* settings listed above for the output from locale is what one of our Ubuntu18 machines report.

**Comment by qumaciel** [comment]
That worked for me, thank you @buildqa .

I still think the input handling of `mri_glmfit` could be improved, e.g.  setting `--cwp 0.99` did not change to 0,99.
