### ISSUE TITLE
SynthStrip outputs a slightly modified qform

### ISSUE THREAD

**Issue by devDonnn** [freesurfer/freesurfer#1060]
I've run SynthStrip using a docker image v1.3 and it outputs a brain mask (-m) with a slightly modified qform and in turn voxel sizes. The original image had isotropic 1 mm^3 voxel sizes whereas after SynthStrip the brain mask has 1.000005 x 1.000000 x 1.000000. I attach a NIfTI image for which the problem occurs and the command I ran: `python3 synthstrip-docker.py -i T1c.nii.gz -m mask.nii.gz`.

[T1c.nii.gz](https://github.com/freesurfer/freesurfer/files/10502478/T1c.nii.gz)

**Comment by ahoopes** [comment]
Thanks for sending the example image @devDonnn. Looks like under the hood nibabel updates the header pixdim when the qform data is set, so I'll have to switch the order of operations in the surfa utils. I can release a new version at some point in the next day or two.

**Comment by ahoopes** [comment]
Ok this should be fixed in synthstrip container v1.4 (surfa v0.4.2) and it will make it into the freesurfer dev releases within the next day or two
