### ISSUE TITLE
install fails looking for synthsr models

### ISSUE THREAD

**Issue by ebrahimebrahim** [freesurfer/freesurfer#1064]
During the `make install` step of the build process on my linux system I get

```txt
CMake Error at mri_synthsr/cmake_install.cmake:71 (file):
  file INSTALL cannot find
  "/home/ebrahim/freesurfer-superbuild/freesurfer/mri_synthsr/synthsr_v20_230130.h5":
  No such file or directory.
```

which is fixed if I comment out the lines added in https://github.com/freesurfer/freesurfer/pull/1062

I followed the `git clone` and `git-annex` instructions in the [build guide](https://surfer.nmr.mgh.harvard.edu/fswiki/BuildGuide) and I indeed did not end up having those v20 models:
```txt 
$ tree mri_synthsr/
mri_synthsr/
├── CMakeLists.txt
├── mri_synthsr
├── mri_synthsr_hyperfine
├── synthsr_v10_210712.h5
└── synthsr_v10_210712_hyperfine.h5
```

**Comment by avnishks** [comment]
Fixed now. Added the missing model files.
