### ISSUE TITLE
How to use CUDA 8.0 ?

### ISSUE THREAD

**Issue by fallingstarriver** [freesurfer/freesurfer#107]
when I type cudadetect 
The result is:

# cudadetect.bin: error while loading shared libraries: libcudart.so.5.0: cannot open shared object file: No such file or directory

But I have installed NVIDIA driver CUDA 8.0

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
|  0%   41C    P8    13W / 220W |    319MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2489    G   /usr/bin/Xorg                                  179MiB |
|    0      3123    G   /usr/bin/gnome-shell                           136MiB |
|    0      4044    G   /usr/lib64/firefox/plugin-container              1MiB |
+-----------------------------------------------------------------------------+

What's the diference between CUDA 5.0 and CUDA 8.0 .

Is FreeSurfer  compatible with CUDA 8.0?

**Comment by buildqa** [comment]
I’m not familiar with specific differences between Cuda 5 and 8.  I believe that as of version 6 there was a more unified memory model, and I presume newer versions of Cuda work with newer/faster Nividia hardware.  I tried to quickly find a comparison chart that goes up thru version 8, but even the wikipedia page is not up to date, https://en.wikipedia.org/wiki/CUDA

There is an archive of (CentOS6) libraries/packages you can download that can be used to build FreeSurfer from source; it contains a copy of Cuda 5.0.35 (see step 3 in how to build http://freesurfer.net/fswiki/freesurfer_linux_developers_page).  I used this package as part of following those steps to build the Freesurfer source code from the dev branch on GitHub.

As of this writing, to build the dev branch with (any) cuda distribution, my understanding is you need to run the configure command with the added options —with-cuda=<path to cuda distribution> and —enable-fermi-gpu.  So if your cuda distribution was installed under /home/osboxes/unzip/centos6-x86_64-packages/CUDA/5.0.35-rh5, then your configure command might look something like,

$ ./configure —disable-Werror —enable-fermi-gpu —with-cuda=/home/osboxes/unzip/centos6-x86_64-packages/CUDA/5.0.35-rh5 —with-pkgs-dir=/home/osboxes/unzip/centos6-x86_64-packages

You could try using a different version of cuda and then set —with-cuda to point to its location, etc.  I used the configure command above on a CentOS7 machine (release 7.4.17-8) to build with the 5.0.35 Cuda distribution in that CentOS6 packages archive.

BTW - I attempted to make a CentOS 7 VM that does not need the CentOS6 packages archive, but I was not able to replace everything in the archive.  I can try and send you a link to my experimental VM image if you want to give it a try.

Please be aware that per the system requirements listed under https://surfer.nmr.mgh.harvard.edu/fswiki/SystemRequirements, FreeSurfer development will no longer support [further] CUDA or GPU development in preference to using OpenMP.

**Comment by melrobin** [comment]
I was able to get CUDA 9.1 to work well.   The build can also fail if nvcc is not in the PATH.  An easy way to check to see if CUDA will be successfully built is to see if the Makefile has nonempty CUDA_DIR and CUDA_LIBS variables.  As buildqa mentions this is accomplished by adding the --with-cuda configure options.

**Comment by DingkunLiu** [comment]
I think fermin is Nvidia's oldest gpu version, could it still be compatible with newer maxwell or volta gpu?

**Comment by buildqa** [comment]
I would ncheck Nividia's web site/hardware specs to see what compatibility is like.

**Comment by buildqa** [comment]
Closing this

**Comment by haanguloo** [comment]
Hi @melrobin, I have been trying to build it with CUDA9.1 but no success so far. It looks that you are the only one here who found a way to make it work. In my case, I am trying to use FreeSurfer with a Nvidia Tesla (K80) card, and with CentOS 7. I know that this thread is closed, but I would like to request some help from you since I have been working on this for almost a month without success. I know that you have to build the source from zero, but what kind of steps did you take to make it work? What was the step-by-step procedure that you made?
I would appreciate if you can shed some light on this case.
Thanks.

**Comment by melrobin** [comment]
I have PM'd you.

**Comment by raintwoto** [comment]
> I have PM'd you.

Hi @melrobin , Could you also PM me about your method. I am trying to use the 2080ti and CUDA 10.1. Thank you very much

**Comment by VasudevDevulapally** [comment]
> I have PM'd you.

@melrobin , is there a way to get CUDA9.1 running, can you please suggest me the procedure. I was trying to pm you .
Kindly please suggest it in open forum so that others can even adapt the CUDA version for their use.

**Comment by salim-alwasity** [comment]
Hi
I know that CUDA is not supported in the newer version of FREESURFER, but is there any chance to build an other FREESURFER version with newer CUDA. I have Nvidia P4000 GPU, and run CUDA 11.

**Comment by molicaca** [comment]
> I have PM'd you.

Hi @melrobin. I'm also trying to recompile the Freesurfer via the cuda 9.1. Could you help me with that? A brief introduction would make sense. Thank you in advance.
