### ISSUE TITLE
Freesurfer SynthSR V2 not working on ubuntu20_x86_64-7-dev version

### ISSUE THREAD

**Issue by joaco18** [freesurfer/freesurfer#1073]
Hello everyone!

I'm running SynthSR from freesurfer and I wanted to try v2 available since some days ago. Therefore I downloaded and installed the dev version of freesurfer as indicated in a tweet by J.E. Iglesias. I downloaded freesurfer-linux-ubuntu20_x86_64-7-dev.tar.gz from [https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev/](https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev/). Then I followed the installation instructions from the freesurfer wiki.

When I run 
`mri_synthsr --i <path_to_myfile>ses-0000/sub-train001_ses-0000_ncct.nii.gz --o <path_to_myfile>/sub-train001_ses-0000_ncct-sr.nii.gz --ct`

I get the following output:

> Using general model from January 2023 (version 2)
> /home/jseia/freesurfer-dev/models/synthsr_v20_230130.h5
> using 3 threads
> predicting 1/1
> 
> the following problem occured when preprocessing image <path_to_myfile>/sub-train001_ses-0000_ncct.nii.gz :
> get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).
> 
> * deprecated from version: 3.0
> * Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
> resuming program execution
> 
> prediction  saved in: <path_to_myfile>/sub-train001_ses-0000_ncct-sr.nii.gz
> 
> If you use this tool in a publication, please cite:
> 
> Joint super-resolution and synthesis of 1 mm isotropic MP-RAGE volumes from clinical 
> MRI exams with scans of different orientation, resolution and contrast
> JE Iglesias, B Billot, Y Balbastre, A Tabari, J Conklin, RG Gonzalez, DC Alexander,
> P Golland, BL Edlow, B Fischl, for the ADNI
> NeuroImage, 118206 (2021)
> 
> SynthSR: a public AI tool to turn heterogeneous clinical brain scans into 
> high-resolution T1-weighted images for 3D morphometry
> JE Iglesias, B Billot, Y Balbastre, C Magdamo, S Arnold, S Das, B Edlow, D Alexander,
> P Golland, B Fischl
> Science Advances, 9(5), eadd3607 (2023)
> 
> If you use the low-field (Hyperfine) version, please cite also:
> 
> Quantitative Brain Morphometry of Portable Low-Field-Strength MRI Using 
> Super-Resolution Machine Learning
> JE Iglesias, R Schleicher, S Laguna, B Billot, P Schaefer, B McKaig, JN Goldstein, 
> KN Sheth, MS Rosen, WT Kimberly
> Radiology, 220522 (2022)
> 

And no prediction is saved in: <path_to_myfile>/sub-train001_ses-0000_ncct-sr.nii.gz as 

mri_synthstrip is working perfectly with the same images.

I'm running freesurfer on an Ubuntu 20.04.3 LTS server:
Architecture:                     x86_64
CPU op-mode(s):              32-bit, 64-bit
CPU(s):                              4
Model name:                      Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz

Let me know if I can contribute anyhow to solve this issue. Thank you in advance,
Joa

**Comment by joaco18** [comment]
Replacing  get_data() for get_fdata() in lines 727 and 729 of [mri_synthseg](https://github.com/freesurfer/freesurfer/blob/dev/mri_synthsr/mri_synthsr) should do the trick:
```
    if squeeze:
        volume = np.squeeze(x.get_fdata())
    else:
        volume = x.get_fdata()
```

**Comment by avnishks** [comment]
Fixed in the dev branch. ([@commit](https://github.com/freesurfer/freesurfer/commit/207ef907efb615ce1ed1637d637798b009c5942c))

Waiting for @jeiglesias' confirmation before I close this.
