### ISSUE TITLE
Add custom Matlab compiler runtime path option

### ISSUE THREAD

**Issue by mdefende** [freesurfer/freesurfer#1074]
Hi,

We run FreeSurfer on a cluster environment at our university, and version 7.3.2 is installed there, but it's policy not to edit software modules once they are working since that would potentially negatively impact all cluster users for that software. From what I can see, the checkMCR.sh script only checks for MCR to be installed in the $FREESURFER_HOME directory which we can't install MCR into or add a symlink to as per the policy. We have the required version of Matlab already installed, and users can also install the MCR into their personal spaces on the cluster, but there's not a way to use those versions with FreeSurfer as written. Is it possible add an option to set a custom MATLAB compiler runtime location when using some of FreeSurfer's submodules instead of only checking in FREESURFER_HOME? 

If I'm missing a way to do that already, I'd be happy to be corrected. If there's not a way to do it, we can create a custom container for our own use with FreeSurfer and MCR installed and use it that way, but that would need to be redone for each new version of FreeSurfer. Thanks

**Comment by buildqa** [comment]
Some system administrators setup the Matlab runtime environment after installing freesurfer, e.g., either R2014b, R2019b
$ sudo FREESURFER_HOME=$FREESURFER_HOME  fs_install_mcr  R2019b

**Comment by mdefende** [comment]
Thank you for the information!
