### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [freesurfer/freesurfer#1094]
freesurfer-dev/mri_convert/mri_convert.cpp line 539
code:
   else if (strcmp(argv[i], "-nc") == 0 ||
             strcmp(argv[i], "--nochange") == 0) // <--  identical 
    {
      nochange_flag = TRUE;
    }
    else if (strcmp(argv[i], "-so") == 0 ||
             strcmp(argv[i], "--store_orig_ras2vox") == 0)
    {
      store_orig_ras2vox_flag = TRUE;
    }
    else if (strcmp(argv[i], "-nc") == 0 ||
             strcmp(argv[i], "--nochange") == 0)  // <--  identical 
    {
      nochange_flag = TRUE;
    }

**Comment by yhuang43** [comment]
Thanks for catching that.
I removed it - https://github.com/freesurfer/freesurfer/commit/9f84c74e138ebf59bd7c15fe2031b92aa3b2832e
