### ISSUE TITLE
assignment to itself

### ISSUE THREAD

**Issue by maddin200** [freesurfer/freesurfer#1095]
freesurfer-dev/mri_glmfit/mri_glmfit.cpp line 1504
Code:
  mriglmtmp = (MRIGLM *) calloc(sizeof(MRIGLM),1);
    mriglmtmp->glm = GLMalloc();
    mriglmtmp->y = mriglm->y;
    mriglmtmp->w = mriglm->w;
    mriglmtmp->Xg = MatrixHorCat(mriglm->Xg,Xselfreg,NULL);
    for (n=0; n < mriglm->npvr; n++) mriglmtmp->pvr[n] = mriglmtmp->pvr[n]; // <-- assignment to same variable
    //MRIglmFree(&mriglm);
    mriglm = mriglmtmp;

**Comment by yhuang43** [comment]
Doug fixed this in commit https://github.com/freesurfer/freesurfer/commit/0ebe9793e1ff1a12b28737d8fb89b516b9db9435
