### ISSUE TITLE
No facemask output when running mideface

### ISSUE THREAD

**Issue by mnoergaard** [freesurfer/freesurfer#1107]
When trying to run mideface with the command:

mideface --i t1.nii.gz --o t1_defaced.nii.gz --facemask facemask.nii.gz 

I only get the ouput from the --o flag but not the output from the --facemask flag. The files are produced when running the command with the --odir flag. Looking at the log file, the facemask is created in the tmp directory, but it seems like it is never copied or created at the final destination?

I'd be happy to provide the log file if that is helpful.

**Comment by dngreve** [comment]
Fixed with most recent PR.

**Comment by mnoergaard** [comment]
Thanks, Doug!
