### ISSUE TITLE
GNU glibc 2.15 | bug report

### ISSUE THREAD

**Issue by chenyangjjj** [freesurfer/freesurfer#1111]
Dear freesurfer developers,

I am using freesurfer7.3.2 on HPC environment (linux, centos,x86_64).

When I am using the command "tksurfer bert rh pial". It gives teh below error(screenshoot) GNU libc version issue, I updated the license according to the error report. But It didn't change anything.

It also happended in other version freesurfers.

<img width="858" alt="image" src="https://github.com/freesurfer/freesurfer/assets/44012383/b64746bc-6c8f-46ee-9942-fafebbf77105">

**Comment by buildqa** [comment]
tksurfer is deprecated and no longer supported.   The alternative is to run freeview.  You could try tksurferfv which is a frontend for freeview that takes most of the original tksurfer options.

**Comment by chenyangjjj** [comment]
Thank you!
