### ISSUE TITLE
Deprecated arguments in pd.read_csv using qatools.py

### ISSUE THREAD

**Issue by RDoerfel** [freesurfer/freesurfer#1114]
Dear all,

I've been running into issues with the qatools.py application. More specifically, I get the following error:

```
  File "/usr/local/nru/freesurfer/fs74/python/packages/qatoolspython/createScreenshots.py", line 107, in createScreenshots
    lut = pd.read_csv(os.path.join(os.environ.get('FREESURFER_HOME'),'FreeSurferColorLUT.txt'),
TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'
```

After digging into the code, it seems this is the location:

[https://github.com/freesurfer/freesurfer/blob/2bf90f2007f33d4f6df4b1f7115f9a492e283dd3/qatools/qatoolspython/createScreenshots.py#L113](https://github.com/freesurfer/freesurfer/blob/2bf90f2007f33d4f6df4b1f7115f9a492e283dd3/qatools/qatoolspython/createScreenshots.py#L113)

And the reason for that is that the argument `error_bad_lines` is deprecated [deprecated and removed in ](https://stackoverflow.com/questions/69513799/pandas-read-csv-the-error-bad-lines-argument-has-been-deprecated-and-will-be-re) since pandas version 1.3.3 (currently on 2.01). 

Are there incentives to update the pandas version?

**Comment by avnishks** [comment]
Thanks for pointing it out. Fixed now with this [commit](https://github.com/freesurfer/freesurfer/commit/08f6fada01db6410ce8c42cca7fd2d54b1afa277).
