### ISSUE TITLE
out of bounds

### ISSUE THREAD

**Issue by maddin200** [freesurfer/freesurfer#1121]
attic/oct_train/oct_train.cpp line 576

Code:
#define NINPUTS 2
#define NTRAINING 10000
static int
train_xor(RBM_PARMS *parms) 
{
  RBM    *rbm ;
  MRI    *mri_inputs, *mri_labels ;
  int    x, val1, val2, n ;
  double r, visible[NINPUTS], rms ;
 ....
visible[2] = nint(visible[0]) ^ nint(visible[1]) ; // <-- probably out of bounds

**Comment by yhuang43** [comment]
The codes in the attic directory are not used.
