### ISSUE TITLE
Freeview ERROR: label name '3rd-Ventricle' is duplicated

### ISSUE THREAD

**Issue by kennyha85** [freesurfer/freesurfer#1125]
Hi all,

I have installed FreeSurfer v6.0.0 in MAC OS 12.6.7 but I got Freeview crashed due to PETSC error (which has been fixed in FreeSurfer v7.1.1)
For the consistency with my previous work, I do not want to install Freesurfer V7 in my MAC.

I updated freeview from this website: 
https://surfer.nmr.mgh.harvard.edu/fswiki/UpdateFreeview

freeview works for me but it still shows the following error:
` ERROR: label name '3rd-Ventricle' is duplicated!
ERROR: label name '3rd-Ventricle' is duplicated!
CTABfindDuplicateNames: 1 duplicate names found in:
  /private/var/folders/4w/c9v2n39j3hd_4rb1bmyrftqw0000gt/T/FreeSurferColorLUT.txt`

I cat the file and see that '3rd-Ventricle' has 2 lablels in the file.  I also see that the **_FreeSurferColorLUT.txt_** file is not identical to the FreeSurferColorLUT.txt in FreeSurfer home folder.

Can any one tell me the issue is serious or not? If so, how to fix this.
Thanks,

**Comment by buildqa** [comment]
If you downloaded a Mac build from https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev, then you are running a *development* build of Freesurfer 7.X which is likely going to be more unstable compared to the older 7.1.1 release build (which you stated you don't want to upgrade to).  You could check what is listed after you do "source $FREESURFER_HOME/SetUpFreesurfer.sh".  If you see something like,
-------- freesurfer-macOS-darwin_x86_64-dev-20230720-755802a --------
with
-dev-
... and a recent date that starts with 2023 ...
20230720
Those man you are running a Freesurfer 7.X development build.

You could also be running a 7.X development version of Freeview if you followed the link to download only freeview from,
https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/freeview,  with *dev* in the archive name, i.e., 
freesurfer-darwin-macOS-dev-freeview.tar.gz. 

There are differences in the color lookup table file, FreeSurferColorLUT.txt, between the 6.0.0 and 7.1.1. releases.  I would expect more differences if you were using that file from a recent 7.X development release.  I don't know the implications of using a different version of FreeSurferColorLUT.txt compared to what was included in the release.  I suggest you post your question to the Freesurfer help list if you plan to use a version of FreeSurferColorLUT.txt included that is not consistent with a clean install of 6.0.0, 7.1.1, or for that matter a development build.

BTW - We don't actively test or patch the FS 6.0.0 release on current versions of MacOS 12.X, 13.X, ...

**Comment by buildqa** [comment]
Please post to the freesurfer help list if this is till an issue, freesurfer@nmr.mgh.harvard.edu
