### ISSUE TITLE
Fedora RPM and/or Flatpak?

### ISSUE THREAD

**Issue by RastikC** [freesurfer/freesurfer#1126]
_Hi,_

would it, please, be possible to release **RPM packages** for **Fedora** and/or, eventually, **Flatpak** for **most distros**?

https://docs.flatpak.org/en/latest/
https://flatpak.org/setup/

_Thank you._

**Comment by buildqa** [comment]
We get requests to support different OS's/platforms and we will note your request.  But we can't promise support for a specific OS/platform in the future.   Given that Fedora is based upon Redhat, you could try installing the CentOS8 stream binary RPM installer for the 7.4.1 release (built with gcc8) https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-CentOS8-7.4.1-1.x86_64.rpm.  This table in the Fedora documentation seems to indicate that CentOS8 installer could be compatible with Fedora 28.  In any event, the yum/linux install tools will complain if something is not compatible during the install.

**Comment by buildqa** [comment]
... table URL, https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux/index.html

**Comment by RastikC** [comment]
@buildqa

**Thank you.** I tried to install (before asking here), but nothing to run (afterwards) - it doesn't appear on the installed SW list.

I understand that supporting many distros/OSs isn't an easy task - that's why I suggested **Flatpak**, which slowly is becoming the Linux standard and by many developers the only installation package provided.

https://en.wikipedia.org/wiki/Flatpak

**Comment by buildqa** [comment]
The download and install as admin or root on a Fedora machine is very simple and only requires a couple of commands in the terminal window.  Below is the output from installing the CentOS8 stream Freesurfer package listed above on a Fedora Core 32 image (which succeeds).

[root@fc32]# cat /etc/os-release
NAME=Fedora
VERSION="32"
ID=fedora
<rest of output deleted>

[root@fc32]#  wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-CentOS8-7.4.1-1.x86_64.rpm
<rest of output deleted>

[root@fc32]# yum install ./freesurfer-CentOS8-7.4.1-1.x86_64.rpm 
... answer yes to all questions ...
<rest of output deleted>

[root@fc32]# ls /usr/local/freesurfer
7.4.1-1
[root@fc32]# ls /usr/local/freesurfer/7.4.1-1/
<rest of output deleted>

**Comment by RastikC** [comment]
_Hi, @buildqa,_

**thanks** for the assistance and help.

Well, it now seems to be installed (just like before, as I realized), but it is unclear to me, **how to run** and **open a study**. Why can't **FreeSurfer** integrate into the **OS's GUI** (e.g. GNOME), just like **Aliza** (https://www.aliza-dicom-viewer.com)?

_Thanks. **Best!**_

**Comment by buildqa** [comment]
Good to hear the install worked.   You could post any further questions about how to use freesurfer to the help list, freesurfer@nmr.mgh.harvard.edu.  I"m not sure there's any advantage for the image viewing application, freeview, to be integrated into a specific dekstop environment in linux or MacOS compared to running as an open source application using common graphics libraries across those platforms.

**Comment by RastikC** [comment]
@buildqa 

**Thanks.** Just simply: **How to run?**

**Comment by RastikC** [comment]
@buildqa 

**Thanks.** Just simply: **How to run?**

**Comment by buildqa** [comment]
The freesurfer wiki, https://surfer.nmr.mgh.harvard.edu/fswiki, has various pages covering freesurfer.

Some people recommend the online "Andy's Brain Book", https://andysbrainbook.readthedocs.io/en/latest, which covers various software tools including freesurfer.  The chapter on freesurfer there is, https://andysbrainbook.readthedocs.io/en/latest/FreeSurfer/FreeSurfer_Introduction.html?highlight=freesurfer

Below are the basics to setup the shell environment in a terminal window running bash (using the CentOS8 stream installer on my fc30 image).  Some people add those export and source commands in their shell initialization file and/or just create a script for them.

$ bash

$ ls -ltd /usr/local/freesurfer/7.4.1-1
drwxr-xr-x. 20 root root 4096 Aug  6 23:16 /usr/local/freesurfer/7.4.1-1

$ export FREESURFER_HOME=/usr/local/freesurfer/7.4.1-1

$ source $FREESURFER_HOME/SetUpFreeSurfer.sh

-------- freesurfer-linux-centos8_x86_64-7.4.1-20230613-7eb8460 --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer/7.4.1-1
FSFAST_HOME       /usr/local/freesurfer/7.4.1-1/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/7.4.1-1/subjects
MNI_DIR           /usr/local/freesurfer/7.4.1-1/mni

... you might also see the output the 1st time the above is run ...
INFO: /home/<your userid>/matlab/startup.m does not exist ... creating

... test running the image viewing program freeview ...

$ which freeview
/usr/local/freesurfer/7.4.1-1/bin/freeview

... check freeview brings up an empty window when run with no arguments ...
$ freeview

... quit and tru viewing one of the provided test subject volumes ...
$ freeview $SUBJECTS_DIR/bert/mri/brain.mgz

... if that works, then you could try viewing one of your own surfaces or volumes ...

Keep in mind that if you want to process your own subjects, you should set SUBJECTS_DIR to some other path, e.g., 

$ mkdir -p $HOME/subjects
$ export SUBJECTS_DIR=$HOME/subjects

- as you can read from but not write to the subjects dir in the installed freesurfer distribution.  Or you need to be able to read/write data to SUBJECTS_DIR when processing your own subjects, e.g., with the recon-all script.

**Comment by RastikC** [comment]
**Thank you.** I'll take a look and give your recommendation a try. **Best!**

**Comment by RastikC** [comment]
_Hi again, @buildqa!_

I'm trying to use OBS (https://openbuildservice.org => https://build.opensuse.org) to build an RPM. I've downloaded  a 237 MB ZIP from your repository (https://github.com/freesurfer/freesurfer), but it wouldn't unpack - due to some non-specified error.

Would anybody from your team be willing to build binaries (using the OBS) and publish them? You'd have a lot of Linux distros covered at once.

_Thank you._

![obrázok](https://github.com/freesurfer/freesurfer/assets/141367429/034fd18d-4460-417f-9fac-669a5fd20cde)
