### ISSUE TITLE
How to hange atlas provided in FreeSurfer?

### ISSUE THREAD

**Issue by AXu0511** [freesurfer/freesurfer#1128]
Hello! I currently have a Nifit-format atlas segmentation map, where labels such as the corpus callosum are labeled as 40, and white matter is labeled as 50, and so on. I also have the corresponding brain image for this segmentation map. How can I use FreeSurfer to achieve segmentation results that match my segmentation map? Alternatively, how can I replace the template in FreeSurfer with my custom segmentation map to achieve my desired segmentation?
Looking forward to your reply soon!

**Comment by avnishks** [comment]
Hi,
Please send your question to the Freesurfer mailing list (freesurfer@nmr.mgh.harvard.edu). It'll get resolved much faster there.
