### ISSUE TITLE
Screen tearing in FreeView on Ubuntu 22.04

### ISSUE THREAD

**Issue by vnckppl** [freesurfer/freesurfer#1129]
**Issue**
1) In FreeView, when I use the mouse to navigate, the crosshair is not under the cursor, but about an inch left and down from it.
2) When I resize the freeview window, it starts to tear. See the attached screenshot:
![freeview_screen_tearing](https://github.com/freesurfer/freesurfer/assets/15114746/033513d0-3922-4a07-95fe-ff30357b5085)

**Environment**
OS: Ubuntu 22.04.3 LTS (_but this happened with 20.04 as well_)
FreeSurfer: freesurfer-linux-ubuntu22_x86_64-7.4.1-20230614-7eb8460
FreeView: 3.0; Build Jun 14 2023 03:48:54 (_but this happened with previous versions as well_)

**Comment by avnishks** [comment]
Hi,
Please send your question to the Freesurfer mailing list ([freesurfer@nmr.mgh.harvard.edu](mailto:freesurfer@nmr.mgh.harvard.edu)). It'll get resolved much faster there.
