### ISSUE TITLE
va_end missing

### ISSUE THREAD

**Issue by maddin200** [freesurfer/freesurfer#1130]
packages/nrrdio/simple.c line 507

Code:
int
_nrrdContentSet_va(Nrrd *nout, const char *func,
                   char *content, const char *format, ...)
{
  char me[]="_nrrdContentSet_va", err[BIFF_STRLEN];
  va_list ap;

  va_start(ap, format);
  if (_nrrdContentSet_nva(nout, func, content, format, ap))
  {
    sprintf(err, "%s:", me);
    biffAdd(NRRD, err);
    free(content); // <-- no va_end
    return 1;
  }
  va_end(ap);

  /* free(content);  */
  return 0;
}

**Comment by buildqa** [comment]
Closing as dev may/may not change the code at their discretion.
