### ISSUE TITLE
missing libraries Freeview using docker/singularity image

### ISSUE THREAD

**Issue by enijhuis** [freesurfer/freesurfer#1132]
Hi there developers,

When using freeview with singularity from the docker image 7.4.1. not all necessary libraries are included. The following error message can be returned:

**freeview: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory**

Maybe the following stackoverflow threat can serve as a help to fix the issue in the docker file:

https://stackoverflow.com/questions/63889102/unable-to-run-docker-image-due-to-libgl-error

NB. a workaround is to install the freeview dockerfile from hub.docker.com/r/cyuwei/freeview however this is rather cumbersome.

Best regards

---- Please read before posting ----

We reserve the GitHub "Issues" page specifically for tracking known software bugs. If you want to report a runtime issue or have a FreeSurfer processing question, please post to the FreeSurfer mailing list instead. Instructions for posting to the mailing list or searching the list archives are available on the support wiki page:

https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport

NOTE: Issues that do not match the above will be closed and we will refer you to the mailing list. Thank you.

---- Remove this text before posting ----

**Comment by pwighton** [comment]
Hi @enijhuis, the FreeSurfer containers were not intended to run GUI applications.

To run neuroimaging GUI applications in a container, I'd suggest taking a look at www.neurodesk.org.  They do a fantastic job managing those complexities.

However that is good to know someone has managed to containerize FreeView.  Do you happen to know where I can find the dockerfile for hub.docker.com/r/cyuwei/freeview?

**Comment by buildqa** [comment]
Closing this.
