### ISSUE TITLE
Skip VTK8 and update to VTK9

### ISSUE THREAD

**Issue by phcerdan** [freesurfer/freesurfer#1135]
Hi @yhuang43, I see that you are updating the code to be compatible with ITK5, that's great!

I wonder though, the title on the commits suggest that you are updating to ITK5/VTK8. ITK5 is the latest major version of ITK, but the latest major version of VTK is 9. Why update to 8, when we could update to 9?

Thanks!

PS: I might be able to help migrating to modern CMake.

**Comment by buildqa** [comment]
Older versions of OS's we support don't support newer versions of ITK/VTK/QT.  Those newer versions are consistent with running on CentOS9 I believe.

**Comment by buildqa** [comment]
Closing this.
