### ISSUE TITLE
SetInput in has been renamed to SetInputData in vtkImageAlgorithm.h since VTK v.6.0.0

### ISSUE THREAD

**Issue by aboualiaa** [freesurfer/freesurfer#1149]
SetInput is still used in this file, which causes a compilation error.

https://github.com/freesurfer/freesurfer/blob/c385e43e3b250ec6c7fcdd6862f90c9dd0587bd4/freeview/VolumeFilterThreshold.cpp#L42

here is the commit from vtk:
https://github.com/Kitware/VTK/commit/4ea36770118ff350051d9d5eaf53c3a8de78a77d

the fix is a very simple rename, unless support for VTK v5 is necessary, but the packages which are officially distributed contain VTK v7, so I think it's safe to say that VTK v5 is not supported and should just be dropped from the code

**Comment by buildqa** [comment]
I don't believe we can drop vtk5 support at this time.

**Comment by aboualiaa** [comment]
close as won't fix

**Comment by aboualiaa** [comment]
thank you. will close as won't fix.
