### ISSUE TITLE
License error occurs when using docker 

### ISSUE THREAD

**Issue by oikosohn** [freesurfer/freesurfer#1164]
Hello FreeSurfer team.

I saw the below command on the  [Overview of the FreeSurfer Docker Image](https://hub.docker.com/r/freesurfer/freesurfer) . And executed it, but there was an error that I didn't have a license.

```
FROM freesurfer/freesurfer:7.1.1
COPY license /usr/local/freesurfer/.license
```

The error occurred because there were no environment variables for the license file. I think users who use the FreeSurfer for the first time may be confused.

It seems that commands should be changed to the [Overview of the FreeSurfer Docker Image](https://hub.docker.com/r/freesurfer/freesurfer) as below.

```
FROM freesurfer/freesurfer:7.1.1
COPY license /usr/local/freesurfer/.license
ENV FS_LICENSE /usr/local/freesurfer/.license/license.txt
```

Alternatively, it would be good to add the environment variable FS_LICENCE to the docker file. So I made a PR(#1165).

**Comment by buildqa** [comment]
We don't provide license.txt or .license  files as part of any freesurfer distribution.   We expect end users to receive and download their own license.txt file after completing the online registration form.  Then subsequently set FS_LICENSE to wherever they decide to download and/or move license.txt to.   Many users opt for their $HOME directory or some location not under the freesurfer tree which does not require root privs to access.

**Comment by oikosohn** [comment]
Thank you for your response.

I believe it's necessary to include a single line of example Dockerfile code.

![image](https://github.com/freesurfer/freesurfer/assets/59533593/58905c6e-5be0-42bc-83d3-b0cb1313f497)

The highlighted code assumes that the license file is located within the `license` folder. Therefore, it copies the `license` folder to `/usr/local/freesurfer/.license`.

In this scenario, adding `ENV FS_LICENSE /usr/local/freesurfer/.license/license.txt` to the example Dockerfile code would be appropriate.

I also believe it would be helpful for newcomers to Docker and Freesurfer, providing them with guidance.

**Comment by buildqa** [comment]
OK, I've update the comments in the Dockerfile to point out the above.
