### ISSUE TITLE
No space between StructName and NumVert

### ISSUE THREAD

**Issue by ToeKneeFan** [freesurfer/freesurfer#1166]
In rare cases, mris_anatomical_stats will generate output where the StructName and the NumVert columns run together (there is no whitespace in between). For example,

> lh.InsertSomeStructNameInsideOfHereThatIsLong.label12345 ...

This seems to be due to the fact that a space is not inserted before the NumVert values (`fprintf(fp, "%5d", dofs[i])`), even though there is whitespace before the other numerical columns (e.g., `fprintf(fp, "  %5.0f", areas[i])`) ([1](https://github.com/freesurfer/freesurfer/blob/f5c40306487e4170a84be1924652f88aa9d26d70/mris_anatomical_stats/mris_anatomical_stats.cpp#L940-L950)). If the StructName is at least 40 characters and NumVert is at least 5 characters, they end up running together. It seems some users explicitly write workarounds to address the parsing (for example, [here](https://github.com/AnnaFurtjes/Comparing_atlases/blob/78ad3790e28ccdf8574b07022c894a988b276435/Serious_Pipeline.html#L1068-L1077)).

Should whitespace be inserted to address this (`"  %5d"` instead of `"%5d"`)?

**Comment by yhuang43** [comment]
It is fixed (commit https://github.com/freesurfer/freesurfer/commit/1ba420df19e2820585dcdd68d3ee26e48025d7e0).

**Comment by ToeKneeFan** [comment]
Thank you very much for your help! 🙏
