### ISSUE TITLE
BUG: 7.4.1: recon-all-clinical.sh

### ISSUE THREAD

**Issue by toomanycats** [freesurfer/freesurfer#1167]
The entry point script `recon-all-clinical.sh` has a few hard coded paths what do not follow the convention of 
`$FREESURFER_HOME/average/foobar.txt`

See line 563 of `recon-all-clinish.sh` as an example. This occurs in a few places.

    set cmd="mris_label2annot --s $SNAME --ctab /usr/local/freesurfer/dev/average/colortable_vpnl.txt --hemi lh --a mpm.vpnl --maxstatwinner --noverb    ose --l lh.FG1.mpm.vpnl.label --l lh.FG2.mpm.vpnl.label --l lh.FG3.mpm.vpnl.label --l lh.FG4.mpm.vpnl.label --l lh.hOc1.mpm.vpnl.label --l lh.hOc    2.mpm.vpnl.label --l lh.hOc3v.mpm.vpnl.label --l lh.hOc4v.mpm.vpnl.label"

**Comment by yhuang43** [comment]
It has been addressed in commit ecdf46e
