### ISSUE TITLE
Non-clickable dialogs in freeview on WSL

### ISSUE THREAD

**Issue by piotrdzwiniel** [freesurfer/freesurfer#1172]
Dialog boxes that appear when using freeview on WSL2 with Ubuntu 22.04.2 LTS are non-interactive - you can't move them, disable them or use the buttons. This includes the window for defining ROI, Command Console, Floating Panels, and others. On the other hand, dialogs that have built-in Ok and Cancel options, such as Load Volume, work.

A preview of one of the situations below. A non-interactive (non-clickable) window is circled red.

![roi](https://github.com/freesurfer/freesurfer/assets/7367330/4df001fd-5082-4bbf-bfc4-98f43574ac1a)

**Comment by buildqa** [comment]
We cannot guarantee WSL together with the X windows server running under Windows - will enable the Freeview GUI to work as it does in a true Linux desktop environment.   As an alternative, you could try creating and running an Ubuntu 22 VM using some author virtualization application, e.g., this describes how to setup and run Ubuntu 22 in Virtualbox, https://freesurfer.net/fswiki/VM_67

**Comment by buildqa** [comment]
Closing.
