### ISSUE TITLE
Edit annotation labels not working

### ISSUE THREAD

**Issue by eric2302** [freesurfer/freesurfer#1173]
Hi!

When using Freeview, I am not able to click the Edit Annotation window (see GIF). Any other window works, just not this one.
![screen](https://github.com/freesurfer/freesurfer/assets/52158179/c282bdd0-c89d-479b-9fff-2fd42ed090b2)

For context, I am using Freesurfer 7.4.1 on a WSL with Ubuntu 22.04. In order to use the Freeview GUI, I use Xlaunch with default settings.

Best,
Eric

**Comment by buildqa** [comment]
We cannot guarantee WSL together with the X windows server running under Windows - will enable the Freeview GUI to work as it does in a true Linux desktop environment. As an alternative, you could try creating and running an Ubuntu 22 VM using a different virtualization application, e.g., this describes how to setup and run Ubuntu 22 in Virtualbox, https://freesurfer.net/fswiki/VM_67

**Comment by buildqa** [comment]
Closing.
