### ISSUE TITLE
nf: mri_synthmorph compatibility with multiple moving images

### ISSUE THREAD

**Issue by mccle** [freesurfer/freesurfer#1176]
Recently, I have been implementing `mri_synthmorph`'s registration as a step within a larger preprocessing pipeline. I am very pleased with the quality of its outputs, but have found myself wanting to transform multiple moving images within a single command call and do not believe there is a current method for doing so. Specifically, I would like to be able to derive the transform from the primary moving image and immediately apply that transform to other images that share the same space. I think this would be particularly useful for registering images derived from the moving image, such as transforming segmentation masks or transforming different b-values and ADC maps while using a DWI as the primary moving image.

I have already experimented with making a couple of changes to [mri_synthmorph/mri_synthmorph](https://github.com/freesurfer/freesurfer/blob/dev/mri_synthmorph/mri_synthmorph) and achieved my desired behavior. First, I added the `interp_method` argument to the `transform` function to allow for transformation of segmentation masks. Since `transform` calls `vxm.utils.transform` where this is already implemented, this change is very simple. For the application of the derived transform to the other moving images, I have inserted the following code at what is currently L640:

```python
for accompanying_image in accompanying_images:
        moving = accompanying_image["moving"]
        out_moving = accompanying_image["out_moving"]
        interp_method = accompanying_image.get("interp_method", "linear")
        mov = sf.load_volume(moving)

        if arg.header_only:
            out = mov.copy()
            out.geom.update(vox2world=ras_2 @ mov.geom.vox2world)
        else:
            out = transform(
                mov, interp_method=interp_method, trans=vox_1, shape=fix.shape
            )
            out = fix.new(out)
        out.save(out_moving)
```
In this context, `accompanying_image` is a sequence of dictionaries that contain the keys "moving" and "out_moving" (and optionally "interp_method", which defaults to "linear" if not specified). The reason I had formatted it this way, was that I believe it may be simplest to pass this option through the CLI using a JSON file so that only one option would have to be added. This is certainly not the only way to encode this information, so I am open to all feedback about how to make this easier for `mri_synthmorph` users. One alternative I have already explored is utilizing `argparse`'s support for passing lists to its options (or lists could be obtained by splitting with a predetermined delimiter). In this way, similar behavior could be obtained purely through the CLI with 3 options indicating a list of paths to the additional moving images, the output paths to the moved images, and the interpolation methods that should be used for each.

Overall, I think this would be a useful addition that would be relatively easy to implement. However, since the CLI would require the addition of 1 or more completely new options, I would like to receive some feedback on the best way to integrate these changes with the existing code. If you have any suggestions on how to better achieve this desired behavior, please let me know.

**Comment by mu40** [comment]
Thanks for using SynthMorph, we are glad that you find it useful! Since among other things, you suggest passing a JSON file, your primary concern is likely not typing out a quick command by hand that applies a transform to a set of images. If you find applying warp fields to other images cumbersome because of the slow conversion to M3Z indicated in the help text, we just added [support for the new MGZ-warp format](https://github.com/freesurfer/surfa/blob/master/surfa/transform/warp.py) to surfa. SynthMorph will switch to this format in the next few weeks, after which you will be able to directly apply SynthMorph warps:

```shell
mri_convert -rt nearest -at warp.mgz moving.mgz out.nii.gz
```

 Alternatively, you will be able to use surfa in Python:

```python
sf.Warp.load('warp.mgz').transform(moving, method='nearest').save('out.nii.gz')
```

I am not sure if the `mri_synthmorph` script is the right place for the suggestion. We intended the `-o` and `-O` flags mostly for validation and already have other tools for applying transforms with fine-grained control. If we added the feature, we would likely also want options for lists of fixed images to resample, and corresponding lists of moving and fixed output file names, resampling types, and the intended output data types for completeness, all of which adds up.

If your pipeline includes FreeSurfer tools or is written in Python, would the format switch resolve your issue? To test the new warp format with `mri_convert` or surfa, you can convert the current SynthMorph warps to it:

```shell
mri_warp_convert -g moving.mgz --inras warp.nii.gz --outmgzwarp warp.mgz
```

**Comment by CPBridge** [comment]
Thanks @mu40 ! I think being able to straightforwardly apply the transform in surfa would be good. We got a bit lost in the transform conversion process and decided that in the current state it would be simpler to hack the synthmorph script like this than try and figure it out.

Applying to further images directly within the synthmorph command may be a useful feature. If so, @mccle made this work quite nicely and we would happily contribute it. But I also get the separation of concerns between calculating and applying the transform. Happy to follow your lead on whether/how this would be added to the script.

**Comment by mccle** [comment]
Thank you for your prompt and thorough response, @mu40. You are correct in that my use case is less concerned with manually typing out a command and has led me to a solution that may not be very CLI friendly. 

My script is actually written in python and was originally calling out to all of the commands you mentioned using `subprocess.run`. It essentially included these steps for obtaining the transform:
```bash
mri_synthmorph -m joint -t transform.mgz moving.nii.gz fixed.nii.gz

mri_warp_convert -g moving.nii.gz --inras transform.mgz --outm3z transform.m3z
```
followed by the transformation of all of the images I identified as "accompanying images" in my earlier message:

```bash
mri_convert -at transform.m3z -rt {interp_method} {accompanying_image} moved_{accompanying_image}
```

As an aside, for using `-m affine`, I was running into some issues converting to `lta` format so that I could support affine transformations as well. An older help string had suggested that I could convert an affine transform `transform.txt` from `mri_synthmorph` like this (though I see that it has since changed in more recent commits): 
```bash
lta_convert --src moving.nii.gz --target.fix.nii.gz --inras transform.txt --outlta transform.lta
```
but this did not work due to the lack of the  `--inras` flag.

Due to my difficulties with applying the affine transform and the increased time consumption introduced by converting to different formats, I found that accessing Synthmorph through voxelmorph directly was much more efficient (at least for my use case). It allowed me to utilize `vox_1` as soon as it was obtained and to apply it quickly without the need for any conversion. From your recommendations, it sounds like `surfa` may be a good alternative though, so I'll definitely explore that as well.

As to your other comment that `mri_synthmorph` may not be the best place to address this, do you think that there is a better place where this belongs? I maintain that it would be useful to be able to apply the transforms directly as written and also potentially to multiple files at the same time, but I agree that this is not `mri_synthmorph`'s primary focus so it may not fit here. Do you think this would be more compatible feature with something else in freesurfer or that it would potentially be a worthwhile new addition?

**Comment by mu40** [comment]
I agree that we need a way to directly apply SynthMorph transforms to other images. We recently transitioned the rigid and affine format to LTA, eliminating the need for conversion. You can now directly apply these transforms with `mri_convert -at`, and the switch to MGZ warps will soon extend this capability to warps, too.

My apologies for incorrectly referencing the non-existent `--inras` flag in the help section on converting matrix transforms. The correct flag should have been `--inniftyreg`. PR #1142 addressed this issue by adding the missing flags in November.

I recognize that applying transforms without FreeSurfer binaries as well as several transforms in one shot may be a desirable feature. PR #1180 will add the functionality you suggest as a new script once surfa finalizes the handling of warps.

**Comment by mccle** [comment]
Thank you for your help, @mu40. Your draft looks like it will make applying the transforms much easier once implemented and I'm sure it will be a welcome addition for many users. I'll keep my eye on PR #1180 and will certainly be trying it in my pipeline once it is ready.
