### ISSUE TITLE
Feature request: Synthstrip - CPU thread control

### ISSUE THREAD

**Issue by jrdalenberg** [freesurfer/freesurfer#1182]
Hey all, 

I am super happy with the performance of Synthstrip and busy with integrating it in my nipype pipelines for (f)MRI and PET preprocessing. 

I was wondering if it is possible to add an input parameter for CPU thread control. I am happy to write a PR myself if you prefer. 

I assume it can be done with `torch.set_num_threads(int)` here: https://github.com/freesurfer/freesurfer/blob/1feb6a6862bffff3a70152b008ccab3bee1dc869/mri_synthstrip/mri_synthstrip#L56

But I have not tested it yet :)

-Jelle

**Comment by mu40** [comment]
Thanks Jelle, sounds like a useful feature.

**Comment by jrdalenberg** [comment]
Awesome, thanks!
