### ISSUE TITLE
BUG: recon-all-clinical.sh

### ISSUE THREAD

**Issue by toomanycats** [freesurfer/freesurfer#1185]
FS version 7.4.1

I've found a minor bug in `recon-all-clinic.sh` line 515

    ln -s $FREESURFER_HOME/subjects/fsaverage $SUBJECTS_DIR/

I believe there should be a test for the existence of the symbolic link first. When I run the clinical pipeline
on more than a single subject I get a shell error that the link could be created b/c it already exists.

I've implemented a simple fix:

    if ( ! -l $SUBJECTS_DIR/fsaverage ) then
      ln -s $FREESURFER_HOME/subjects/fsaverage $SUBJECTS_DIR/
    endif

**Comment by yhuang43** [comment]
Thanks for bringing this to our attention.
