### ISSUE TITLE
DWI direction setting of MRI equipment

### ISSUE THREAD

**Issue by zhangjingcode** [freesurfer/freesurfer#1194]
Thanks to the freesurfer team for their efforts to promote the development of brain function research! We collected DWI data from a new generation of 3T MRI scanner developed by our company, however, there are someting wrong in freesurfer process, probably because different direction setting or saving in Dicom tag from Siemens or GE.  How should we set direction parameters or other Dcm tags to ensure freesurfer normal operation?

**Comment by yhuang43** [comment]
Can you be more specific of the problem? Also, the version of Freesurfer you are running.

**Comment by yhuang43** [comment]
Just realized the issue is more related to DICOM standard. Check this web site - https://www.dicomstandard.org/current/. Maybe, Siemens or GE manuals.
