### ISSUE TITLE
mris_preproc

### ISSUE THREAD

**Issue by woainiqdu** [freesurfer/freesurfer#1196]
Hello, when I use mris_preproc, I will get ERROR: no subjects specified,I have tried many methods but the results are still not very good. Could someone give me some advice? thank you .

**Comment by woainiqdu** [comment]
The following is my FSGD

GroupDescriptorFile 1

Title lh_thickness						

Class young 			

Class old 			

Variables gender age			

Input	BN1	young	2	22

Input	BN2	young	2	24

Input	BN3	young	2	22

Input	BN4	young	1	22

**Comment by dngreve** [comment]
Please post this to the freesurfer list ***@***.*** 
Also include the full command line and all the terminal output.

On 4/2/2024 10:04 AM, woainiqdu wrote:
>
>         External Email - Use Caution
>
> Hello, when I use mris_preproc, I will get ERROR: no subjects 
> specified,I have tried many methods but the results are still not very 
> good. Could someone give me some advice? thank you .
>
> —
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/10zQAFeOLhwjR24BeEHQhE-MBPCmckCn0TCke-fvaoyUlKyh6dPZEr-TBNN3OtfXkIThTv5F4eYf5nX7lxPPBc6iMkEkr6Nf7Vuc3wsu-G1CAf1H4pDa5LiiH4uYQ7FvMhJD08Y145u1JILn47qdkXyJDAp43PS3wloUGYVDFNHAH090XIA296u58ACI647nB6DUztZ7Dy_v81Wh0TtYLxB9FfYGoCnU3EKCEDx7JpFqZMqugwYOdcfRgMHZPA9iUgEhhrO4szkhFEaHA71EF0h3q6yup1-GSz8gHI9O9ynAkQn6iVuCV9JJo4p8wkKOM/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1196>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1GpTNn3mMqE8nZIHCoCv6Evwkot1biRTS1iGdZOkO9szsao_GzXpCX8KWcYu9GVeDF_ET1kHqLOszpfFb3wWzpMkA65UUnle5zK3m5JV2glAx3y96c0xyUV4xzIwgcJJMORfEBHMmmKbFvBe-zRI1aLK2_SGCx5CueT8LI0b-gfwmdKtBZfAFATVVm8rsILidZUWfxI8fq3JRbQQbEextLz05NOk24CcMkfa7j8lflJdvKg57yhvNdCB6-_B9sOPFC3VL4CIx9eeZuM4XuceVLJEfba7cS7UbfHuEUhUt73DXPolOh8xXd07J1-6OLwmO/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VQBALQ7GMX3GQZ7YBTY3K3FDAVCNFSM6AAAAABFTOXOGSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGIZDANRRG4YDANY>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>
>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by woainiqdu** [comment]
This is my script file.

#!/bin/tcsh

 setenv study $argv[1]

 foreach hemi (lh rh)
 foreach smoothing (10)
 foreach meas (volume thickness)
 mris_preproc --fsgd FSGD/{$study}.fsgd \
 --target fsaverage \
 --cache-in {$meas}.fwhm{$smoothing}.fsaverage \
 --hemi {$hemi} \
 --out {$hemi}.{$meas}.{$study}.{$smoothing}.mgh
 end
 end
end


But it will output.ERROR: no subjects specified
ERROR: no subjects specified
ERROR: no subjects specified
ERROR: no subjects specified

This is my FSGD.

GroupDescriptorFile 1

Title lh_thickness

 Class young

 Class old

 Variables gender age

 Input BN1 young 2 22

Input BN2 young 2 24

Input BN3 young 2 22

发件人：Douglas Greve ***@***.***>
发送日期：2024-04-02 22:19:42
收件人：freesurfer/freesurfer ***@***.***>
抄送人：woainiqdu ***@***.***>,Author ***@***.***>
主题：Re: [freesurfer/freesurfer] mris_preproc (Issue #1196)

Please post this to the freesurfer list ***@***.***
 Also include the full command line and all the terminal output.

 On 4/2/2024 10:04 AM, woainiqdu wrote:
 >
 >         External Email - Use Caution
 >
 > Hello, when I use mris_preproc, I will get ERROR: no subjects
 > specified,I have tried many methods but the results are still not very
 > good. Could someone give me some advice? thank you .
 >
 > —
 > Reply to this email directly, view it on GitHub
 > <https://secure-web.cisco.com/10zQAFeOLhwjR24BeEHQhE-MBPCmckCn0TCke-fvaoyUlKyh6dPZEr-TBNN3OtfXkIThTv5F4eYf5nX7lxPPBc6iMkEkr6Nf7Vuc3wsu-G1CAf1H4pDa5LiiH4uYQ7FvMhJD08Y145u1JILn47qdkXyJDAp43PS3wloUGYVDFNHAH090XIA296u58ACI647nB6DUztZ7Dy_v81Wh0TtYLxB9FfYGoCnU3EKCEDx7JpFqZMqugwYOdcfRgMHZPA9iUgEhhrO4szkhFEaHA71EF0h3q6yup1-GSz8gHI9O9ynAkQn6iVuCV9JJo4p8wkKOM/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1196>,
 > or unsubscribe
 > <https://secure-web.cisco.com/1GpTNn3mMqE8nZIHCoCv6Evwkot1biRTS1iGdZOkO9szsao_GzXpCX8KWcYu9GVeDF_ET1kHqLOszpfFb3wWzpMkA65UUnle5zK3m5JV2glAx3y96c0xyUV4xzIwgcJJMORfEBHMmmKbFvBe-zRI1aLK2_SGCx5CueT8LI0b-gfwmdKtBZfAFATVVm8rsILidZUWfxI8fq3JRbQQbEextLz05NOk24CcMkfa7j8lflJdvKg57yhvNdCB6-_B9sOPFC3VL4CIx9eeZuM4XuceVLJEfba7cS7UbfHuEUhUt73DXPolOh8xXd07J1-6OLwmO/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VQBALQ7GMX3GQZ7YBTY3K3FDAVCNFSM6AAAAABFTOXOGSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGIZDANRRG4YDANY>.
 > You are receiving this because you are subscribed to this
 > thread.Message ID: ***@***.***>
 >
 The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
 Please note that this e-mail is not secure (encrypted). If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately. Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.
