### ISSUE TITLE
OpenMP thread synchronization bottleneck

### ISSUE THREAD

**Issue by mathdugre** [freesurfer/freesurfer#1199]
# Environment details
Docker image: `mathdugre/freesurfer:debug-info` also available at https://github.com/mathdugre/mri-bottleneck/blob/main/container/freesurfer.Dockerfile

Multi-threading was set using:
* `-threads` argument
* `OMP_NUM_THREADS` env var
* `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` env var

All set to the same value.

# Issue
Profiling the `recon-all` pipeline, we found that when using multi-threading a majority of the time was spent waiting for OpenMP threads to synchronize. The two figure below show the CPU time spent in each function when using 1 and 32 threads respectively.
Note the difference on the y-scale as well.
![hotspots-1threads-freesurfer-reconall-simple](https://github.com/freesurfer/freesurfer/assets/16450132/4d8ec483-95d2-4eb9-9890-12123e6a0f21)
![hotspots-32threads-freesurfer-reconall-simple](https://github.com/freesurfer/freesurfer/assets/16450132/2c0da3eb-683e-442e-a770-c5f6b8b7be9a)

We found similar results when using lower number of threads. Furthermore, the parallel efficiency decrease significantly when increasing the number of threads.
![makespan-freesurfer](https://github.com/freesurfer/freesurfer/assets/16450132/8f1d4aeb-ba5d-458f-87f5-a4d3f6c3a60f)

# Potential Solution
We think this issue might arise from the OpenMP scheduling policy used; mostly _static_ policy is used. We think that using _dynamic_ policy might reduce the impact from threads synchronization. However, we couldn't test this hypothesis since naively replacing the OpenMP scheduling type failed to compile.

**Comment by buildqa** [comment]
We can't promise anything w.r.t changing how OpenMP is used.  We are still using itk4 on some platforms, and it looks like there are some limitations with itk, https://itk.org/pipermail/insight-users/2013-October/048898.html

**Comment by buildqa** [comment]
As we migrate to newer versions of linux OS's, we will need to use newer versions of ITK which should improve performance.  i do not have a schedule for that however.
