### ISSUE TITLE
Hippocampus data missing after segmentation

### ISSUE THREAD

**Issue by Dai0-2** [freesurfer/freesurfer#1200]
Why is it that after I do the hippocampal subpartition segmentation in Freesurfer 6.0, the size of the hippocampus I get pieced together from the 22 subpartitions seems to be missing a portion of the hippocampus compared to the entire hippocampus data in lh.hippoSfLabels-T1.v10.mgz and rh.hippoSfLabels-T1.v10.mgz

<img width="168" alt="16d152566b334dd5e30d5770a32c8ab" src="https://github.com/freesurfer/freesurfer/assets/139936376/e47f0dda-3451-43f2-935d-99ab17b6f1f4">
<img width="164" alt="792b37782fed13675d2cb3b89f45b0a" src="https://github.com/freesurfer/freesurfer/assets/139936376/2c17151d-0e7c-4d17-8c62-893c6e47f853">

**Comment by buildqa** [comment]
Please re-post this on the freesurfer help list (if you have not done so already).
