### ISSUE TITLE
are the synthstrip model weights for pediatric images available?

### ISSUE THREAD

**Issue by nimzodisaster** [freesurfer/freesurfer#1204]
---- Please read before posting ----

We reserve the GitHub "Issues" page specifically for tracking known software bugs. If you want to report a runtime issue or have a FreeSurfer processing question, please post to the FreeSurfer mailing list instead. Instructions for posting to the mailing list or searching the list archives are available on the support wiki page:

https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport

NOTE: Issues that do not match the above will be closed and we will refer you to the mailing list. Thank you.

---- Remove this text before posting ----

**Comment by mu40** [comment]
We just added preliminary d-SynthStrip weights on the [SynthStrip website](https://w3id.org/synthstrip), which you can use with the `--model` flag.

**Comment by buildqa** [comment]
Please (re)post to the Freesurfer help list if you continue to have issues.
