### ISSUE TITLE
recon-all: pushd: too many arguments

### ISSUE THREAD

**Issue by sbashford** [freesurfer/freesurfer#1205]
When passing an input file path containing a space to recon-all via -i, the script aborts with:

pushd: too many arguments

for example:

```shell
recon-all -i "path/to the/file.nii" ...
```

I think this can be remedied by supplying quotes around $InVolDir in the below line:
https://github.com/freesurfer/freesurfer/blob/220a6c6370536cbe34f8a54c744e615ea9732db4/scripts/recon-all#L5947

Does this seem correct? I know about bash, not tcsh...

**Comment by dngreve** [comment]
That would probably work at that line, but below there are going to be many (hundred?) places where the same thing will happen. Bottom line is don't have spaces in your path.
