### ISSUE TITLE
Issues with pctsurfcon

### ISSUE THREAD

**Issue by sRassmann** [freesurfer/freesurfer#1216]
I tried using `pctsurfcon` to calculate WM-GM contrast for non T1 images. While not in the docs, there seems to be a flag (`--mov`) for this application. Nevertheless, I think there is a naming bug as it is parsed as :

```bash
    case "--mov":
      if ( $#argv < 1) goto arg1err;
      set movvol = $argv[1]; shift;
      if(! -e $movvol) then
        echo "ERROR: cannot find $movvol"
        exit 1;
      endif
      breaksw
```
but introduced as 

```bash
set mov = ();
```
and referred to as 
```bash
  if($#mov == 0) set mov = $SUBJECTS_DIR/$subject/mri/$fsvol.mgz
  if(! -e $mov) then
    echo "ERROR: cannot find $mov"
    exit 1;
  endif
```
so the flag does not work.

Further, (at least using the surface pipeline from FastSurfer) the files `lh/rh.aparc.annot` do not exist resulting in the error

```
Reading annotation <subj>/label/lh.aparc.annot
error: No such file or directory
error: could not read annot file <subj>/label/lh.aparc.annot ... trying local annot
error: No such file or directory
error: could not read annot file <subj>/surf/../label/lh.aparc.annot
```
E.g. creating a softlink from `lh/rh.aparc.DKTatlas.mapped.annot` seems to work for me.

Happy to create a PR solving these issues.

**Comment by dngreve** [comment]
Just checked in a fix.
