### ISSUE TITLE
`freeview`   :structure=name Not working.

### ISSUE THREAD

**Issue by toomanycats** [freesurfer/freesurfer#1262]
When attempting to use `freeview -v foo.nii.gz:colormap=lut:structure=1` the viewer does not move the cursor to the proper slice containing the most voxels with label = 1. The cursor is located a default location. There are no errors on the command line. 

I've tried FS ver 7.0.1 through 7.4.1 and none work as expected.

When I mouse click on the label the slice does move. It's only the scripting feature that does not appear to work.
This is a nice feature when creating automated reports on registrations. I'd love if it worked.

```
$ uname -a                                                                                                                                                     
 Linux hostname-foo 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux    
```

**Comment by rpwang17** [comment]
Can you double-check if label 1 actually exists? Have you tried with any other label?

**Comment by toomanycats** [comment]
Yes, I did check and I should have put that here. 

     freeview -v /opt/freesurfer/7.4.1/subjects/bert/mri/aparc+aseg.mgz:colormap=lut:structure=Left-Cerebellum-White-Matter

As you can see in the screen shot, the cursor is not on the label.
![image](https://github.com/user-attachments/assets/f439ecbf-b330-43f8-8bcb-12adfce1adbf)

**Comment by rpwang17** [comment]
This option is to "Move the slice in the main viewport to where it has the most of the given structure". It does not move the cursor in other planes. I guess I can change it so that it moves the slice in all the 3 planes.

**Comment by toomanycats** [comment]
Please recreate my command with `bert`. You'll notice that the image will open at some default view.
If you then double click the labels, the view will change as expected. This should be recreated when I issue the `:structure=name_or_label` option and it does not.

I don't really care where the cross hairs are , but you'll discover that they do indeed move to the centroid of the label selected.

This screen shot is what happens when I double click the label in ROI list. This is different than the previous screenshot.
![image](https://github.com/user-attachments/assets/ae20a11d-aa46-4772-8616-5dd2a178b84f)

**Comment by rpwang17** [comment]
When you double-click a label it moves the cursor to the center of the mass of the label. That is a different thing. I did tried your command, it works as it is supposed to, which is to move the slice in the MAIN VIEW ONLY to where it has the biggest given structure. The other views will remain default. 

Like I said earlier, if you'd like to move the slices on all the views from the command-line, I can add an option do that.

**Comment by toomanycats** [comment]
You are correct my bad. I don't need the cursor to move.
