### ISSUE TITLE
Example in help cannot run

### ISSUE THREAD

**Issue by Stuming** [freesurfer/freesurfer#133]
Hey, my FREESURFER version is: freesurfer-Linux-centos6_X86_64-stable-pub-V6.0.0.

I run the example in `fcseed-sess `:

`2. Create white matter and ventricular CSF nuisance regressors
   
     fcseed-sess -o wm.dat   -wm   -s session -fsd rest
     fcseed-sess -o vcsf.dat -vcsf -s session -fsd rest`

And I get an ERROR: Flag -o unrecognized.

I check the source code in branch `stabel6`, and it seems `-o` only works in `fcseed-config`, and not works in `fcseed-sess`.

Maybe you should modify your help in these two files(`fcseed-config`, `fcseed-sess`), or I misunderstand the meaning of this help.

**Comment by dngreve** [comment]
Hi, would you mind submitting this to the freesurfer mailing list rather than github? It makes it much easier for us to have one place where all this is handled. 
thanks
doug
