### ISSUE TITLE
git annex not working

### ISSUE THREAD

**Issue by chrisadamsonmcri** [freesurfer/freesurfer#143]
I'm building freesurfer according to the instructions on the git page. Annex is not downloading the data files. The logs are pasted below.

git remote -v
datasrc	https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git (fetch)
datasrc	https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git (push)
origin	https://github.com/chrisadamsonmcri/freesurfer.git (fetch)
origin	https://github.com/chrisadamsonmcri/freesurfer.git (push)
upstream	git@github.com:freesurfer/freesurfer.git (fetch)
upstream	git@github.com:freesurfer/freesurfer.git (push)

git annex get --metadata fstags=makeinstall .
get BrainstemSS/linux_x86_64/segmentSubject (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

  (Note that these git remotes have annex-ignore set: origin upstream)
failed
get BrainstemSS/mac_osx/segmentSubject.app/Contents/MacOS/segmentSubject (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

  (Note that these git remotes have annex-ignore set: origin upstream)
failed
get HippoSF/AtlasDump.mgz (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

  (Note that these git remotes have annex-ignore set: origin upstream)
failed
get HippoSF/AtlasMesh.gz (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

  (Note that these git remotes have annex-ignore set: origin upstream)
failed
get HippoSF/linux_x86_64/SegmentSubfieldsT1Longitudinal (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

  (Note that these git remotes have annex-ignore set: origin upstream)
failed
get HippoSF/linux_x86_64/segmentSubjectT1T2_autoEstimateAlveusML (from datasrc...) 
  Unable to access these remotes: datasrc

  Try making some of these repositories available:
  	16e5e991-f665-40b5-b639-35dc7e859f97 -- iglesias@panamint:/autofs/space/panamint_005/users/iglesias/software/freesurfer
   	54f67f98-f3e4-4367-b65f-4fbb622ec17d -- zkaufman@sand:/space/freesurfer/repo/annex.git [datasrc]
   	9a8bd918-e920-4c39-bf99-b70b68e85907

**Comment by ahoopes** [comment]
Working on this now - it seems to only be an issue for users outside of the martinos network

**Comment by ahoopes** [comment]
These files should be accessible now. Are you able to retrieve them?

**Comment by chrisadamsonmcri** [comment]
Yeah it is working now. Thanks so much.
