### ISSUE TITLE
Build fail with OpenGL libraries

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#228]
---- WHEN REPORTING AN ISSUE CUT HERE and ABOVE ----

### Platform details: 

- FreeSurfer version:  Github source 
- Operating system name and version: Fedora 21 GCC6

### Summary
FreeSurfer fails to build due to what appears to be missing OpenGL libraries in the link line

### Actual behavior
Errors shown below in Details

### Expected behavior
Completed build
### How to replicate the behavior
Follow Linux Developer build instructions
### Details
The Freesurfer build fails at this command:
libtool: link: g++ -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-Map -Wl,ld_map.txt -Wl,--no-demangle -o mris_show mris_show.o /usr/lib64/libuuid.so  -L/home/melrobin/packages/centos6-x86_64-packages/qt/current/lib -L/usr/lib64
 -L/usr/X11R6/lib64 -L/home/melrobin/packages/centos6-x86_64-packages//mni/current/lib -L/home/melrobin/packages/centos6-x86_64-packages//vxl/current/lib -L/home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit ../utils/libutils.a ../minc_substitute/libminc_substitute.a ../fsgdf/libfsgdf.a ../rgb/librgb.a ../unix/libunix.a ../dicom/libdicom.a ../hipsstubs/libhipsstubs.a ../log/liblog.a ../xml2/libxml2.a ../jpeg/libjpeg.a ../tiff/libtiff.a ../expat/libexpat.a ../glut/libglut.a -L/lib64 -lX11 -lXmu /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKIO.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKAlgorithms.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKCommon.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKNumerics.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKMetaIO.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKniftiio.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKNrrdIO.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkpng.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitksys.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitktiff.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkv3p_netlib.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkzlib.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkgdcm.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkopenjpeg.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkjpeg8.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkjpeg12.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libitkjpeg16.a /home/melrobin/packages/centos6-x86_64-packages//itk/current/lib/InsightToolkit/libITKDICOMParser.a -lz -lm -lcrypt -ldl -lpthread /home/melrobin/packages/centos6-x86_64-packages//mni/current/lib/libvolume_io.a /home/melrobin/packages/centos6-x86_64-packages//mni/current/lib/libminc.a /home/melrobin/packages/centos6-x86_64-packages//mni/current/lib/libnetcdf.a -lvnl_algo -lvnl -lvcl -lnetlib -lv3p_netlib

and produces lots of these types of errors
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:878: undefined reference to `glViewport'
mris_show.o: In function `special_key_handler':
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:923: undefined reference to `glMatrixMode'
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:937: undefined reference to `glRotatef'
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:955: undefined reference to `glRotatef'
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:945: undefined reference to `glRotatef'
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:951: undefined reference to `glRotatef'
/home/melrobin/packages/freesurfer/mris_show/mris_show.c:933: undefined reference to `glRotatef'

The build seems not to include the OpenGL libraries when building mris_show as you can see from the link line.  I'm trying to trace this up the Autotools chain, but need some help.  I can work a little more on a fix with a little guidance telling me where to look.

**Comment by melrobin** [comment]
This has also failed under gcc4.8

**Comment by ahoopes** [comment]
It looks like your compilation is missing the `-lGLU -lGL` library flags. You should check mris_show/Makefile to make sure that `GL_LIBS` and `GLU_LIBS` have been set:

`grep -e GLU_LIBS -e GL_LIBS mris_show/Makefile`

If not, it's possible that you just need to install these libs with `yum install mesa-libGL-devel mesa-libGLU-devel` and reconfigure. You can also check this by inspecting the configure output for "GL found" and "GLu found"

**Comment by melrobin** [comment]
Thank you very much for your response!  Here is the output from grep:
GLU_LIBS =
GL_LIBS = -lGL -L/lib64 -lX11  -lm
WXWIDGETS_GL_LIBS = -L/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib -pthread   -L/usr/X11R6/lib64   -L/usr/lib64 /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_gl-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_base-2.8.a -lGL -lGLU -lz -ldl -lm

GL_LIBS is set, but GLU_LIBS is empty, but both libraries appear in WXWIDGETS_GL_LIBS.  

I don't have mesa installed, but have the NVIDIA drivers.  Does Freesurfer require Mesa?

**Comment by ahoopes** [comment]
The `mesa-libGLU-devel` library is [required to build freesurfer](http://freesurfer.net/fswiki/freesurfer_linux_developers_page#CentOS7)

**Comment by melrobin** [comment]
OK, these packages were previously installed:
[melrobin@scorpion freesurfer]$ sudo dnf install mesa-libGLU-devel
[sudo] password for melrobin:
Last metadata expiration check: 1:20:59 ago on Tue Jan  2 12:49:57 2018.
Package mesa-libGLU-devel-9.0.0-10.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[melrobin@scorpion freesurfer]$ sudo dnf install mesa-libGL-devel
Last metadata expiration check: 1:22:09 ago on Tue Jan  2 12:49:57 2018.
Package mesa-libGL-devel-17.0.5-3.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

There must be some problem in detecting this on my system.  Which part of the build system would pick this up?

**Comment by melrobin** [comment]
So somehow WXWIDGETS_GL_LIBS picks up the relevant libraries, but the build system does not assign GLU_LIBS.   Also, the library list in the initial post does not have either library.

**Comment by ahoopes** [comment]
Oh okay - I don't think wxWidgets is actually detecting `-lGLU`, it looks like that flag is hard-coded on line 949 of *centos6-x86_64-packages/wxWidgets/current/bin/wx-config*. That being said, `GLU_LIBS` is set by the automake macro `AX_CHECK_GLU`, which searches for libGLU, during configuration:

https://github.com/freesurfer/freesurfer/blob/3d8ef80c5f193217d2bad70d07aa2bc7d7946a95/configure.in#L3055

I just noticed that our current error handling of `AX_CHECK_GLU` looks outdated, so the configuration doesn't actually quit if the GL utility lib isn't detected. You can check the config.log to see what went wrong during the detection:

`grep -m1 -A10 "lGLU" config.log`

An ld error would hopefully provide some hints

**Comment by melrobin** [comment]
Yes there was indeed a linker error:
[melrobin@scorpion freesurfer]$ grep -m1 -A10 "lGLU" config.log
configure:26975: /home/melrobin/gcc-4.8/bin/g++ -o conftest    -g -O3 -msse2 -mfpmath=sse -Wall -Wno-unused-parameter -Werror -Wno-unused-variable -Wno-narrowing -Wno-aggressive-loop-optimizations -Wno-switch -Wno-enum-compare -Wno-unused-local-typedefs -Wno-unused-but-set-variable -fno-strict-overflow -Wno-maybe-uninitialized -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-result -Wno-unused-local-typedefs -DUSE_SSE_MATHFUN   -L/home/melrobin/packages/centos6-x86_64-packages/qt/current/lib -L/usr/lib64 -L/usr/X11R6/lib64  conftest.cpp -lGLU -lGL -L/lib64 -lX11  -lm  >&5
/usr/lib64/libGLU.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/usr/lib64/libGLU.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
configure:26975: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Freesurfer"
| #define PACKAGE_TARNAME "freesurfer"
| #define PACKAGE_VERSION "dev"
| #define PACKAGE_STRING "Freesurfer dev"

This found libGLU.so, but maybe it failed because of come C++ ABI stuff that I could change.

**Comment by ahoopes** [comment]
I see, so it must be a gcc versioning issue. CXXABI_1.3.8 is associated with gcc4.9 and CXXABI_1.3.9 is associated with gcc5.1. So based on [this thread](https://stackoverflow.com/questions/29230777/program-linking-fails-when-using-custom-built-gcc), you can either manually build the library with your gcc4.8, or you can try building freesurfer with 5.1, but unfortunately, this will likely introduce a bunch of compile errors

**Comment by melrobin** [comment]
I'll try to straighten this out and try the grep again.

**Comment by ahoopes** [comment]
I was just able to replicate the original issue in a fedora27 docker with gcc4.9. When I switched back to using the default gcc7.2, GLU was successfully detected, but it introduced a bunch of errors when compiling the cpputils. So not too helpful :/ but at least it confirms the source of the problem

**Comment by buildqa** [comment]
If the gcc c++ rev 4.9 compiler is not the default compiler on your system, then you may need to set LD_LIBRARY_PATH to point to the accompanying newer version of libstdc++ with the CXXABI_1.3.8 symbol.  In this case, presumably you set your PATH to point to the  gcc 4.9 ./bin directory, e.g., say gcc was installed under /usr/local/gcc4.9/bin.   Parellel to that ./bin subdirectory, or somewhere in the installtion is a ./lib directory with the libstdc++ you need to find.   So for this example, LD_LIBRARY_PATH could be set as,

export LD_LIBRARY_PATH=/usr/local/gcc4.9/lib:$LD_LIBRARY_PATH

**Comment by melrobin** [comment]
I tried to change LD_LIBRARY_PATH and LIBRARY_PATH to /home/melrobin/gcc-4.9/lib64 which contains libstdc++.  There is a still the undefined reference to CXXABI_1.3.9.  Changing the compiler to gcc 4.8 results in both CXXABI_1.3.8 and CXXABI_1.3.9 linker errors.  Changing the compiler to the system default 6.4.1and gcc 5 has the same behavior as gcc 4.9.  

The plot thickens a bit, but at least there are some more experiments that I can do.

**Comment by melrobin** [comment]
It appears that I do not have libsupc++.so, but have libsupc++.a.  I'll see what it takes to produce the shared library which might allow LD_LIBRARY_PATH to work.

**Comment by melrobin** [comment]
Could this be a problem:
[melrobin@scorpion freesurfer]$ ldd /usr/lib64/libGLU.so
/usr/lib64/libGLU.so: /home/melrobin/gcc-4.9/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib64/libGLU.so)
        linux-vdso.so.1 (0x00007ffc77bce000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f8c22d47000)
        libstdc++.so.6 => /home/melrobin/gcc-4.9/lib64/libstdc++.so.6 (0x00007f8c22a3d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8c22734000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8c2236e000)
        libgcc_s.so.1 => /home/melrobin/gcc-4.9/lib64/libgcc_s.so.1 (0x00007f8c22157000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f8c21f25000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f8c21be6000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f8c219d4000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f8c2171e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8c2151a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8c212fc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8c23241000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f8c210d4000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f8c20ed0000)

Why would OpenGL be linked to my custom built gcc/g++?

**Comment by melrobin** [comment]
More information:  The mesa-libGLU-devel was from fedora 24:
===============================================================================================================================================
 Package                             Arch                           Version                               Repository                      Size
===============================================================================================================================================
Reinstalling:
 mesa-libGLU                         x86_64                         9.0.0-10.fc24                         fedora                         179 k

I feel this is getting closer to resolution.

**Comment by buildqa** [comment]
You could also try looking for that symbol in your libstdc++ library with, 

$ strings  /home/melrobin/gcc-4.9/lib64/libstdc++.so.6 | grep CXXABI

If you see some (of the older) CXXABI symbols like CXXABI_1.3.8, 1.3.7, etc. - but not the newer 1.3.9 one you need, then it means the libstdc++ library (or that gcc distribution) is too old.   You can set LD_LIBRARY_PATH to force the search path for libraries to anywhere, e.g.,  /home/melrobin/gcc-4.9/lib64 - but I'm this case it needs to point to a new enough version of libstdc++ to resolve the symbols required by the native OpenGL libraries.  But there is no guarantee that a newer gcc distribution with a libstdc++ containing  CXXABI_1.3.9  will compile the code at this point in time w/o errors.

So I would unset LD_LIBRARY_PATH.  Then if you do that ldd command again on /usr/lib64/libGLU.so you should see a different libstdc++, and you can check with the strings command if that one contains the needed CXXABI_1.3.9  symbol.  My CentOS 7 system only needs the older CXXABI symbols.

% ldd /usr/lib64/libGLU.so | grep libstdc
	libstdc++.so.6 => /lib64/libstdc++.so.6
% strings /usr/lib64/libGLU.so | grep CXXABI
CXXABI_1.3

Out of curiosity, do you have a "patchelf" command on your machine, or does this command return anything?

$ which patchelf

**Comment by melrobin** [comment]
The strings command allowed me to see that gcc4.9 does not have CXXABI_1.3.9, but as Andrew mentioned gcc5 does.  However, the grep fails even with gcc5: 
/usr/lib64/libGLU.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

which is strange to me.  Which version of the mesa-GLU-devel package do you use?  Maybe the one I use is too new for Freesurfer and I could install an earlier version.

I put patchelf on my system

**Comment by melrobin** [comment]
I was able to clear the problem that grep pointed out with this configure line:
CC=/usr/local/gcc-4.8/bin/gcc CXX=/usr/local/gcc-4.8/bin/g++  CXXFLAGS=-static-libstdc++ ./configure --disable-Werror --with-pkgs-dir=/home/melrobin/packages/centos6-x86_64-packages/

Adding the static libstdc++ seems to allow -lGLU to be found:
checking for OpenGL Utility library... -lGLU
GLu found:
Setting GLU_CFLAGS='-pthread '
and GLU_LIBS='-lGLU -lGL -L/lib64 -lX11  -lm'

Do you know what could be wrong with the compilers?  

This has allowed more progress, but the build now fails with this error:
autoencoder.c: In function ‘AEaccumulateGradient’:
../include/romp_support.h:78:18: error: ‘ROMP_pf_stack’ undeclared (first use in this function)
     ROMP_pf_end(&ROMP_pf_stack); \

I do not think that the two are related however.

**Comment by buildqa** [comment]
From what I can see in romp_support.h, it looks like a function gets defined which contains the define of ROMP_pf_stack - and - that function should already be called to do the define so ROMP_pf_stack is defined at line 78.  You can see my compilation line for autoencoder.c below (as it worked for me on CentOS7).   Maybe it would help to configure things so you have -DHAVE_OPENMP on the compilation line (as I do).

I hope the following info useful with regard to the previous posts....

Depending upon what symbols are removed (stripped) from binaries, then there can be limitations to what the "strings" or "nm" commands can show you.  The "nm" command is more flexible; here is a brief post about how to use it,  https://www.thegeekstuff.com/2012/03/linux-nm-command/

When you run "ldd" on a binary to see the library references, it can be good to know that the paths listed to its dynamic libs can be determined from searching different path variables.  The libs found can be the result of searching LD_LIBRARY_PATH, but they can also be the result of searching the paths in the RPATH as set in the binary you are running ldd on.  Setting RPATH in a binary (at link time) can be preferable to globally setting LD_LIBRARY_PATH in the environment, as RPATH is searched first if present, I believe, even if LD_LIBRARY_PATH is set.   This is why I asked if you had "patchelf" installed on your system, i.e., patchelf (or readelf) will show you RPATH if there is one set ( "patchelf --print-rpath myprogram") - but patchelf will also let you change it.  RPATH is often used to make the dynamic lib references relative to where the binaries live by setting RPATH to something like '$ORIGIN/../lib' e.g., "gcc main.c -Wl,-rpath='$ORIGIN/../lib' -lfoo -lbar"  This can help to make binary and library distributions self-contained.  There's not really any point in putting system lib locations like /lib64 or /usr/lib64 in RPATH - as those should be set to be searched by default (after RPATH is searched).  There are many postings about this, but these seem to be good, 

https://stackoverflow.com/questions/33519640/why-i-cannot-override-search-path-of-dynamic-libraries-with-ld-library-path/33520976#33520976

https://blog.flameeyes.eu/2010/06/the-why-and-how-of-rpath/
- - - - - - - - - - - - - - - - - - - -
My CentOS7 autoencoder.c compile:

$ gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/dicom -I../xml2 -I../include/NrrdIO -DTEEM_DIO=0 -DTEEM_32BIT=0 -DTEEM_QNANHIBIT=1 -DTEEM_ENDIAN=1234 -I../jpeg -I../tiff -I../expat -I/usr/pubsw/packages/itk/current/include/InsightToolkit -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Algorithms -I/usr/pubsw/packages/itk/current/include/InsightToolkit/BasicFilters -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Common -I/usr/pubsw/packages/itk/current/include/InsightToolkit/IO -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Numerics -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Numerics/Statistics -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Review -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Review/Statistics -I/usr/pubsw/packages/itk/current/include/InsightToolkit/SpatialObject -I/usr/pubsw/packages/itk/current/include/InsightToolkit/Utilities -DHAVE_ITK_LIBS  -I../glut -DHAVE_GLUT_LIBS  -I/usr/pubsw/packages/vxl/current/include/vxl/core -I/usr/pubsw/packages/vxl/current/include/vxl/vcl -I/usr/pubsw/packages/vxl/current/include/vxl/v3p/netlib -I/usr/pubsw/packages/vxl/current/include/vxl/v3p/netlib/opt  -DHAVE_ZLIB -g -O3 -msse2 -mfpmath=sse -Wall -Wno-unused-parameter -Werror -Wno-unused-variable -Wno-narrowing -Wno-aggressive-loop-optimizations -Wno-switch -Wno-enum-compare -Wno-unused-local-typedefs -Wno-unused-but-set-variable -fno-strict-overflow -Wno-maybe-uninitialized -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-result -Wno-unused-local-typedefs -DUSE_SSE_MATHFUN -fopenmp -DHAVE_OPENMP -m64 -DLinux -DANSI -fdata-sections -ffunction-sections -Wl,--gc-sections -fno-lto -I/usr/pubsw/packages/mni/current/include  -fno-lto -MT autoencoder.o -MD -MP -MF .deps/autoencoder.Tpo -c -o autoencoder.o autoencoder.c

**Comment by melrobin** [comment]
Thank you very much for your help!  I was able to get much further into the build based on your OpenMP suggestions and building libGLU with gcc4.8 ensuring that CXXABI1.3.9 would not be a dependency.  I have some Boost issues to try to work through, but that is a different issue.  The Fedora 25 mesa-libGLU-devel package seems to require gcc5+
