### ISSUE TITLE
confirm that mris_register is running multi-threaded

### ISSUE THREAD

**Issue by nschmans** [freesurfer/freesurfer#319]
in a recent run of recon-all -s subjid -all -parallel -openmp 8,  upon completion and grepping recon-all.log for FSRUNTIME, it displayed this:

FSRUNTIME@ mri_ca_register  1.1117 hours 8 threads
FSRUNTIME@ mris_sphere  0.0338 hours 8 threads
FSRUNTIME@ mris_sphere  0.0319 hours 8 threads
FSRUNTIME@ mris_fix_topology lh  0.2741 hours 8 threads
FSRUNTIME@ mris_fix_topology rh  0.1889 hours 8 threads
FSRUNTIME@ mris_sphere  0.1200 hours 8 threads
FSRUNTIME@ mris_sphere  0.1065 hours 8 threads
FSRUNTIME@ mris_register  0.1354 hours 1 threads
FSRUNTIME@ mris_register  0.1477 hours 1 threads

so it seems mris_register did not run with 8 threads, although a quick glance of mris_register.c shows that it should have (ie, HAVE_OPEN looked active).

**Comment by emtpgeek** [comment]
I'll look into

**Comment by emtpgeek** [comment]
It is using all 8 threads, it is the message that is wrong

**Comment by emtpgeek** [comment]
https://github.com/freesurfer/freesurfer/pull/320

**Comment by nschmans** [comment]
thanks
