### ISSUE TITLE
Build fail on MHTgetBucket

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#325]
### Platform details:

- FreeSurfer version:  Development
- Operating system name and version: Fedora 25

### Summary
Build fails with linking error on MHTgetBucket function
### Actual behavior
tksurfer-tksurfer.o: In function `deconvolve_weights':
/home/melrobin/packages/freesurfer/tksurfer/tksurfer.c:23587: undefined reference to `MHTgetBucket'
### Expected behavior
Good compile
### Details
The function MHTgetBucket does not appear in any of the source code.  
Please put URL to code or code here (if not too long).

**Comment by emtpgeek** [comment]
It has been replaced by MHT{acq,rel}Bucket because buckets need to be locked and released when in parallel code

Please replace the call with MHTacqBucket  and add a MHTrelBucket call when the bucket is no longer in use

/Bevin

**Comment by emtpgeek** [comment]
or I can do it - but it will take longer to arrive in your dev that way

**Comment by melrobin** [comment]
OK, thank you very much.  I will make the mods and see what happens.

**Comment by melrobin** [comment]
OK, I was able to move past this error, but should an MHTrealBucket occur at the end of the file.  I'm not quite sure what this function does.

**Comment by emtpgeek** [comment]
If the mhtacqbucket returns a non null value, then that bucket is locked.  The mhtrelbucket unlocks it.  If you don't unlock it then all further attempts to acquire the bucket will hang.  So you should always call the release function for every bucket you acquire.

**Comment by ahoopes** [comment]
Is this the correct usage? https://github.com/freesurfer/freesurfer/pull/326/commits/5185fe496d3d83dacb9785ad0498d3c38505f669

**Comment by melrobin** [comment]
The changes allow a clean build.
