### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#332]
### Platform details:

- FreeSurfer version:  Development
- Operating system name and version:  Fedora 25

### Summary
Build failure with mrisurf.c
### Actual behavior
mrisurf.c:9663:54: error: ‘FACE {aka struct face_type_}’ has no member named ‘orig_area’; did you mean ‘orig_angle’?
       delta = (double)(area_scale * face->area - face->orig_area);
### Expected behavior
Clean build
### Details
The struct face has no member orig_area.  There are changesets that change face->orig_area to fNorm->orig_area, but fNorm is not defined in mrisurf.c

**Comment by ahoopes** [comment]
This should be fixed for you now, right?

**Comment by melrobin** [comment]
No, the problem with face->orig_area is still there.  This line was not changed with the recent changesets.

**Comment by melrobin** [comment]
This is fixed.
