### ISSUE TITLE
[recommendation] Enable code tests coverage reporting

### ISSUE THREAD

**Issue by yarikoptic** [freesurfer/freesurfer#334]
Now that you are "all github and travis"...
Tests code coverage is very common (and useful) for python projects but I had no idea that it is possible now to upload coverage reports to coveralls for C/C++ projects.  I saw it used by vowpal_wabbit: https://github.com/JohnLangford/vowpal_wabbit/blob/master/.travis.yml which apparently uses gcov and https://github.com/eddyxu/cpp-coveralls to upload to coveralls (I personally now prefer codecov over coveralls but I am not sure if similar helper exists for it)

**Comment by buildqa** [comment]
There are some tests on individual commands run as part of nightly builds as they are not time consuming.  The recon-all test still takes a while however.  I am not sure what (other) plans there may be w.r.t code coverage.

**Comment by yarikoptic** [comment]
It was just a recommendation... since tests were disabled on Travis altogether, not sure if it is still pertinent

**Comment by buildqa** [comment]
OK thanks, closing this one for now.
