### ISSUE TITLE
Bug: DICOMread.c bad handling of DICOM read for DWI params

### ISSUE THREAD

**Issue by nschmans** [freesurfer/freesurfer#340]
there is a bug in DICOMread.c (in freesurfer).  the error line is 4799, and the code tries to read DWI parameters when reading a philips dicom file, but on a valid Philips DICOM structural scan (not DWI) it fails to convert the dicom to mgz, with errors like those shown below.   the workaround is to declare this environment var:

setenv FS_LOAD_DWI 0

perhaps DoDWI should not default to 1, or the error handling of not detecting DWI info (which will not exist in a structural T1W scan) should be different.

some sample data, to try mri_convert to 001.mgz, is here:

/autofs/cluster/freesurfer/subjects/test/S10493

here's the error dump:

ERROR: GetDICOMInfo(): dcmGetDWIParams() 7
DICOM File: /Users/cmet/Desktop/Folders/ADNI30/DICOMS/018_S_0043/ADNI_______MPRAGE-1.2_/2005-12-08_13_16_26.0/S10493/ADNI_018_S_0043_MR_ADNI_______MPRAGE-1.2__br_raw_20051212145138088_150_S10493_I9324.dcm
break DICOMRead.c:4799
ERROR: GetDICOMInfo(): dcmGetDWIParams() 7
DICOM File: /Users/cmet/Desktop/Folders/ADNI30/DICOMS/018_S_0043/ADNI_______MPRAGE-1.2_/2005-12-08_13_16_26.0/S10493/ADNI_018_S_0043_MR_ADNI_______MPRAGE-1.2__br_raw_20051212145138573_149_S10493_I9324.dcm
break DICOMRead.c:4799
First Sorting
Computing Slice Direction
Vs: 1.2 0 0
Vs: 1 0 0
Second Sorting
IsDWI = 0, IsPhilipsDWI = 0
Counting frames
nframes = 1
nslices = 92
ndcmfiles = 92
PE Dir = ROW (dicom read)
CTABreadASCII(/Applications/freesurfer-git/FreeSurferColorLUT.txt): could not open file
ERROR: getcwd returned no pathToo many open files
ERROR: reading /Applications/freesurfer-git/FreeSurferColorLUT.txt
Loading pixel data
ERROR: /Users/cmet/Desktop/Folders/ADNI30/DICOMS/018_S_0043/ADNI_______MPRAGE-1.2_/2005-12-08_13_16_26.0/S10493/ADNI_018_S_0043_MR_ADNI_______MPRAGE-1.2__br_raw_20051212145132276_1_S10493_I9324.dcm is not a dicom file
   70092 Requested element (18 82) not found in DCM_GetElementVM
   70092 Requested element (18 9087) not found in DCM_GetElementVM

**Comment by ahoopes** [comment]
Would requiring an environment variable like `LOAD_PHILIPS_DWI` be a reasonable/less invasive fix? Globally disabling DWI loading is probably the cleanest option, but not very backwards compatible, especially for the ex-vivo pipelines. I'm not sure how common Philips DWI scans are anyway

**Comment by nschmans** [comment]
i think the existing FS_LOAD_DWI environment variable operates the same as your proposed LOAD_PHILIPS_DWI variable.  so essentially, there is a fix available (and, in fact, we at cmet have already incorporated setting FS_LOAD_DWI to 0 to avoid this problem).   changing the default to 0 would change the existing assumed behavior, which presumably would break existing DWI tools.  so now its a question of which user base should be setting the environment var.   i think the 'right' thing to do is to either fix the code to be smarter on checking for the DWI info in the DICOM before performing tests on it, or make the default to check for these special DWI fields only if a var is set.  but, i guess to put a lid on it, i'm happy to drop this issue (given that there is a workaround) if the parties who need to make this change are not willing.

**Comment by ahoopes** [comment]
I was thinking that `DoDWI` would still default to 1, except when reading Philips scans, in which case `LOAD_PHILIPS_DWI` would have to be set. But I agree that the best option is just to fix the DICOM reader. We can leave the issue open for now, and I'll take a look into the code soon and try to sort out a fix.

**Comment by ahoopes** [comment]
how about this - https://github.com/freesurfer/freesurfer/pull/443? Now, if there's an initial failure while reading DWI info in Philips DICOMs, it assumes that the DWI data doesn't exist and continues on without error. However, if `FS_LOAD_DWI` is set, it assumes the DWI data actually does exist and produces the original errors

**Comment by nschmans** [comment]
That seems reasonable.  I will close the issue.  Thanks!
