### ISSUE TITLE
asegstats2table --skip when first subject is wrong

### ISSUE THREAD

**Issue by ntraut** [freesurfer/freesurfer#347]
Issue:
When using the script `asegstats2table` with the `--skip` option, when the first subject given is not good then the script raise the following error when it reaches the first good subject:
```
Traceback (most recent call last):
  File "/Applications/freesurfer/bin/asegstats2table", line 568, in <module>
    if(nmeasures != nmeasures0 and not options.common_flag and not options.all_flag):
NameError: name 'nmeasures0' is not defined

```
Solution:
It just needs to modify few lines in `asegstats2table` to fix this bad behavior. I can make a pull request if wanted.

**Comment by ahoopes** [comment]
Thanks for pointing this out! Feel free to submit a pull request if you'd like
