### ISSUE TITLE
pctsurfcon does not use outbase for stats file

### ISSUE THREAD

**Issue by ntraut** [freesurfer/freesurfer#353]
### Actual behavior
With `pctsurfcon` we can use an alternative outbase to replace the default out file name `?h.w-g.pct.mgh`. But for the stats file name it is always `?h.w-g.pct.stats`.

### Expected behavior
It should produce a stats file with the same outbase as for the mgh file. I will propose a PR in that sense.

### Details
`set sum = $SUBJECTS_DIR/$subject/stats/$hemi.$OutBase.stats`

**Comment by ahoopes** [comment]
@ntraut is this fixed with https://github.com/freesurfer/freesurfer/pull/354?

**Comment by ntraut** [comment]
Yes I fixed the issue with #354. It should be ok now.
