### ISSUE TITLE
fsgdf looking in wrong place for tcl8.4?

### ISSUE THREAD

**Issue by williford** [freesurfer/freesurfer#36]
I went back to trying the `make check`, because I need `flirt.fsl` and this is currently not being installed (I believe it should be in "$FREESURFER_HOME/bin" - which does contain mri_motion_correct.fsl). It seems that calling mri_motion_correct2 instead of mri_motion_correct.fsl might have solved my problem (mri_motion_correct.fsl complained that flirt.fsl could not be found).

I am now getting the error:

```
==========================================
   Freesurfer dev: fsgdf/test-suite.log
==========================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test
==========
<snip>
8 Control-Siemens-Female  14.6667  37.3333 
INFO: bvolumeRead: min = 0.07, max = 6.98333
C Test successful.

Tcl_CreateInterp...done.
Tcl_Init...Tcl_Eval returned not TCL_OK:
Trying: Tcl_Init returned not TCL_OK
Result: Can't find a usable init.tcl in the following directories: 
    /usr/pubsw/packages/tcltktixblt/current/lib/tcl8.4
```

My configure command was:
`./configure --disable-Werror --with-pkgs-dir=/home/jonathan/.local/install/freesurfer/centos6-x86_64-packages --prefix=/usr/local/freesurfer`

So I would have expected the tcl8.4 to look in the
`/home/jonathan/.local/install/freesurfer/centos6-x86_64-packages/tcltktixblt/current/lib/tcl8.4` directory. This directory does contain init.tcl.

I'm not sure how the `/usr/pubsw` got in there. It is not in the Makefile.am, but it is in the generated Makefile. For example:

```
Makefile
603:QT_LIBS = -L/home/jonathan/.local-jessie/install/freesurfer/centos6-x86_64-packages/qt/current/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5X11Extras -L/usr/pubsw/packages/qt/5.6.2/5.6/gcc_64/lib -lQt5Gui -lQt5Script -lQt5ScriptTools -lQt5Core -lGL -lpthread 
656:WXWIDGETS_CFLAGS = -I/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/wx/include/gtk2-ansi-release-static-2.8 -I/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -D__WXGTK__ -pthread    -D__WXGTK20__   -I/usr/include/gtk-2.0  -I/usr/lib/gtk-2.0/include      -I/usr/include/gdk-pixbuf-2.0 -I/usr/lib64/gtk-2.0/include    -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include     -I/usr/lib64/glib-2.0/include   -I/usr/include/pango-1.0      -I/usr/include/cairo    -I/usr/include/atk-1.0
657:WXWIDGETS_CXXFLAGS = -I/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/wx/include/gtk2-ansi-release-static-2.8 -I/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -D__WXGTK__ -pthread  -D__WXGTK20__   -I/usr/include/gtk-2.0  -I/usr/lib/gtk-2.0/include      -I/usr/include/gdk-pixbuf-2.0 -I/usr/lib64/gtk-2.0/include    -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include     -I/usr/lib64/glib-2.0/include   -I/usr/include/pango-1.0      -I/usr/include/cairo    -I/usr/include/atk-1.0
659:WXWIDGETS_GL_LIBS = -L/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib -pthread   -L/usr/X11R6/lib64   -L/usr/lib64 /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_gl-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_base-2.8.a -lGL -lGLU -lz -ldl -lm 
660:WXWIDGETS_LIBS = -L/usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib -pthread   -L/usr/X11R6/lib64   /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_richtext-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_aui-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_xrc-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_qa-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_html-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_adv-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_gtk2_core-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_base_xml-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_base_net-2.8.a /usr/pubsw/packages/wxWidgets/wxGTK-2.8.9/lib/libwx_base-2.8.a -Wl,--export-dynamic -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lpangoxft-1.0 -lpangox-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lXinerama -lXxf86vm -lSM -lpng ../jpeg/libjpeg.a ../tiff/libtiff.a ../expat/libexpat.a -lz -ldl -lm  -lwx_gtk2_gl-2.8
```

**Comment by zkaufman** [comment]
@williford The issue has something to do with the fact that we are creating a tarball of these installed packages and moving them from their original installation location. (You'll notice that the `centos6-x86_64-packages/tcltktixblt/current/lib/tclConfig.sh` file has the original `/usr/pubsw/packages` directory hardcoded in it.)

This was true with the Qt installation as well, but we were able to get around that issue by modifying the `qt/current/bin/qt.conf` file (This is done by the `centos6-x86_64-packages/setup.sh` script).

I've tried modifying the hardcoded paths in `tclConfig.sh` but was unable get ride of the issue. I ultimately added the `--disable--tcktk-apps` to the `configure` script and this bypasses the whole `fsgdf` build and check. I will need to perform a full test suite to be absolutely sure passing the `--disable-tcltk-apps` is ok, but I strongly beleive it is as the build finished without error and we are deprecating the tcltk apps anyway.
