### ISSUE TITLE
dngtester Makefile has a hardwired path to the ITK directories in pubsw

### ISSUE THREAD

**Issue by emtpgeek** [freesurfer/freesurfer#431]
### Platform details:  

- FreeSurfer version: dev 
- Operating system name and version: Ubuntu 16.04 gcc 5.4

### Summary
dngtester Makefile has a hardwired path to the ITK directories in pubsw, rather than using those supplied in the configure invocation

**Comment by ahoopes** [comment]
This should be fixed with https://github.com/freesurfer/freesurfer/pull/432 and https://github.com/freesurfer/freesurfer/pull/433. I removed the hardcoded paths, and cpptester now  won't be built without ITK
