### ISSUE TITLE
mris_sphere/mris_register give different negative triangle counts based on Linux kernel/OMP_NUM_THREADS

### ISSUE THREAD

**Issue by ltirrell** [freesurfer/freesurfer#434]
## Platform details:
- FreeSurfer version: 
Custom built dev version, based on git commit [5b0b659](https://github.com/freesurfer/freesurfer/tree/5b0b65905081aadc18d12fc9041623a3cd668b71), using ITK and VXL built by running `make build-itk && make build-vxl` from the `packages` dir
- Operating system name and version:
  - Ubuntu 16 (`Linux ip-172-31-61-33 4.4.0-1057-aws #66-Ubuntu SMP Thu May 3 12:49:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)
  - Ubuntu 14 (`Linux ip-172-31-78-211 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)
  - Amazon Linux (`Linux ip-172-31-10-20 4.9.85-38.58.amzn1.x86_64 #1 SMP Wed Mar 14 01:17:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)

## Summary
An Ubuntu 16-based Docker container was used to run a FreeSurfer-based workflow on the above operating systems. Depending on the kernel/OS of the Host operating system, the number of "negative triangles"  seen in the `mris_sphere`/`mris_register` steps are greatly different, with higher number of negative triangles causing more iterations (and longer run time). Additionally, on the same host, different results are seen if `OMP_NUM_THREADS` is set to 1 or 8. 

## Actual behavior
Here is first listing for the number of "negative triangles" seen in the log file for the same subject in 5 different run environements (`OMP_NUM_THREADS=8` on Amazon Linux, Ubuntu 16, and Ubuntu 14; `OMP_NUM_THREADS=1` on Ubuntu 14 and Ubuntu 16):
#### Amazon Linux, 8 threads:
 - `Linux ip-172-31-10-20 4.9.85-38.58.amzn1.x86_64 #1 SMP Wed Mar 14 01:17:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - mris_sphere lh: 67
 - mris_sphere rh: 169
 - mris_register lh: 5
 - mris_register rh: 56
#### Ubuntu 16, 8 threads:
 - `Linux ip-172-31-61-33 4.4.0-1057-aws #66-Ubuntu SMP Thu May 3 12:49:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - mris_sphere lh: 866
 - mris_sphere rh: 1366
 - mris_register lh: 892
 - mris_register rh: 1219
#### Ubuntu 14, 8 threads:
 - `Linux ip-172-31-78-211 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - mris_sphere lh: 67
 - mris_sphere rh: 169
 - mris_register lh: 5
 - mris_register rh: 56
---
#### Ubuntu 16, 1 thread:
 - `Linux ip-172-31-61-33 4.4.0-1057-aws #66-Ubuntu SMP Thu May 3 12:49:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - mris_sphere lh: 810
 - mris_sphere rh: 1368
 - mris_register lh: 1016
 - mris_register rh: 1157
#### Ubuntu 14, 1 thread:
 - `Linux ip-172-31-78-211 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - mris_sphere lh: 115
 - mris_sphere rh: 37
 - mris_register lh: 129
 - mris_register rh: 47
---
- For the 8 threaded runs, the Ubuntu 16 (kernel `4.4.0`) environment gave differing results than the other 2 environments (Amazon Linux with kernel `4.9.85` and Ubuntu 14 with kernel `3.13.0`
- When the # of negative triangles start high, the number of iterations seems to reach a maximum, then stop even when there are still 100s of negative at the end.  For example, the Ubuntu 16, 8 thread case has this: 
```
...
1228: dt=0.0273, 561 negative triangle
1229: 562 negative triangles
writing spherical brain to lh.sphere
spherical transformation took 0.2047 hours
...
```
while the Ubuntu 14, 8 thread case has:
```
...
177: dt=0.9900, 4 negative triangles
writing spherical brain to lh.sphere
spherical transformation took 0.0868 hours
...
```
- The single threaded runs give different results than the 8 threaded run on the same host.
- The above numbers are reproducible within the same environment/number of threads setup.

## Expected behavior
- `OMP_NUM_THREADS` should not have an effect on the results
- Should number of negative triangles be similar regardless of running environment?

## How to replicate the behavior
I can send the subject I used to investigate this issue by email. I can also send inputs to the command where the issue is found:
`mris_sphere -seed 1234 ?h.inflated ?h.sphere`
I was able to replicate the issue in 2 subjects (which have good input)

## Details
When investigating this issue, it seems that everything up to and including the `mris_fix_topology` step are the same between different environments. So the `Make White Surf`, `Smooth2` or `Inflation2` steps of `recon-all` could be introducing a difference

**Comment by ltirrell** [comment]
Note that these results used `samseg` instead of `aseg` to initialize surfs. It appears there are differences in `samseg` results based on `OMP_NUM_THREADS`:
- `ubuntu14_8threads_samseg == ubuntu16_8threads_samseg`
- `ubuntu14_1threads_samseg == ubuntu16_1threads_samseg`
- `ubuntu16_8threads_samseg != ubuntu16_1threads_samseg`

Thus, the thread based differences in `mris_sphere` etc described here are most likely due to differences in input to the surface processing stream. Will follow up regarding samseg separately.

**Comment by emtpgeek** [comment]
I have started looking at this

**Comment by ltirrell** [comment]
This issue appears to be related to running CorticoMetrics' FreeSurfer-based workflows within a Docker container, and not directly related to FS itself, so I will close this issue.

For some more details, it is recommended to use Docker volumes for the paths where FS writes to (such as mounting the `SUBJECTS_DIR` at runtime with `docker run -v /path/to/host/subjects_dir:/path/to/docker/subject_dir` or using `VOLUME $SUBJECTS_DIR` within the Dockerfile when building the container). This resolves the above issue.

Some steps within `recon-all` (such as `mris_fix_topology` and `mris_remove_intersections`) write output to the same filename as the input (e.g. `mris_remove_intersection ../surf/rh.orig ../surf/rh.orig`), and there is instability where the wrong output file is captured in certain configurations when Docker volumes are not used. The large number of negative triangles appears to be due to this, where the `?h.orig.nofix` is used as input to `mris_make_surfaces` instead of a version that has passed through the Fix Topology steps
```
?h.orig.nofix 
    -- cp --> ?h.orig  
    # in incorrect configurations, this cp'd file is used for input to mris_make_surfaces
        -- mris_fix_topology --> ?h.orig 
            -- mris_remove_intersections --> ?h.orig
                -- mris_make_surfaces --> ?h.white
```
