### ISSUE TITLE
please inform about which path is lacking the disk space

### ISSUE THREAD

**Issue by daisyburr** [freesurfer/freesurfer#462]
### Platform details:
Running freesurfer (build-stamp.txt: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a) via fmripep1.1.2 on a singularity container version 2.4.1

### Summary
Error from log file:
CV of field change: 0.000983965
ncendef: ncid 5: No space left on device
Error outputting volume: possibly disk full?
nu_evaluate: crashed while running evaluate_field (termination status=139)
nu_correct: crashed while running nu_evaluate (termination status=65280)
ERROR: nu_correct
Linux ndoli.hpcc.dartmouth.edu 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-sid000499 exited with ERRORS at Thu Jul 19 17:45:37 UTC 2018

### Details
The error notes that disk space is likely full, but I have more than enough space in all the directories where output is being saved. Is it possible to have this error provide information about where the space is missing?

**Comment by buildqa** [comment]
Looks like this was followed up in the thread referenced above.   If a space underrun is happening inside a Docker container at run time, e.g., on /tmp, then I would think the container would need to be dynamically re-sized to avoid the error.

**Comment by buildqa** [comment]
Closing this given thread above has been closed.
