### ISSUE TITLE
cmake problems

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#504]
### Platform details:

- FreeSurfer version:  Development
- Operating system name and version: Fedora 27

### Summary
Packages does not match cmake directories
### Actual behavior
CMake installation does not complete
### Expected behavior
Successful build
### How to replicate the behavior
mkdir build
cd build
cmake with FS_DIR set properly
### Details
The packages tar file does not really match the new CMake build system.  For instance there is a line in FindXML2.cmake, set(XML2_DIR ${FS_PACKAGES_DIR}/xml2/2.7.7), but xml2 is not in centos6-x86_64-packages-dev.20180621.tar.gz.  The same is true for libjpeg and libtiff.  

I know that this is still under development and maybe I am doing something wrong, but I did want to raise this issue.

**Comment by ahoopes** [comment]
The new prebuilt packages tarball is stored at https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz. Right now this is only documented in cmake, but I'll update this on the developer wiki

**Comment by melrobin** [comment]
OK, this works for me...closing
