### ISSUE TITLE
mri_convert and mosaic gre dicoms

### ISSUE THREAD

**Issue by pwighton** [freesurfer/freesurfer#516]
### Platform details:

- FreeSurfer version: issue occurs using both `nmr-stable60-env` and `nmr-dev-env`
- Operating system name and version: `Linux 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

### Summary

`mri_convert` is having issues converting mosaic'd gre dicoms.

Some test data can be found [here](https://gate.nmr.mgh.harvard.edu/filedrop2/index.php?p=b8oeqt0eihj).  [dcm2niix](https://github.com/rordenlab/dcm2niix) can successfully convert the dicoms.

I'd be happy to fix this myself and submit a PR if someone can point me in the right direction.

### Actual behavior

`mri_convert` converts sample dicoms with dimensions: `128 x 104 x 1 x 4`

### Expected behavior

`mri_convert` should convert sample dicoms with dimensions: `128 x 104 x 36 x 4`

#### Get the test data
```
mkdir ~/gre-mosaic-test
cd ~/gre-mosaic-test
wget 'https://gate.nmr.mgh.harvard.edu/filedrop2/index.php?p=b8oeqt0eihj' -O gre-mosaic-dicoms.tar.gz
tar zxvf ./gre-mosaic-dicoms.tar.gz
```

#### Convert with `mri_convert`
```
mri_convert -i ./gre-mosiac-dicoms/MR.1.3.12.2.1107.5.2.19.45407.2018090314553098105526633 -o gre-mosaic-mri_convert.nii.gz
```

#### Convert with `dcm2niix`
```
wget https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20180622/dcm2niix_27-Jun-2018_lnx.zip
unzip ./dcm2niix_27-Jun-2018_lnx.zip
./dcm2niix ./gre-mosiac-dicoms/MR.1.3.12.2.1107.5.2.19.45407.2018090314553098105526633 ./
```

**Comment by pwighton** [comment]
Update: conversion works when using `NSLICES_OVERRIDE`:
```
NSLICES_OVERRIDE=36 mri_convert -i ./gre-mosiac-dicoms/MR.1.3.12.2.1107.5.2.19.45407.2018090314552215447026080 -o ./gre-mosaic-mri_convert-sdcm-ismosaic-override.nii.gz
```

So the problem seems to be with how `sdfi->VolDim[2]` is being populated in `DICOMRead.c` (i.e. see [here](https://github.com/freesurfer/freesurfer/blob/2a7c92b23bdfc5b06d58f3cf5093c806a367b5cb/utils/DICOMRead.c#L208))

Will keep digging..

**Comment by neurolabusc** [comment]
@pwighton dcm2niix can derive the number of slices in a mosaic from two places: explicitly from a private DICOM tag (0019,100A, US) or the private [CSA Image Header Info](https://nipy.org/nibabel/dicom/siemens_csa.html) (0029,1010, OB: `NumberOfImagesInMosaic`). If both are missing and the Image Type (0008,0008, CS) tag includes the text `Mosaic` and the image is not interpolated, dcm2niix will guess the number of slices in the mosaic based on the  image dimensions and the number of phase encoding lines. This guess makes strong assumptions, and will not remove empty cells from the mosaic (e.g. any mosaic with 31..36 slices will be assumed to have 36), and assumes the number of reconstructed columns and rows for each slice are equal (square, not rectangular).

Your sample dataset is no longer available for download. In my experience, this situation reflects an image where the CSA header has been stripped. No tool will be able to infer details like slice timing, gradient direction, etc. My advice would be to update the anonymization tool that removed these crucial tags.

In brief, I suspect this reflects a limitation of your impoverished DICOM data. I would not describe this as a bug in mri_convert.

**Comment by pwighton** [comment]
Thanks @neurolabusc!

I can confirm the DICOM tag `0019,100A` is `36`.  I was about to re-upload the data, but decided to test the latest version of `mri_convert` first and... it works!

So some change in the past 3 years has solved this problem.
