### ISSUE TITLE
memory overflow with threads (Bevin?)

### ISSUE THREAD

**Issue by m-reuter** [freesurfer/freesurfer#525]
### Platform details:

- FreeSurfer version: 6.0 and dev
- Operating system name and version: Centos7 (probably others)

### Summary

_MAX_FS_THREADS is used to allocate vectors (e.g. mrisurf.c in MRIScomputeTriangleProperties_new)
around lines 12027  and 12183

If more threads are available, code will write to un-allocated space. Also code will free unallocated space later resulting in seg fault. 

### Actual behavior

seg fault

### Expected behavior

Fix: 
set max_threads to _MAX_FS_THREADS if it is larger will fix this.  This fix needs to be applied probably in many places not just MRIScomputeTriangleProperties_new. 

### How to replicate the behavior
This can be replicated by running e.g. mris_volmask for the ribbon construction (see recon all) without previously limiting number of threads on a large mulit-core machine. (I had >140 threads)

### Details

This will fail if max_threads is > _MAX_FS_THREADS which can happen on large servers.
Fix add:

if (max_threads > _MAX_FS_THREADS)
  max_threads =_MAX_FS_THREADS

  VECTOR *v_a[_MAX_FS_THREADS], *v_b[_MAX_FS_THREADS], *v_n[_MAX_FS_THREADS];

  int tno;
  for (tno = 0; tno < max_threads; tno++) {
    v_a[tno] = VectorAlloc(3, MATRIX_REAL);
    v_b[tno] = VectorAlloc(3, MATRIX_REAL);
    v_n[tno] = VectorAlloc(3, MATRIX_REAL); /* normal vector */
  }

...

  for (tno = 0; tno < max_threads; tno++) {
    VectorFree(&v_a[tno]);
    VectorFree(&v_b[tno]);
    VectorFree(&v_n[tno]);
  }

**Comment by emtpgeek** [comment]
_MAX_FS_THREADS is assumed by about 20 places to be a bound on the value returned by omp_get_thread_num and omp_get_max_threads.   It is set to 128.   This assumption is not checked anywhere.

Merely raising it to say 4096 and recompiling would potentially introduce another problem - there are about 20 places where this number is used to provide the bounds for stack variables.  But some threading systems have limits on the size of stacks, and this could exceed the limit.

So, as a workaround, set OMP_NUM_THREADS to 128 or less before running on these systems.   Given the way the Freesurfer code uses memory, it is unlikely that there is any performance win from using more than about 16 threads - using more than 128 will probably slow the application down, not speed it up.

Indeed try measuring with 8 and 16 threads on a such a system, and see if there really is any gain from the higher numbers.

I will investigation getting rid of the 128 limitation, but the above should get you moving again immediately.

**Comment by m-reuter** [comment]
Thanks, I think we don't need to increase MAX_FS_THREADS. Rather my suggestion (see above) is to limit the number of max_threads in the code and thus overwrite OMP_NUM_THREADS with whatever is in MAX_FS_THREADS in case someone asks for more (on purpose or by accident). 

if (max_threads > _MAX_FS_THREADS)
   max_threads =_MAX_FS_THREADS

will fix the memory overflow and segfault.

Alternatively, we can exit gracefully with a message that they should set OMP_NUM_THREADS to a lower number as that many threads will decrease performance (because I assume no one actually wants that may threads, but uses a default setting on a server by accident).

**Comment by emtpgeek** [comment]
I think this will fix your problem...

/Bevin
