### ISSUE TITLE
The documentation on getting the third party packages is out of date...

### ISSUE THREAD

**Issue by emtpgeek** [freesurfer/freesurfer#543]
https://surfer.nmr.mgh.harvard.edu/fswiki/freesurfer_linux_developers_page

It says
$> cd ~
$> wget ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz
$> tar -xzvf centos6-x86_64-packages.tar.gz
$> ./centos6-x86_64-packages/setup.sh

but there is no such directory as pub/dist/fs_supportlibs/prebuilt/centos6_x86_64

wget ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz
--2018-09-29 11:26:52--  ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz
           => ‘centos6-x86_64-packages.tar.gz’
Resolving surfer.nmr.mgh.harvard.edu (surfer.nmr.mgh.harvard.edu)... 132.183.240.105
Connecting to surfer.nmr.mgh.harvard.edu (surfer.nmr.mgh.harvard.edu)|132.183.240.105|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/dist/fs_supportlibs/prebuilt/centos6_x86_64 ... 
No such directory ‘pub/dist/fs_supportlibs/prebuilt/centos6_x86_64

**Comment by buildqa** [comment]
Please see the new documentation on the cmake build, which includes how to run a script to build your own local copies of the libraries, https://surfer.nmr.mgh.harvard.edu/fswiki/CMakePort
If the build_packages script does not build everything, you can try using this prebuilt archive of the 3rd party packages, http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/

**Comment by buildqa** [comment]
I am told there is a option to cmake, i.e., something like -DMINIMAL:BOOL=ON, that will build/install a minimal version of FS sans graphics libs (or being able to run freeview).   If you want to do it piecemeal, you can always do --no-<package> options per package I believe.

**Comment by buildqa** [comment]
Closing for now, but we can re-open if you still have an issue.

**Comment by emtpgeek** [comment]
Sadly I still have three issues

(1) is minor - I think one needs to get various files from the annex before doing the build
    cd packages
    find . -type l -exec git annex get {} \;

(2) is a bad compiler switch - ./source/build_kwwidgets.sh explicitly specifies "-mmacosx-version-min=10.8", but this is not acceptable to ubuntu 16's /usr/bin/c++.  I had to delete this by hand.

(3) is a show-stopper.  I am getting various problems with the tcl 8.6 on my system, and I don't know which obsolete version of tcl I need to revert to.  This shows in two ways...

/home/rheticus/freesurfer-packages/vtk/5.10.1/src/vtk-v5.10.1/Common/vtkTclUtil.cxx:16:
            /home/rheticus/freesurfer-packages/vtk/5.10.1/src/vtk-v5.10.1/Common/vtkTclUtil.cxx: In function \u2018void vtkTclVoidFunc(void*)\u2019:
            /home/rheticus/freesurfer-packages/vtk/5.10.1/src/vtk-v5.10.1/Common/vtkTclUtil.cxx:493:66: error: \u2018Tcl_Interp {aka struct Tcl_Interp}\u2019 has no member named \u2018errorLine\u2019
                                          " at line number " << arg2->interp->errorLine);

and perhaps it is the cause of 

        [ 27%] Building CXX object CMakeFiles/KWWidgets.dir/vtkKWCheckButtonTcl.cxx.o
        In file included from /home/rheticus/freesurfer-packages/kwwidgets/CVS/src/KWWidgets-HEAD-cvs/vtkKWObject.h:28:0,
                         from /home/rheticus/freesurfer-packages/kwwidgets/CVS/src/KWWidgets-HEAD-cvs/vtkKWApplication.h:23,
                         from /home/rheticus/freesurfer-packages/kwwidgets/CVS/src/KWWidgets-HEAD-cvs/vtkKWApplicationTcl.cxx:6:
        /home/rheticus/freesurfer-packages/vtk/5.10.1/src/vtk-v5.10.1/Common/vtkTcl.h:26:17: fatal error: tcl.h: No such file or directory
        compilation terminated.
