### ISSUE TITLE
Bug in command line argument processing for -FLAIR option

### ISSUE THREAD

**Issue by Pavel-IO** [freesurfer/freesurfer#554]
Hi all, I think I find bug in current nightly build introduced before 2 months.

Issue:
In commit https://github.com/freesurfer/freesurfer/commit/cca4ae7cf38106659b269092c5dc2011da755258#diff-c103785e528beb242d36ca3e03b546a4R5738 were introduced (in `recon-all` file) assigment `set DoT2pial = 1` in FLAIR case. Probably should be here `set DoFLAIRpial = 1`.

Consequence:
When I use `-FLAIRpial` option in cmd arguments, both  `DoT2pial` and `DoFLAIRpial ` are set to `1` and execution is termind with error message "Cannot specify both T2 and FLAIR for pial correction.".

Possibly workarounds:
Thanks to the order in the code, maybe it can help `-no_t2pial` cmd option witch sets `set DoT2pial = 0`.

**Comment by buildqa** [comment]
Hello Pavel - Waiting for developer feedback before making change you suggest, i.e., setting DoFLAIRpial=1 at line 5727 instead of DoT2pial=1

**Comment by buildqa** [comment]
This fix has been committed, so you should see the option has been changed at line 5727
