### ISSUE TITLE
OMP Compile errors

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#569]
### Platform details:
Fedora 27
- FreeSurfer version: 
- Operating system name and version:

### Summary
When building from source I get some small errors related to OpenMP support
### Actual behavior
[  5%] Building C object utils/CMakeFiles/utils.dir/romp_support.c.o
/home/melrobin/packages/freesurfer/utils/romp_support.c: In function ‘before_main’:
/home/melrobin/packages/freesurfer/utils/romp_support.c:39:5: warning: implicit declaration of function ‘omp_set_num_threads’; did you mean ‘omp_get_max_threads’? [-Wimplicit-function-declaration]
     omp_set_num_threads(_MAX_FS_THREADS);
     ^~~~~~~~~~~~~~~~~~~
     omp_get_max_threads
/home/melrobin/packages/freesurfer/utils/romp_support.c: At top level:
/home/melrobin/packages/freesurfer/utils/romp_support.c:42:5: error: redefinition of ‘romp_omp_get_thread_num’
 int romp_omp_get_thread_num()  {

### Expected behavior
Clean compile
### How to replicate the behavior
Use CMake build tools for FreeSurfer
### Details
Some small redefinition problems come from somewhere.
Please put URL to code or code here (if not too long).

**Comment by buildqa** [comment]
Hello, 

I can't seem to reproduce when building from the current dev tree on CentOS7 with gcc 4.8.5,

utils $ rm CMakeFiles/utils.dir/romp_support.c.o

utils]$ make VERBOSE=1 romp_support.o
cd /home/osboxes/git/freesurfer && make -f utils/CMakeFiles/utils.dir/build.make utils/CMakeFiles/utils.dir/romp_support.c.o
make[1]: Entering directory `/home/osboxes/git/freesurfer'
Building C object utils/CMakeFiles/utils.dir/romp_support.c.o
cd /home/osboxes/git/freesurfer/utils && /usr/bin/gcc -DANSI -DHAVE_GLUT_LIBS -DHAVE_ITK_LIBS -DHAVE_OPENGL -DHAVE_OPENMP -DHAVE_ZLIB -DLinux -DTEEM_32BIT=0 -DTEEM_DIO=0 -DTEEM_ENDIAN=1234 -DTEEM_QNANHIBIT=1 -DUSE_LOCAL_MINC -DUSE_SSE_MATHFUN -I/home/osboxes/git/freesurfer -I/home/osboxes/git/freesurfer/include -I/home/osboxes/git/freesurfer/minc_1_5_1 -I/home/osboxes/git/freesurfer/netcdf_3_6_0_p1 -I/home/osboxes/git/freesurfer/include/dicom -I/home/osboxes/git/freesurfer/include/NrrdIO -I/home/osboxes/git/packages/xml2/2.7.7/include/libxml2 -I/home/osboxes/git/packages/jpeg/6b/include -I/home/osboxes/git/packages/tiff/3.6.1/include -I/home/osboxes/git/packages/glut/3.7/include/GL -I/home/osboxes/git/packages/expat/2.0.1/include -I/home/osboxes/git/packages/itk/4.13.0/include/ITK-4.13 -I/home/osboxes/git/packages/itk/4.13.0/include  -fopenmp    -Wall -Wno-unused-result -Wno-unused-local-typedefs -Wno-unused-but-set-variable -msse2 -mfpmath=sse -m64 -fdata-sections -ffunction-sections -Wl,--gc-sections -O2 -DNDEBUG   -o CMakeFiles/utils.dir/romp_support.c.o   -c /home/osboxes/git/freesurfer/utils/romp_support.c
make[1]: Leaving directory `/home/osboxes/git/freesurfer'
utils]$

**Comment by melrobin** [comment]
I want to try your method, but am unsure what directories you are in.  For instance I do not have a utils.dir directory and it appears that at some point you are in a utils directory.

Can you share your structure or tell me where you are invoking make?

**Comment by buildqa** [comment]
If you have not used the cmake build, then please give it a try - which is what I used.  In addition to the wiki page, https://surfer.nmr.mgh.harvard.edu/fswiki/CMake, I am attaching a script (makefile) that will attempt to run a cmake command for you in the ./freesurfer tree, and then do the build, etc.   I have used it with CentOS 6, 7, Ubuntu 16, 18, and MacOS.  It is still a work in progress, but it could help you get started with the cmake build.  Just read the top of the file or type "make" or "make help".  I could only attach it as a file with an extension, i.e., 
[makefile_melrobin.txt](https://github.com/freesurfer/freesurfer/files/2578470/makefile_melrobin.txt)
 (makefile_melrobin.txt), so you should rename it to makefile, Makefile, etc.

**Comment by melrobin** [comment]
I can reproduce the error with this command:
gcc -c -I../include romp_support.c

Here is the resulting error:
[melrobin@scorpion utils]$ gcc -c -I../include romp_support.c
romp_support.c: In function ‘before_main’:
romp_support.c:39:5: warning: implicit declaration of function ‘omp_set_num_threads’; did you mean ‘omp_get_max_threads’? [-Wimplicit-function-declaration]
     omp_set_num_threads(_MAX_FS_THREADS);
     ^~~~~~~~~~~~~~~~~~~
     omp_get_max_threads
romp_support.c: At top level:
romp_support.c:42:5: error: redefinition of ‘romp_omp_get_thread_num’
 int romp_omp_get_thread_num()  {
     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from romp_support.c:26:0:
../include/romp_support.h:43:28: note: previous definition of ‘romp_omp_get_thread_num’ was here
 #define omp_get_thread_num romp_omp_get_thread_num

**Comment by melrobin** [comment]
I'm going to close this while I work on more compiler flags for OpenMP.
