### ISSUE TITLE
Suggestion: be flexible about temp space location

### ISSUE THREAD

**Issue by baxpr** [freesurfer/freesurfer#580]
### Platform details:

Containers, e.g. docker/singularity

- FreeSurfer version: dev, git tag nightly_20180822 and probably others
- Operating system name and version: Centos7

### Summary
Temp storage location is hardcoded to be /dev/shm in at least one place:
scripts/mri_nu_correct.mni line 92
And I think also other places because changing this section of code didn't fix the issue.

### Actual behavior
Default /dev/shm space is insufficient for freesurfer's needs and recon-all fails.

### How to replicate the behavior
Run in a container with small /dev/shm space, e.g. 64MB which is docker's default.

### Details
Some parts of Freesurfer are hardcoded to always use /dev/shm when it exists. If /dev/shm is too small, e.g. recon-all will fail. This hardly seems critical because I have found a workaround for my case: set /dev/shm allocation to be larger e.g. 3GB in my docker container. But, a robust solution would be to allow user to specify what temp dir should be used instead of forcing /dev/shm.

Please put URL to code or code here (if not too long).
https://github.com/freesurfer/freesurfer/blob/dev/scripts/mri_nu_correct.mni
Line 92

**Comment by baxpr** [comment]
By the way - a too-small /dev/shm yields this error message, which was pretty hard for me to parse:

evaluate_field: posixio.c:210: px_pgin: Assertion `*posp == ((off_t)(-1)) || *posp == lseek(nciop->fd, 0, 1)' failed.
nu_evaluate: crashed while running evaluate_field (termination status=6)
nu_correct: crashed while running nu_evaluate (termination status=65280)
ERROR: nu_correct

**Comment by buildqa** [comment]
Hello,

II don't know if the existing docker resources available on github have solved the issue(s) mentioned above, but you could take a look, https://github.com/corticometrics/fs6-cloud

This thread may also be interesting,
https://github.com/freesurfer/freesurfer/issues/70#issuecomment-316361886

**Comment by ahoopes** [comment]
This should be fixed by https://github.com/freesurfer/freesurfer/commit/53128205ab6ea9c2124709b1f131d2e6f33ebf15. `mri_nu_correct.mni` now checks the size of `/dev/shm` before using it as a temporary dir.
