### ISSUE TITLE
Error in manual: resample cortical parcellation to the natrive space

### ISSUE THREAD

**Issue by YerongLi** [freesurfer/freesurfer#605]
Hi all:

 I found that the tutorial on sampling surface to naive space does not work: "https://surfer.nmr.mgh.harvard.edu/fswiki/FsAnat-to-NativeAnat"

I have got an error like this:
```
~/Documents/100206/T1w/100206/surf$ mri_surf2surf --sval-xyz pial --reg ../mri/register.native.dat ../mri/rawavg.mgz --tval pial.native --tval-xyz --hemi lh --s 1158119_3_6
Reading header for ../mri/rawavg.mgz
ERROR: --tval-xyz flag needs 1 argument
   FYI: --tval-xyz now requires a volume. See --help
```
Anyone knows how to fix this?

Yerong

**Comment by ahoopes** [comment]
Hi Yerong, please post this type of processing question to the freesurfer mailing list. Information on subscribing to the list can be found [here](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport). Thanks!
