### ISSUE TITLE
build_packages.py does not build enough of mnic

### ISSUE THREAD

**Issue by emtpgeek** [freesurfer/freesurfer#608]
### Platform details: x64
- FreeSurfer version: dev 
- Operating system name and version: ubuntu 16.04 

### Summary
The minc directory built by build_packages.py does not contain many of the utilities in the centos packages, including some that are needed by recon-all such as nu_correct

### Actual behavior
It creates
        ~/freesurfer-packages/minc/1.5/bin/
            dcm2mnc           mincconcat  mincextract  mincmakescalar      mincresample  mincview    transformtags  xfminvert
            ecattominc        minccopy    mincheader   mincmakevector      mincreshape   mincwindow  upet2mnc
            invert_raw_image  mincdiff    minchistory  mincmath            mincstats     mnc2nii     voxeltoworld
            mincaverage       mincedit    mincinfo     minc_modify_header  minctoecat    nii2mnc     worldtovoxel
            minccalc          mincexpand  minclookup   mincpik             minctoraw     rawtominc   xfmconcat

### Expected behavior
The expected contents are
       ~/bin/freesurfer/mni/bin
            autocrop          make_phantom   mincheader          minctoraw    nu_estimate_np_and_em   volume_cog
            check_scale       make_template  minchistory         minctracc    nu_estimate_np_and_em~  volume_hist
            correct_field     mincaverage    mincinfo            mincview     nu_evaluate             volume_stats
            crispify          mincbbox       minclookup          mincwindow   param2xfm               voxeltoworld
            dcm2mnc           mincblur       mincmakescalar      mnc2nii      rand_param              worldtovoxel
            Display           minccalc       mincmakevector      mritoself    rawtominc               xcorr_vol
            ecattominc        mincchamfer    mincmath            mritotal     register                xfm2param
            evaluate_field    mincconcat     minc_modify_header  mritotal~    resample_labels         xfmconcat
            extracttag        minccopy       mincpik             ncdump       sharpen_hist            xfminvert
            field2imp         mincdiff       mincresample        ncgen        sharpen_volume          xfmtool
            imp2field         mincedit       mincreshape         nii2mnc      spline_smooth           zscore_vol
            invert_raw_image  mincexpand     mincstats           nu_correct   transformtags
            make_model        mincextract    minctoecat          nu_estimate  upet2mnc

### How to replicate the behavior
Build the packages using build_packages.py
Use the resulting packages to run recon-all

### Details
recon-all very soon crashes because nu_correct not found

**Comment by ahoopes** [comment]
As of 45a75d7bd3e6b807e8f9cd60b61a153d1b635fc6, `nu_correct` is now longer used by default for bias correction in recon-all. Hopefully we can remove the entire mni dependency soon.
