### ISSUE TITLE
How to use CUDA 9.2?

### ISSUE THREAD

**Issue by inobrevi** [freesurfer/freesurfer#631]
Ok I see that there is post for CUDA 8.0 but still I can't find clear instruction on how to make freesurfer use  CUDA newer than 5.0.
I am using Linux 4.19.0-kali1-amd64  SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
and GTX 970.

And if there is a way to run freesurfer on current CUDA I think it would be beneficial if there was official instruction how to do it, step-by-step because I can not find one anywhere.

Thanks in advance for help

EDIT: In any case, how to use gpu acceleration on gtx 970? Installation of CUDA 5.0 (run package) after installation of newest CUDA (9.2) and supplied driver is too old for gtx 970...

**Comment by ahoopes** [comment]
Unfortunately, the only way to run freesurfer6 with CUDA 9+ is by building the distribution yourself and linking to the newer libraries. However, I don't think this has ever been done successfully, and I should also note that CUDA is no longer supported going forward (as of https://github.com/freesurfer/freesurfer/pull/624). Sorry for the troubles.
