### ISSUE TITLE
utils/mrisurf_metricProperties_fast.h - MRIS_MP uninitialized const member variables

### ISSUE THREAD

**Issue by nagaflokhu** [freesurfer/freesurfer#634]
### Platform details:

- FreeSurfer version: commit 6583c24717a92d9b5b0287766dc112256df43ed3 (dev branch - March 1st, 2019)
- Operating system name and version: macOS High Sierra Version 10.13.6 (17G65)

### Summary
When trying to compile `utils/mrisurf_metricProperties.cpp` in the context of compiling Freeview, g++-5 reports the `use of deleted function 'MRIS_MP::MRIS_MP()'`, caused by `uninitialized const member in 'struct MRIS_MP'`. Several const member variables are introduced by the use of the `MRIS_MP__LIST_MRIS_IN` macro on line 39.

Replacing the use of `MRIS_MP__LIST_MRIS_IN` on line 39 by the code I've inserted at the bottom of this issue enables successful compilation of `utils/mrisurf_metricProperties.cpp` and Freeview.

I am not making a pull request for the time being for two reasons: first, there may be a reason for using the `MRIS_MP__LIST_MRIS_IN` macro (I suspect not - it is never used anywhere else); second, there may be a reason for making the introduced variables `const`.

### Actual behavior
Compilation of Freeview fails due to compilation failure in `utils/mrisurf_metricProperties.cpp`, as explained above.

### Expected behavior
Successful compilation.

### How to replicate the behavior
`cd freeview && make`

### Details

```
int status, nvertices, nfaces, nsize;
double radius;
VERTEX_TOPOLOGY * vertices_topology;
FACE_TOPOLOGY * faces_topology;
```

**Comment by ahoopes** [comment]
This is related to our recent switch to c++. There will have to be some further refactoring of the surface utils, but 4a489efe3a08503eced9996f5d08f215aa4ead24 should fix things for now.
