### ISSUE TITLE
wishlist: FREESURFER_SEED environment variable

### ISSUE THREAD

**Issue by yarikoptic** [freesurfer/freesurfer#636]
Many commands in FreeSurfer now have `-seed` cmdline option to seed the RNG during their execution. `recon-all` has `-norandomness` which then seeds corresponding commands (more might come ;)) with `1234` as a seed.
Whenever FreeSurfer is used within larger pipelines, there might neither be an easy way to instruct `recon-all` to do `-norandomness` nor to seed it with a specific (not `1234`), consistent (across sub-tools) seed which was known (currently based on time) at the time of original computation.
To resolve that, I wondered if there is an easy way to
- make FreeSurfer's RNG, upon creation if an environment (e.g. `FREESURFER_SEED`) variable is defined - take it as a seed.

That would allow for any tool in freesurfer using RNG to be consistently (the same env var), and reproducibly (if FREESURFER_SEED is set/known) reproduce arbitrary results.

If such environment variable would get defined/used by FreeSurfer, I would be happy to add it to the list of similar environment variables in https://github.com/ReproNim/reproseed/blob/master/reproseed.sh#L23 and try on composite analysis pipelines (e.g. `fmriprep`) to see if I would get lucky to reproduce entire preprocessing even when different used tools have their own ways to set their seeds.

**Comment by ahoopes** [comment]
As of 6992bb0246bf03b0ea2ed099731043461a573a76, the `FREESURFER_SEED` variable can be used to globally seed the RNG.
