### ISSUE TITLE
trac-all - /bin/sh instead of #!/bin/bash in scripts which use bash-only syntax extensions

### ISSUE THREAD

**Issue by 0rC0** [freesurfer/freesurfer#667]
### Platform details:

- FreeSurfer version: 6.0 (and still present in commit https://github.com/freesurfer/freesurfer/commit/99e8d22f3dc8bc3c8d8f08ea65178f66d7aaeaaf)
- Operating system name and version: Ubuntu 16.04.6 "Xenial" LTS

### Summary
Issue still posted in the [mailing list](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg51085.html). Some files executed from trac-all have 
`#!/bin/sh` shebang but use bash-only syntax

### Actual behavior
Executing the scripts gives out:
`Syntax error: "(" unexpected` for:

https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/scripts/bedpostx_mgh#L131
https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/scripts/fsl_sub_mgh#L470

### How to replicate the behavior
``
#from a terminal

/bin/sh

fslver=(`cat $FSLDIR/etc/fslversion | sed 's/\./ /g'`) 

heldjobs=(`qstat -u $user | grep -w H | awk -v FS=. '{print $1}'`) 
``

### Details

I'm gonna send a pull request to correct this issue

**Comment by ahoopes** [comment]
thanks! the PR has been merged
