### ISSUE TITLE
How to generate a template and its segmentation file with multiple berts

### ISSUE THREAD

**Issue by SY51826** [freesurfer/freesurfer#673]
Hello FreeSurfer Developers,
 
I used “recon-all -all” command to make 10berts. And I would like to use these berts to generate a template and corresponding segmentationfile(such as aseg.mgz) by calculating their average. I have run the “mri_robust_template”command. But it only generated an unclear template through 5 iterations without segmentation file. Could you tell which command should I use to generate both template and corresponding segmentation file.
 
1)    FreeSurfer version: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
2)    Platform: ubuntu 18.04

Thank you very much for your kind consideration and I am looking forward to your reply.

Yours sincerely,
Yu Sun

**Comment by ahoopes** [comment]
Hi Yu Sun, please post this type of processing question to the freesurfer mailing list. Information on subscribing to the list can be found [here](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport). Thanks!
