### ISSUE TITLE
*.aparc.stats file bug in # Measure text

### ISSUE THREAD

**Issue by dbkeator** [freesurfer/freesurfer#675]
### Platform details:

- FreeSurfer version: 6.0
- Operating system name and version: Linux, x86_64

### Summary
All the aparc.stats files have a missing comma in the # Measure row for Cortex:
"# Measure Cortex, CortexVol Total cortical gray matter volume, 390925.975594, mm^3"

### Expected behavior
"# Measure Cortex, CortexVol, Total cortical gray matter volume, 390925.975594, mm^3"
### How to replicate the behavior
recon-all
### Details

Please put URL to code or code here (if not too long).

**Comment by ahoopes** [comment]
Closing as this has been fixed in dev by https://github.com/freesurfer/freesurfer/commit/ef5c54e9c6d04003a8206790ef6ee77cafc5cf01
