### ISSUE TITLE
freesurfer recon-all requirements

### ISSUE THREAD

**Issue by satra** [freesurfer/freesurfer#68]
on a base ubuntu system, freesurfer requires `tcsh`, `libgomp1`, and `bc` to be installed for `recon-all` to run, but this is not stated anywhere in the install docs.

i don't know if there are other things required, but after installing the above recon-all is running. i will post if there are any more things needed or whether recon-all ran to completion.

**Comment by satra** [comment]
MCR for brainstem segmentation also requires: `libxt6`, `libxmu6`

**Comment by zkaufman** [comment]
@satra May I ask how you came up with that list? I've setup freesurfer on freshly installed Ubunutu laptops hundreds of times (for the freesurfer course) and the only packages Ive had to install on top of the base system was `tcsh` and `csh` (and `libjpeg62` for freeview).

**Comment by satra** [comment]
ubuntu desktops are different from minimal ubuntu systems. but that being said i mistakenly stated base ubuntu, when the system was actually: `debian:8.5`

if you create a docker container `docker run -it --rm -v external_freesurfer:/freesurfer debian:8.5` and try to run recon-all, you'll notice that these libraries are missing.

so i just ran, installed, ran, till i was able to run both the standard recon-all and the MCR bits.

**Comment by satra** [comment]
this was the actual container i used, which already has a few other things over the base system: https://hub.docker.com/r/continuumio/miniconda/~/dockerfile/

**Comment by zkaufman** [comment]
@satra Got it. Thanks. Centos and Ubuntu systems are our primary testing platforms. Ill try out a fresh install on a Debian 8 system, verify the requirements you state above, and make note of that on the download page.

**Comment by zkaufman** [comment]
After MANY frustrating hours trying to install both Debian 8.5 and 8.8 on an older Dell Precision and newer Dell Inspiron laptops, and failing, I am giving up and closing this issue. I am happy verify and list requirements for "base" installations of various  linux distributions, but I cant concern myself keeping an up-to-date list of requirements for all possible docker installations.

**Comment by satra** [comment]
@zkaufman - i'm sorry you ran into installation issues. however, this is not just a docker issue. the [installation page](http://freesurfer.net/fswiki/DownloadAndInstall) of freesurfer states under requirements:

`Operating System: Linux, macOS`, and that's simply not true. perhaps in general these requirements need to be updated/clarified.

the point here is that when someone wants to run freesurfer on a base linux install that is not a desktop install, they will run into issues. there are many instances where we install freesurfer simply to run recon-all on some remote compute node, without any requirements for interactive displays. these systems tend to be fairly simple, and hence other dependencies outside of the tarball become relevant. 

from a linux perspective, it would be good to list the set of required base packages for the tarball. and you don't have to go across software, you could list them just for centos 7.x for example.

**Comment by zkaufman** [comment]
@satra I am able to run full recons on the centos7 base system out-of-the-box. So would the required packages you seek be the packages required to be installed on top of the minimal ISO?

**Comment by satra** [comment]
@zkaufman - exactly, that would be good. since many servers are minimized by default.

**Comment by zkaufman** [comment]
Got it. I guess I was looking at it from the opposite end, thinking most academic environments (like the NMR) have base systems plus many add on modules. In my personal experience, I rarely come across minimized installations on server/compute nodes, but I guess that makes sense. Ok, I'll take a look at these minimal distros and come up with the required package list. Should be easy enough.

**Comment by zkaufman** [comment]
@satra I have been performing recons with the minimal centos7 installation and only need 'tcsh' 'bc' and 'perl'. I would do the same test with ubuntu but their are many variants, and it doesn't seem worth the effort. Lastly, and very frustratingly, I am completely unable to install debian on a modern laptop. 

I am fairly certain these library requirements you mention above exist only in the world of docker containers and not actual linux distributions that exist as OSes on ones laptop or desktop. Although I would like to test debian as further evidence of this.
