### ISSUE TITLE
Windows Carriage Return causes  "subscript out of range"  error in trac-all preproc

### ISSUE THREAD

**Issue by 0rC0** [freesurfer/freesurfer#691]
- FreeSurfer version: 6.0
- Operating system name and version: Ubuntu 16.04.6 LTS

### Summary

Windows Carriage Return characters in BVALs and BVECs cause `trac-all preproc` fail with error `Subscript out of range`.

The error was described sometimes in the [mailing list](https://www.mail-archive.com/search?l=freesurfer%40nmr.mgh.harvard.edu&q=+%22subscript+out+of+range%22++%22trac-all%22&a=1).

The problem should be in [trac-preproc](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/scripts/trac-preproc#269) . It causes some empty cells in the arrays.

A workaround is using [dos2unix](http://dos2unix.sourceforge.net/) with the BVALs and BVECs and merging them with `cat <bvals_dti_9b0> <bvals_dti_64dir> > <bval.txt>`.

### How to replicate the behavior

See files in attachment

### Details
[MCI015.dti_bval.txt](https://github.com/freesurfer/freesurfer/files/3406153/MCI015.dti_bval.txt)
[MCI015.dti_bval_d2u.txt](https://github.com/freesurfer/freesurfer/files/3406154/MCI015.dti_bval_d2u.txt)
[MCI015.dti_bvec.txt](https://github.com/freesurfer/freesurfer/files/3406155/MCI015.dti_bvec.txt)
[trac-preproc_log_subscript_error.txt](https://github.com/freesurfer/freesurfer/files/3406176/trac-preproc_log_subscript_error.txt)

**Comment by ahoopes** [comment]
@ayendiki I'm guessing the easiest way to account for carriage returns is to remove them during the original bvec/bval file caching. @0rC0 in your local install do you mind replacing [line 220](https://github.com/freesurfer/freesurfer/blob/stable6/scripts/trac-preproc#L220) in `trac-preproc` with:

```bash
    set cmd = (tr -d '\r' < $bvecfile > $dwidir/dwi_orig.bvecs)
```
and [line 238](https://github.com/freesurfer/freesurfer/blob/stable6/scripts/trac-preproc#L238) with:

```bash
    set cmd = (tr -d '\r' < $bvalfile > $dwidir/dwi_orig.bvals)
```

and letting us know if that fixes things?

**Comment by 0rC0** [comment]
> @0rC0 in your local install do you mind replacing [line 220](https://github.com/freesurfer/freesurfer/blob/stable6/scripts/trac-preproc#L220) in `trac-preproc` with:
> 
> ```shell
>     set cmd = (tr -d '\r' < $bvecfile > $dwidir/dwi_orig.bvecs)
> ```
> 
> and [line 238](https://github.com/freesurfer/freesurfer/blob/stable6/scripts/trac-preproc#L238) with:
> 
> ```shell
>     set cmd = (tr -d '\r' < $bvalfile > $dwidir/dwi_orig.bvals)
> ```
> 
> and letting us know if that fixes things?

Thank you for the suggestion. Unfortunately it doesn't work, I receive the error:

` tr: extra operand ‘<’` 

It can have to do with the parsing from `tcsh`  ([see here i.e.),](https://stackoverflow.com/questions/33665206/set-a-csh-command-with-options-within), the command is echoed ([line 239](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/scripts/trac-preproc#239)) as:

` < /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/data_MCI/MCI015.dti_bvec.txt > /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/dmri/dwi_orig.bvecs` 

full log:
```
INFO: SUBJECTS_DIR is /media/NFSr_work/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI

INFO: Diffusion root is /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI

Actual FREESURFER_HOME /media/NFSr_work/home/katharina/software/freesurfer

INFO: FreeSurfer build stamps do not match

Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0

Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c

INFO: current FREESURFER_HOME does not match that of previous processing.

    Current: /home/katharina/software/freesurfer

    Previous: /usr/local/freesurfer-5.3

trac-preproc -c /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/scripts/dmrirc.local -log /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/scripts/trac-all.log -cmd /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/scripts/trac-all.cmd -no-isrunning

#-------------------------------------

/home/katharina/software/freesurfer/bin/trac-preproc

#-------------------------------------

#@# Image corrections Fri Jul 19 12:08:10 CEST 2019

mri_convert --bvec-voxel /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/data_MCI/MCI015.dti.nii /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/dmri/dwi_orig.nii.gz

mri_convert.bin --bvec-voxel /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/data_MCI/MCI015.dti.nii /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/dmri/dwi_orig.nii.gz

$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $

reading from /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/data_MCI/MCI015.dti.nii...

TR=7530.00, TE=0.00, TI=0.00, flip angle=0.00

i_ras = (-0.937818, -0.336383, -0.0856941)

j_ras = (-0.347027, 0.902607, 0.254703)

k_ras = (0.00832972, -0.268604, 0.963215)

writing to /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/dmri/dwi_orig.nii.gz...

< /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/data_MCI/MCI015.dti_bvec.txt > /home/WorkFlowTemp/SMARTAGE/2019_DTI/TRACULA/01_input/recon_all_MCI/MCI015/dmri/dwi_orig.bvecs

tr: extra operand ‘<’

Try 'tr --help' for more information.

Linux doc2 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ahoopes** [comment]
Oh right, the redirection won't get handled correctly if run from a variable. I just committed [a fix](https://github.com/freesurfer/freesurfer/commit/bed3e25a5777d1b09dcec8a8b9b6701a6cf31d2c) to the dev branch, but since I don't have data to test this properly, you'll have to let me know how it works. You can update the script via:

```
curl https://raw.githubusercontent.com/freesurfer/freesurfer/dev/scripts/trac-preproc -o $FREESURFER_HOME/bin/trac-preproc
```

**Comment by buildqa** [comment]
Some people do the following to convert large number of files in a subdirectory,
$ find . -type f -print0 | xargs -0 -n 1 -P 4 dos2unix 
Also as part of the git workflow for files committed,
$ git ls-files | xargs dos2unix

**Comment by 0rC0** [comment]
> Oh right, the redirection won't get handled correctly if run from a variable. I just committed [a fix](https://github.com/freesurfer/freesurfer/commit/bed3e25a5777d1b09dcec8a8b9b6701a6cf31d2c) to the dev branch, but since I don't have data to test this properly, you'll have to let me know how it works. You can update the script via:
> 
> ```
> curl https://raw.githubusercontent.com/freesurfer/freesurfer/dev/scripts/trac-preproc -o $FREESURFER_HOME/bin/trac-preproc
> ```

it works!
