### ISSUE TITLE
dev_nightly_tests  build error on Mac 10.14.6

### ISSUE THREAD

**Issue by zuooonz** [freesurfer/freesurfer#698]
### Platform details:

- FreeSurfer version: dev_nightly_tests
- Operating system name and version: Mac 10.14.6

### cmake:
```
brew install cmake armadillo gcc5

cmake . -DBUILD_GUIS=OFF \
        -DFS_PACKAGES_DIR="/Users/z/Downloads/tmp/freesurfer_dependencies"  \
        -DCMAKE_C_COMPILER="/usr/local/bin/gcc-5"       \
        -DCMAKE_CXX_COMPILER="/usr/local/bin/g++-5"     \
        -DCMAKE_Fortran_COMPILER="/usr/local/bin/gfortran-5"
```

freesurfer_dependencies contains the [prebuilt packages](https://surfer.nmr.mgh.harvard.edu/fswiki/BuildRequirements).

Here the output:
> -- The C compiler identification is GNU 5.5.0
> -- The CXX compiler identification is GNU 5.5.0
> -- Checking whether C compiler has -isysroot
> -- Checking whether C compiler has -isysroot - yes
> -- Checking whether C compiler supports OSX deployment target flag
> -- Checking whether C compiler supports OSX deployment target flag - yes
> -- Check for working C compiler: /usr/local/bin/gcc-5
> -- Check for working C compiler: /usr/local/bin/gcc-5 -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Checking whether CXX compiler has -isysroot
> -- Checking whether CXX compiler has -isysroot - yes
> -- Checking whether CXX compiler supports OSX deployment target flag
> -- Checking whether CXX compiler supports OSX deployment target flag - yes
> -- Check for working CXX compiler: /usr/local/bin/g++-5
> -- Check for working CXX compiler: /usr/local/bin/g++-5 -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- The Fortran compiler identification is GNU 5.5.0
> -- Checking whether Fortran compiler has -isysroot
> -- Checking whether Fortran compiler has -isysroot - yes
> -- Checking whether Fortran compiler supports OSX deployment target flag
> -- Checking whether Fortran compiler supports OSX deployment target flag - yes
> -- Check for working Fortran compiler: /usr/local/bin/gfortran-5
> -- Check for working Fortran compiler: /usr/local/bin/gfortran-5  -- works
> -- Detecting Fortran compiler ABI info
> -- Detecting Fortran compiler ABI info - done
> -- Checking whether /usr/local/bin/gfortran-5 supports Fortran 90
> -- Checking whether /usr/local/bin/gfortran-5 supports Fortran 90 -- yes
> -- No build type selected - defaulting to Release
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- Found ARMADILLO: /usr/local/include  
> -- Found PETSC: /Users/z/Downloads/tmp/freesurfer_dependencies/petsc/2.3.3/include  
> -- Found ANN: /Users/z/Downloads/tmp/freesurfer_dependencies/ann/1.1.2/include  
> -- Found GTS: /Users/z/Downloads/tmp/freesurfer_dependencies/gts/0.7.6/include  
> -- Found OpenMP_C: -fopenmp  
> -- Found OpenMP_CXX: -fopenmp  
> -- Found OpenMP_Fortran: -fopenmp (found version "4.0") 
> -- Found OpenMP: TRUE (found version "4.0")  
> -- Found X11: /usr/X11/include  
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.4", minimum required is "3.5") 
> -- Found PythonLibs: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
> -- Performing Test HAS_FLTO
> -- Performing Test HAS_FLTO - Failed
> -- LTO disabled (not supported by the compiler and/or linker)
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/z/Downloads/tmp/freesurfer

### make:

> [  0%] Building C object packages/jpeg/CMakeFiles/jpeg.dir/jcapimin.c.o
> In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:69:0,
>                  from /usr/local/Cellar/gcc@5/5.5.0_3/lib/gcc/5/gcc/x86_64-apple-darwin17.7.0/5.5.0/include-fixed/stdio.h:78,
>                  from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jinclude.h:46,
>                  from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jcapimin.c:20:
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h: In function 'renameat':
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h:39:56: error: expected declaration specifiers before '__AVAILABILITY_INTERNAL__MAC_10_10'
>  int     renameat(int, const char *, int, const char *) __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
>                                                         ^
> In file included from /usr/local/Cellar/gcc@5/5.5.0_3/lib/gcc/5/gcc/x86_64-apple-darwin17.7.0/5.5.0/include-fixed/stdio.h:78:0,
>                  from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jinclude.h:46,
>                  from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jcapimin.c:20:
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:81:25: error: storage class specified for parameter 'fpos_t'
>  typedef __darwin_off_t  fpos_t;
>                          ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:139:2: error: expected specifier-qualifier-list before 'fpos_t'
>   fpos_t (* _Nullable _seek) (void *, fpos_t, int);
>   ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:157:3: error: storage class specified for parameter 'FILE'
>  } FILE;
>    ^
> In file included from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jinclude.h:46:0,
>                  from /Users/z/Downloads/tmp/freesurfer/packages/jpeg/jcapimin.c:20:
> ...

**Comment by zuooonz** [comment]
#### also tested with default clang:
```
cmake . -DBUILD_GUIS=OFF \
    -DFS_PACKAGES_DIR="/Users/z/Downloads/tmp/freesurfer_dependencies_clang" 
```

#### cmake:

> -- The C compiler identification is AppleClang 11.0.0.11000020
> -- The CXX compiler identification is AppleClang 11.0.0.11000020
> -- Check for working C compiler: /usr/bin/gcc
> -- Check for working C compiler: /usr/bin/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/g++
> -- Check for working CXX compiler: /usr/bin/g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- The Fortran compiler identification is GNU 9.2.0
> -- Checking whether Fortran compiler has -isysroot
> -- Checking whether Fortran compiler has -isysroot - yes
> -- Checking whether Fortran compiler supports OSX deployment target flag
> -- Checking whether Fortran compiler supports OSX deployment target flag - yes
> -- Check for working Fortran compiler: /usr/local/bin/gfortran
> -- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
> -- Detecting Fortran compiler ABI info
> -- Detecting Fortran compiler ABI info - done
> -- Checking whether /usr/local/bin/gfortran supports Fortran 90
> -- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
> -- No build type selected - defaulting to Release
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- Found ARMADILLO: /usr/local/include  
> -- Found PETSC: /Users/z/Downloads/tmp/freesurfer_dependencies_clang/petsc/2.3.3/include  
> -- Found ANN: /Users/z/Downloads/tmp/freesurfer_dependencies_clang/ann/1.1.2/include  
> -- Found GTS: /Users/z/Downloads/tmp/freesurfer_dependencies_clang/gts/0.7.6/include  
> -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
> -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
> -- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
> -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) (found version "4.5")
> -- Found X11: /usr/X11/include  
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.4", minimum required is "3.5") 
> -- Found PythonLibs: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
> -- Performing Test HAS_FLTO
> -- Performing Test HAS_FLTO - Success
> -- LTO enabled
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/z/Downloads/tmp/freesurfer

#### make:
> ...
> [ 26%] Building CXX object utils/CMakeFiles/utils.dir/morph.cpp.o
> [ 26%] Building CXX object utils/CMakeFiles/utils.dir/mosaic.cpp.o
> [ 26%] Building CXX object utils/CMakeFiles/utils.dir/mri.cpp.o
> /Users/z/Downloads/tmp/freesurfer/utils/mri.cpp:16609:27: error: 'sizeof (labels)' will return the size of the
>       pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
>   length = sizeof(labels) / sizeof(int);
>            ~~~~~~~~~~~~~~ ^
> 1 error generated.
> make[2]: *** [utils/CMakeFiles/utils.dir/mri.cpp.o] Error 1
> make[1]: *** [utils/CMakeFiles/utils.dir/all] Error 2
> make: *** [all] Error 2

**Comment by aboualiaa** [comment]
On  macOS you need to provide the whole gcc toolchain. The only gcc that seems to work for me is gcc-9 (I've tried gcc-5 through 8, the default apple clang and clang 9). Here's a configuration that worked at HEAD on Catalina (10.15):

- [ ]  install the latest gcc (as of 26.10.19 it is gcc-9): `brew install gcc`

---

- [ ] if the repository is at directory `freesurfer`, the prebuilt packages are at `freesurfer_dependencies`, then change **the top of the file** `freesurfer/CMakeLists.txt` to the following:

```cmake
# before starting the project, set gcc/g++ as the default compiler
# find_program(CMAKE_C_COMPILER NAMES $ENV{CC} gcc PATHS ENV PATH NO_DEFAULT_PATH)
# find_program(CMAKE_CXX_COMPILER NAMES $ENV{CXX} g++ PATHS ENV PATH NO_DEFAULT_PATH)

set(FS_PACKAGES_DIR "/path/to/freesurfer_dependencies")

set(CMAKE_Fortran_COMPILER "/usr/local/bin/x86_64-apple-darwin19-gfortran-9")
set(CMAKE_C_COMPILER "/usr/local/bin/x86_64-apple-darwin19-gcc-9")
set(CMAKE_CXX_COMPILER "/usr/local/bin/x86_64-apple-darwin19-g++-9")
set(CMAKE_AR "/usr/local/bin/x86_64-apple-darwin19-gcc-ar-9")
set(CMAKE_NM "/usr/local/bin/x86_64-apple-darwin19-gcc-nm-9")
set(CMAKE_RANLIB "/usr/local/bin/x86_64-apple-darwin19-gcc-ranlib-9")
```

Notice that the first three lines (the default behaviour) are commented. Apple aliases `gcc` and `g++` to `clang` and `clang++` for "transition purposes.

The `x86_64-apple-darwin*` binaries are installed by `brew`

---

- [ ] The next problem is the ITK package in `freesurfer_dependencies`. ITK version 4.13 does not compile with `gcc` versions greater than 8 🤦‍♂️ (I haven't tried more recent versions). So we need to change the file `freesurfer_dependencies/itk/4.13.0/include/ITK-4.13/vcl_compiler.h` at line 101:

from `#  error "Dunno about this gcc"`
to `#   define VCL_GCC_90`

obviously a hack, but it does the trick.

---

- [ ] since `gcc-9` is very recent and there is a lot of old code in freesurfer, it will emit a lot of warnings. search for the line `# warnings` in `freesurfer/CMakeLists.txt`. The next line should look like this:

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Wno-absolute-value -Wno-sign-compare -Wno-write-strings -Wno-unused-result -Wno-unused-parameter")
```

just remove the `-Werror` flag

or if you want to silence warnings all-together replace the above line with:

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -w")
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w")
```

---

### bonus tip

- [ ] If you want a faster build you could uses `ninja`. Sadly an issue that arises is that the released `ninja` doesn't support fortran, so we can't just `brew install ninja`. You'll need to build it yourself.

```shell
brew install re2c # this is a ninja dependency
brew install python3 # if you don't already have it
cd /whatever/directory/you/like
git clone -b features-for-fortran https://github.com/Kitware/ninja.git
cd ./ninja
python3 ./configure.py --bootstrap # if nothing goes wrong you now have a ninja binary
cp ./ninja /usr/local/bin # copy ninja so that cmake finds it
```

now at `freesurfer` root you can:

```shell
cmake . -G Ninja -DBUILD_GUIS=OFF
ninja
```

and ninja will parallelise the compilation process  🎉🥳.

All this is obviously a workaround, not a solution. I'm not a maintainer of this repository.

If anything doesn't work please let me know.

**Comment by zuooonz** [comment]
@aboualiaa 

Thanks for your reply.
I have abandoned. I tested with docker-freesurfer, it worked (maybe, I did not run through recon-all).
