### ISSUE TITLE
BUG: Downstream FreeSurfer surface I/O broken

### ISSUE THREAD

**Issue by larsoner** [freesurfer/freesurfer#699]
A newline appears to have been removed from `MRISwriteTriangularSurface` at some point, and this breaks downstream readers when generating things with latest `FreeSurfer`.

For example, the output of this command:
```
$ mri_watershed -useSRAS -surf ./fsaverage \
    ~/applications/freesurfer-6/subjects/fsaverage/mri/T1.mgz ws.mgz
```
On Freesurfer 6 produces a file `fsaverage_brain` that starts with:
```
ÿÿþcreated by larsoner on Tue Aug 20 13:55:57 2019

^@^@(^B^@^@P^@À^K^[SÁ<89>8:Bªñ»A<98>ü<98>...
```
And on latest Freesurfer dev starts with:
```
ÿÿþcreated by larsoner on Tue Aug 20 13:59:19 2019
^@^@(^B^@^@P^@À^DìðÁ<8c>ËúB¨<93><A<9a>;ËÂ¾¾^TB^ZÓnB<85>äÄÁ<9a>^VRB^X·WA<9c>...
```
There is a newline missing, which is problematic because downstream readers such as `nibabel` assume the procedure for reading should be [the following](https://github.com/nipy/nibabel/blob/master/nibabel/freesurfer/io.py#L172-L178):

1. Read magic
2. Read stamp
3. *dump the next line*
4. Read dimensionality
5. Read data

Because of the missing newline, on latest `freesurfer` the `fobj.readline()` dump-the-next-line step must be removed in order for the file to be read properly. This behavior should probably be reverted (?) so that downstream readers don't suffer from this problem.

I assume this change is buried somewhere in the history of `MRISwriteTriangularSurface`, but don't actually know:

https://github.com/freesurfer/freesurfer/blame/5e5b72f4871bfffe0246aed964a588b97ace65fc/utils/mrisurf_io.cpp#L5837-L5840

My best guess is that in the old code (about a year ago when it was in [mrisurf.c](https://github.com/freesurfer/freesurfer/blob/8b5ff696b2a233bc67a928fe2b07437f176c66cb/utils/mrisurf.c)?), the `current_date_time()` maybe had a newline on it?
```
  time_str = current_date_time();
  ...
  fwrite3(TRIANGLE_FILE_MAGIC_NUMBER, fp);
  fprintf(fp, "created by %s on %s\n", user, time_str);
```
This would have caused two newlines to be written before the data. But this is just speculation on my part!

**Comment by ahoopes** [comment]
You're right - the extra newline was accidentally removed as a result of the c++ refactor, and this change only got caught by external surface readers. The newline has been re-added as of 2aae19d2ff29cadb4b143e6a58ef7c75dd60de71, and any previously "broken" surface files can be correctly resaved with an updated `mris_convert` (or one from a previous stable release).
