### ISSUE TITLE
Minimized version of freesurfer 6.0.0 for recon-all

### ISSUE THREAD

**Issue by satra** [freesurfer/freesurfer#70]
i downloaded the CentOS binary from freesurfer and then followed the instructions for installing the the brainstem+hippocampal subfield segmentation bits.

i also downloaded the [studyforrest data](http://studyforrest.org/access.html) using datalad/git-annex and use the T1 and T2 images of sub-01.

#### Docker command
i'm mounting freesurfer externall into docker

```
docker run -it --rm -v /software/data/studyforrest-data-structural:/data:ro -v /software/work/opt/freesurfer:/freesurfer:ro -v /software/work/testdata:/fsdata --security-opt seccomp:unconfined continuumio/miniconda bash
```

#### Inside docker:
note that command 3 is likely to get killed without allocating sufficient memory (10G) to the docker instance. 

```
conda install -y --channel vida-nyu reprozip
apt-get -y update
apt-get -y install tcsh libgomp1 bc libxt6 libxmu6
export FREESURFER_HOME=/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh 
export SUBJECTS_DIR=/fsdata
cd /fsdata

cmd1="recon-all -s sub-01 -all -i /data/sub-01/anat/sub-01_T1w.nii.gz -T2 /data/sub-01/anat/sub-01_T2w.nii.gz -T2pial"
cmd2="recon-all -s sub-01 -brainstem-structures"
cmd3="recon-all -s sub-01 -hippocampal-subfields-T1T2 /data/sub-01/anat/sub-01_T2w.nii.gz T2 -itkthreads 4"
cmd4="asegstats2table --subjects sub-01 --segno 11 17 18 --meas mean --tablefile aseg.mean-intensity.table"
cmd5="aparcstats2table --hemi lh --subjects sub-01 --tablefile lh.aparc.area.table"

reprozip trace -d /fsdata/trace --dont-identify-packages $cmd1
reprozip trace -d /fsdata/trace --dont-identify-packages --continue $cmd2
reprozip trace -d /fsdata/trace --dont-identify-packages --continue $cmd3
reprozip trace -d /fsdata/trace --dont-identify-packages --continue $cmd4
reprozip trace -d /fsdata/trace --dont-identify-packages --continue $cmd5

cat trace/config.yml | grep '\- "/freesurfer' > fsfiles.txt
```

current output: https://www.dropbox.com/s/hnpqe0unrij7k4x/fsfiles.txt?dl=0

will be building minimal tarball later today. any suggestions, extra commands welcome.

**Comment by pwighton** [comment]
Very cool @satra! The script dcmunpack would be nice to have.

**Comment by binarybottle** [comment]
These commands don't have to include all arguments that you might wish to use later, as with reprozip, do they?  For example:
    recon-all -all -i $T1 -i $T2 -s $SUBJECT -sd $FREESURFER_SUBJECTS -cw256 -expert $EXPERT_FILE

**Comment by satra** [comment]
@pwighton - it would be nice to add directly from dicom conversion, which i think `mri_convert` handles without dcmunpack. i'll check that on a different run. my goal here was not to extend beyond recon-all usage. any additions would be subject to other folks requirements. i'm still considering whether to leave out $cmd4 and $cmd5

@binarybottle - i believe many of those arguments would work with this list without error. but, one would have to come up with a complete list to actually get confirmation. (btw - i think recon-all wouldn't how to handle `-i $T1 -i $T2`).

**Comment by pwighton** [comment]
Yeah @satra, I think dcmunpack is just a helper script and not needed to convert from dicoms.

**Comment by satra** [comment]
@pwighton , @binarybottle - here are the minimized tarballs:

https://www.dropbox.com/sh/mvgpn6cml04me6u/AABPcE15H-hA58nHJv0MJv_4a?dl=0

`recon-all-freesurfer6.min.tgz` - just recon-all bits without MCR
`recon-all-MCRv80.min.tgz`  - just the MCR to add on to the first one
`recon-all-freesurfer6+MCR.min.tgz` - everything for recon-all + brainstem + hippo (needs 10G of memory)

i'll test this tonight in a docker container. just noting that the license file is not included.

**Comment by binarybottle** [comment]
Thank you, @satra!

**Comment by satra** [comment]
in a container this will require setting environment variables along the following lines:

```
ENV OS=Linux \
    FS_OVERRIDE=0 \
    FIX_VERTEX_AREA= \
    FSF_OUTPUT_FORMAT=nii.gz \
    FREESURFER_HOME=/opt/freesurfer
ENV SUBJECTS_DIR=$FREESURFER_HOME/subjects \
    MNI_DIR=$FREESURFER_HOME/mni \
    LOCAL_DIR=$FREESURFER_HOME/local \
    MINC_BIN_DIR=$FREESURFER_HOME/mni/bin \
    MINC_LIB_DIR=$FREESURFER_HOME/mni/lib \
    MNI_DATAPATH=$FREESURFER_HOME/mni/data
ENV PERL5LIB=$MINC_LIB_DIR/perl5/5.8.5 \
    MNI_PERL5LIB=$MINC_LIB_DIR/perl5/5.8.5 \
  PATH=$FREESURFER_HOME/tktools:$MINC_BIN_DIR:$PATH
```

**Comment by satra** [comment]
final bit for removing the files.

you'll have to remount the docker in writeable mode for the freesurfer directory (it's read only at the beginning of this issue. since this script was meant to work in a specific location, it's not tested for arbitrary use cases.

```python
import os
with open('fsfiles.txt', 'rt') as fp:
    data = fp.read().splitlines()
paths = [val.split('"')[1] for val in data]
files_to_remove = []
for root, dirs, files in os.walk('/freesurfer'):
    for fname in files:
        fullname = os.path.join(root, fname)
        if fullname not in paths:
            files_to_remove.append(fullname)
for fname in files_to_remove:
    os.unlink(fname)
```

only 1539 files needed (including MCR bits), 41081 files deleted

**Comment by pwighton** [comment]
@satra:

Another environment variable you may want to consider is OMP_NUM_THREADS=n which enables n worker threads for the binaries: `mri_em_register`, `mri_ca_register`, `mri_ca_label`, `mris_sphere` and maybe a couple others.  Faster runtimes can be achieved with OMP_NUM_THREADS=8.

Is it because of `/freesurfer/license.txt` that the FreeSurfer mount has to be read/write?  How are you handling the license?  Inspired by the BIDS fs container, I'm using an [entrypoint script](https://github.com/corticometrics/fs6-cloud/blob/master/docker/entrypoint-base.bash) for my container to decode a base64 env var into `license.txt`.  It would be nice if there was an `FREESURFER_LICENSE` env var to tell FreeSurfer where to look for 'license.txt' (or even accept a base64 string directly) so the mount could be read-only.

**Comment by satra** [comment]
@pwighton - yes `OMP_NUM_THREADS` should be controlled by the user. i would probably set it to 1 by default in a container.

i think the freesurfer folks are working on an environment variable that points to the location of the license file option, but i'll let @zkaufman comment on that.

there are several things that can be done. the shell option works. here is another option one can use:

`docker ... -v /outside/folder/:/license ...` where /outside/folder contains license.txt

and inside the container one can link: $FREESUFER_HOME/license.txt to /license/license.txt

**Comment by zkaufman** [comment]
@pwighton @satra I believe the ability to define an environment variable to point to the location of the license file has recently been implemented. If not, I will implement it, as it will solve other issue relating this license file locations (multi-user clusters). In terms of accepting a base64 string instead of the file itself, I see no obvious reason why not, but need to think about that some more.

**Comment by dngreve** [comment]
Yes, it has. setenv FS_LICENSE. It is not in version 6 but in our current dev.

**Comment by satra** [comment]
i just tested that the minimal tarball runs recon-all fine (haven't tested longitudinal stream). we will release this together with ants + mindboggle as a combined structural processing container .

@zkaufman and @dngreve - will there be a minor release (6.0.1) soon? we would like to keep the production containers aligned with releases. also if i were to turn this minimization process into an automated docker script, would you be willing to generate a nightly version of the tarball?

**Comment by satra** [comment]
this variable set works, and as @pwighton suggested you can add OMP_NUM_THREADS or use `-openmp N`.

note that freesurfer home and subjects dir should be adjusted.

```
ENV FS_OVERRIDE=0 \
    OS=Linux \
    FSF_OUTPUT_FORMAT=nii.gz \
    FIX_VERTEX_AREA=\
    FREESURFER_HOME=/opt/freesurfer
ENV MNI_DIR=$FREESURFER_HOME/mni \
    SUBJECTS_DIR=/subjects
ENV PERL5LIB=$MNI_DIR/share/perl5 \
    MNI_PERL5LIB=$MNI_DIR/share/perl5 \
    MINC_BIN_DIR=$MNI_DIR/bin \
    MINC_LIB_DIR=$MNI_DIR/lib \
    MNI_DATAPATH=$MNI_DIR/data
ENV PATH=$FREESURFER_HOME/bin:$FREESURFER_HOME/tktools:$MINC_BIN_DIR:$PATH
```

**Comment by zkaufman** [comment]
@satra There are no immediate plans for a minor 6.0.1 release. And yes, send the script (with instructions please) and I will add it to the nightly build.

**Comment by kaczmarj** [comment]
Hi all, [neurodocker](https://github.com/kaczmarj/neurodocker) can now minimize docker images with reprozip. I replicated what @satra did above with `recon-all`.

**Download data**
```shell
rsync -aL psydata.ovgu.de::studyforrest/structural/sub-01 studyforrest-data-structural
```

**Generate Dockerfile and build Docker image**
```shell
neurodocker generate --base continuumio/miniconda:4.3.14 --pkg-manager apt --freesurfer version=6.0.0 | docker build -t kaczmarj/freesurfer:6.0.0 -
```

**Run Docker container**
(`-d` runs container in the background)
```shell
docker run --rm -td --security-opt seccomp:unconfined \
-v $(pwd)/studyforrest-data-structural:/data \
-v $(pwd)/testdata:/fsdata \
-e SUBJECTS_DIR='/fsdata' \
--name recon-all-container \
kaczmarj/freesurfer:6.0.0 bash
```

**Copy FreeSurfer license into container**
```shell
docker cp license.txt recon-all-container:/opt/freesurfer/
```

**Trace commands within running container**
Note that `$cmd3` is not traced. Here are the [logs](https://www.dropbox.com/s/vuixi3ximr96r8e/neurodocker_reprozip_20170719.log?dl=0).
```shell
cmd1="recon-all -s sub-01 -all -i /data/sub-01/anat/sub-01_T1w.nii.gz -T2 /data/sub-01/anat/sub-01_T2w.nii.gz -T2pial"
cmd2="recon-all -s sub-01 -brainstem-structures"
cmd3="recon-all -s sub-01 -hippocampal-subfields-T1T2 /data/sub-01/anat/sub-01_T2w.nii.gz T2 -itkthreads 4"
cmd4="asegstats2table --subjects sub-01 --segno 11 17 18 --meas mean --tablefile aseg.mean-intensity.table"
cmd5="aparcstats2table --hemi lh --subjects sub-01 --tablefile lh.aparc.area.table"

neurodocker reprozip --verbosity=debug recon-all-container "$cmd1" "$cmd2" "$cmd4" "$cmd5" | tee neurodocker_reprozip.log
```

**Stop and delete container**
```shell
docker stop recon-all-container
```

**Create minimized Docker image**
The `neurodocker reprozip` command above gave me a reprozip pack file on my local machine, which I used to create a new, minimized docker image.
```shell
reprounzip docker setup neurodocker-reprozip.rpz test_fs_rpz
```

My original freesurfer v6.0.0 docker image was 6.24 GB, and the minimized docker image was 1.29 GB (uncompressed). There could have been another 363 MB saved if I had deleted the output of the traced commands. I am not sure if reprozip can exclude output automatically (maybe with the `--dont-find-inputs-outputs` option). The environment variables also have to be reset in the minimized container. Even `$PATH` did not carry over.

**Comment by satra** [comment]
@kaczmarj - thanks for this - looking good. i'm surprised that the environment is not maintained somewhere. i think there may be a file inside the image that does have the info. look at how reprozip replays the commands.

**Comment by satra** [comment]
@pwighton - this is now available as part of neurodocker. so closing this issue.

**Comment by schahid** [comment]
Just to warn those who want to try the min of freesurfer or mcr, please don't try the min versions. I tried it yesterday and they are pretty minimum in size but incomplete in full functionality. The minimum freesufer is missing template images which are required in Talairach transformation step. 2nd, the mcr won't work by throwing this error: Message Catalog MCR:mclmcr was not loaded from the file. Please check file location, format or contents. 
So please do some testing before deleting important files to make them minimum in size ;-)

**Comment by satra** [comment]
@schahid - could you please clarify which version you used? and what command you used?

**Comment by schahid** [comment]
@satra I used neurodocker generated freesufer 6.0.0 dockerfile and then used recon-all -all first and then with hippcampal subfields using the full MCR2012b. I thought I should try the min version of FS6.0 and MCR to build the smaller docker image. But first the recon-all failed pointing to a missing img file in FSHOME/average folder. I added that file and re-run the workflow. Then recon-all completed, but when I used the Hippcampal subfields, the min MCR from the dropbox:
https://www.dropbox.com/sh/mvgpn6cml04me6u/AABPcE15H-hA58nHJv0MJv_4a?dl=0
 threw that error as above. 
Please let me know if you want further details.

**Comment by satra** [comment]
thanks @schahid - if you used the one with MCR + min, that should have supported the subfield extraction (provided you have sufficient memory). if not, we can test it out soon. because that version was generated using this command:

```bash
cmd3="recon-all -s sub-01 -hippocampal-subfields-T1T2 /data/sub-01/anat/sub-01_T2w.nii.gz \
 T2 -itkthreads 4"
```
the neurodocker version does not allow subfield segmentation presently.

@kaczmarj - the regular freesurfer should not exclude anything.

https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/interfaces/freesurfer.py#L133

and we should add support for the version with subfield segmentation enabled.

**Comment by kaczmarj** [comment]
@schahid and @satra - I will update the neurodocker's freesurfer installation with these points in mind.

**Comment by schahid** [comment]
Thanks @kaczmarj and @satra for considering these points. 
Just to update you  that I also tried the FS 6.0 ver minimized for recon-all given in 
https://github.com/kaczmarj/neurodocker/blob/master/examples/generated-full.Dockerfile#L115
and it also failed at the early steps  as shown in recon-all-status.log. Dont have the exact error, sorry, as I deleted those subject folders, but only remember it was also related to Talairach stage.

**Comment by satra** [comment]
@schahid - that would be very weird since we actually use that in a couple of different settings. we will test this out.

**Comment by schahid** [comment]
@satra - may be you haven't used the 3T and qcache flags where some of the required input files are not found in the average folder. And if this is the case, then the minimized version would just be used for the default recon-all flags only.

**Comment by satra** [comment]
@schahid - yes the use cases we covered were essentially the ones covered in the 4 commands above. if there are pathways outside those, then files corresponding to those pathways would not be in the minimized tarball.

@kaczmarj - perhaps we can add these two use case commands as well, and cut a new minimized tarball.

**Comment by roohy466** [comment]
> final bit for removing the files.
> 
> you'll have to remount the docker in writeable mode for the freesurfer directory (it's read only at the beginning of this issue. since this script was meant to work in a specific location, it's not tested for arbitrary use cases.
> 
> import os
> with open('fsfiles.txt', 'rt') as fp:
>     data = fp.read().splitlines()
> paths = [val.split('"')[1] for val in data]
> files_to_remove = []
> for root, dirs, files in os.walk('/freesurfer'):
>     for fname in files:
>         fullname = os.path.join(root, fname)
>         if fullname not in paths:
>             files_to_remove.append(fullname)
> for fname in files_to_remove:
>     os.unlink(fname)
> only 1539 files needed (including MCR bits), 41081 files deleted

Is there such a code for freesurfer7.4.1 to have minimum files for recon-all?
Rouhi
