### ISSUE TITLE
Bug: non-application of parameters from expert file to T2-assisted call of mris_make_surfaces in freesurfer-dev

### ISSUE THREAD

**Issue by marcoaqil** [freesurfer/freesurfer#703]
### Platform details:

- FreeSurfer version: freesurfer-dev (binaries obtained from freesurfer website on 11-7-19 and on 20-8-19)
- Operating system name and version: Linux CentOS 7

### Summary
Parameters from an expert file relevant to T2-assisted pial segmentation are passed to the wrong call of mris_make_surfaces. 

### Actual behavior
When running a full recon-all or recon-all autorecon3, with the -T2pial flag, it appears that freesurfer-dev passes parameters from the expert options file, such as -T2_min and -nsigma_below, to the first call of mris_make_surfaces (which uses T1 alone) but not to the second call (which uses T2).

### Expected behavior
Expert-file parameters for a T2-assisted pial segmentation should be passed to the relevant (second) call of mris_make_surfaces.

### How to replicate the behavior
Run a full recon-all or recon-all autorecon3, with -T2pial flag, and an expert file with parameters relevant to T2-assisted pial segmentation (for example, the expert file content could be "mris_make_surfaces -T2_min 50"). Inspect the recon-all log. You should see (or at least this is the behavior i have been getting, with two different versions of freesurfer-dev) that the T2-relevant parameters are passed to the first call of mris_make_surfaces, but not the second one.

I apologize in advance if this bug is actually resulting from a mistake in my understanding of freesurfer, and will be very grateful for any support.

**Comment by vsiless** [comment]
Hi Marco, I just submitted a pull-request that reads these parameters on the recon-all and send them to mris_make_surfaces. You should be careful when playing with those parameters, since the T2 has been normalized by intensity and the values should be pretty much close to the default. It's commit #704 . I'll close this once it's merged. Best!

**Comment by marcoaqil** [comment]
Hi Viviana, thank you very much for the help! That sounds perfect! Sure, I will definitely first try again the segmentation with the standard parameters before trying to change them. Unfortunately so far segmenting with the standard parameters has not given fully satisfactory result on our data, although freesurfer-dev does a lot better than 6.0. Hence why I hope that slightly adjusting the parameters manually could help.

Best,
Marco

**Comment by vsiless** [comment]
Hi Marco, does it look worst than T1 or with only T1 it also looks bad?

**Comment by marcoaqil** [comment]
If you are interested, I can definitely give you more information: perhaps you will have some useful suggestions! The short answer is, with T2 it looks significantly better than T1 alone, but it has some new issues of its own. See below for details.

### Data
I am working with 0.7mm 7T data. The T1 is obtained by suitably combining the first and second inversions of an mp2rage sequence. It has very nice contrast and SNR, but also very significant signal dropout in the temporal lobes. I am only interested in the occipital lobe, so this is not an issue per se, but it probably has an impact on the segmentation statistics. The T2 is obtained from a turbo spin echo sequence, also 0.7mm. 

### Pipeline
I first run the data through the standard anatomical pipeline of [fmriprep 1.4.0](https://fmriprep.readthedocs.io/en/stable/), including freesurfer 6.0 segementation. I then re-run autorecon3 with freesurfer-dev.

### T1 alone
With T1 alone, aside from the regions of signal dropout, freesurfer does an excellent pial segmentation wherever the grey does not touch the dura. However, virtually wherever the grey and dura are in contact, the dura is entirely included within the grey. This also goes for large portions of the sagittal sinus and the tentorium cerebelli. These issues can be corrected manually by acting on the brain mask (also tried the -gcut flag, without great results) but it takes a lot of manual labor since every slice needs to be corrected. Hence why I decided to also collect T2 data.

### T1 + T2
Including T2 resulted in exclusion of about ~70% of the dura and sagittal sinus regions from the final freesurfer-dev segmentation, which was great to see (the tentorium is still mostly included, but that is not too much work to correct manually). However, occasionally now the pial surface segmentation seems to make strange choices that do not reflect either T1 or T2. For example, in some places the pial cuts significantly into the grey matter (this did not happen with T1 alone, and is quite strange because the T1 and T2 data seem to agree). In some other places, the pial extends into and even outside the dura, where both T1 and T2 have very low values, which again is very strange. I was hoping to correct at least some of these issues by acting on the T2_min parameter, and that is when I run into the bug. If you have any further suggestions, they would definitely be appreciated!

**Comment by marcoaqil** [comment]
hi @vsiless, do you know if your bug fix has been (or will soon be) implemented? thank you
