### ISSUE TITLE
MGH coordinate system documentation

### ISSUE THREAD

**Issue by alexrockhill** [freesurfer/freesurfer#714]
It would be great to have a 3D diagram of the Freesurfer coordinate system in the documentation https://surfer.nmr.mgh.harvard.edu/fswiki/CoordinateSystems?action=AttachFile&do=get&target=fscoordinates.pdf, like this example http://www.fieldtriptoolbox.org/faq/how_are_the_different_head_and_mri_coordinate_systems_defined/ especially to clarify fsaverage vs single subject space.

cc @robertoostenveld

**Comment by ahoopes** [comment]
Thanks @alexrockhill. Adding this to our internal documentation todo list. Closing the issue since its unrelated to the actual code.
