### ISSUE TITLE
preproc-sess should pass the input stem to mktemplate

### ISSUE THREAD

**Issue by psoulos** [freesurfer/freesurfer#729]
### Platform details:

- FreeSurfer version: 6.0.0
- Operating system name and version: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c

### Summary
On line 194 of preproc-sess, the following code is called

`set cmd = (mktemplate-sess -s $sessid -d $sessparent -fsd $fsd)`
This ignores the input stem specified by the user when calling preproc-sess. Instead, this line should be 
`set cmd = (mktemplate-sess -s $sessid -d $sessparent -fsd $fsd -funcstem $instem)`

### Actual behavior
preproc-sess ignores the input stem when calling mktemplate

### Expected behavior
preproc-sess should pass the input stem to mktemplate

### Details

Please put URL to code or code here (if not too long).
https://github.com/freesurfer/freesurfer/blob/dev/fsfast/bin/preproc-sess#L194

**Comment by dngreve** [comment]
This has been fixed in the dev version.
