### ISSUE TITLE
freesufer build issue, fail to build anatomicuts/dmri_saveHistograms

### ISSUE THREAD

**Issue by DoctorYe** [freesurfer/freesurfer#730]
- Operating system name and version: ubuntu 18.02
- GCC version: 5.5

script: 
```
cd $raw_path;
git clone https://github.com/freesurfer/freesurfer.git;
wget https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz;
tar -xzvf centos7-packages.tar.gz;
cd $raw_path/freesurfer;
git remote add datasrc https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git;
git fetch datasrc;
git annex get .
```

```
cmake   -DFS_PACKAGES_DIR="$raw_path/packages"\
        -DGFORTRAN_LIBRARIES="/usr/lib/gcc/x86_64-linux-gnu/7/libgfortran.a"\
        -DBUILD_GUIS="OFF"\
        $raw_path/freesurfer
make
```

cmake error: 

> CMakeFiles/testOrientationPlanesFromParcellation.dir    /testOrientationFromParcellationFilter.cxx.o: In function `_ZN3itk11ImageSourceINS_5ImageIdLj3EEEE14GraftNthOutputEjPNS_10DataObjectE':
> 
> testOrientationFromParcellationFilter.cxx(.text._ZN3itk11ImageSourceINS_5ImageIdLj3EEEE14GraftNthOutputEjPNS_10DataObjectE[_ZN3itk11ImageSourceINS_5ImageIdLj3EEEE14GraftNthOutputEjPNS_10DataObjectE]+0x4f): undefined reference to  **_ZNK3itk13ProcessObject23MakeNameFromOutputIndexB5cxx11Em'**
> 
> 
>     anatomicuts/CMakeFiles/dmri_saveHistograms.dir/build.make:342: recipe for target 'anatomicuts/dmri_saveHistograms' failed

for detail information please refer to the attached files: CMakeCache.txt and make.log
Thank you
Ningrong
[CMakeCache.txt](https://github.com/freesurfer/freesurfer/files/3833981/CMakeCache.txt)
[make.log](https://github.com/freesurfer/freesurfer/files/3833982/make.log)

**Comment by ahoopes** [comment]
If you're going to use gcc 5, you must also build the external packages (specifically ITK) with gcc 5 as well, since our prebuilt packages were built with 4.8.

You can also just install gcc 4.8 with:

```
apt-get -y install gcc-4.8 g++-4.8 gfortran-4.8
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 48 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8
update-alternatives --config gcc  # choose gcc-4.8
```

**Comment by YuchuanQiao** [comment]
@ahoopes I also met a problem with make step, the error message was:
/freesurfer/utils/mrisp.cpp:2314:3: note: ‘.count.420’ was declared here
   for (fno = f0; fno <= f1; fno++) /* for each frame */
   ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1565: utils/CMakeFiles/utils.dir/mrisp.cpp.o] Error 1

I built with gcc4.8.1, g++4.8.1 and the same version gfortran.
All prebuilt packages are from https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz.
Do you have any idea why this error occurs?
Thank you.

**Comment by ahoopes** [comment]
Can you send the full message? This seems to be missing the actual compiler error. Also, ubuntu  18.04 non-gui builds are passing locally right now. What branch are you using?

**Comment by YuchuanQiao** [comment]
@ahoopes 
I tried both the latest release version freesurfer-dev_nightly_build and also the dev version from git.
from the output of the build screen, the message is:
[ 27%] Built target vtkutils
[ 27%] Built target fem_elastic
[ 27%] Built target dmri_saveHistograms
[ 27%] Built target testOrientationPlanesFromParcellation
[ 27%] Built target lineprof
[ 29%] Built target kvlGEMSCommon
[ 30%] Built target gemsbindings
[ 30%] Building CXX object utils/CMakeFiles/utils.dir/mrisp.cpp.o
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp: In function ‘<built-in>’:
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2141:3: error: ‘.count.412’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   for (fno = fnoLo; fno < fnoHi; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2141:3: note: ‘.count.412’ was declared here
   for (fno = fnoLo; fno < fnoHi; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2141:3: error: ‘.count.413’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   for (fno = fnoLo; fno < fnoHi; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2141:3: note: ‘.count.413’ was declared here
   for (fno = fnoLo; fno < fnoHi; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp: In function ‘<built-in>’:
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2314:3: error: ‘.count.419’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   for (fno = f0; fno <= f1; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2314:3: note: ‘.count.419’ was declared here
   for (fno = f0; fno <= f1; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2314:3: error: ‘.count.420’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   for (fno = f0; fno <= f1; fno++) /* for each frame */
   ^
/home/tools/freesurfer/freesurfer/utils/mrisp.cpp:2314:3: note: ‘.count.420’ was declared here
   for (fno = f0; fno <= f1; fno++) /* for each frame */
   ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1565: utils/CMakeFiles/utils.dir/mrisp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7326: utils/CMakeFiles/utils.dir/all] Error 2

When I look at the CMakeError.log file, it says:

Performing C++ SOURCE FILE Test HAS_FLTO failed with the following output:
Change Dir: /home/tools/freesurfer/bin_git_gcc4.8.1/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_20b6c/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_20b6c.dir/build.make CMakeFiles/cmTC_20b6c.dir/build
gmake[1]: Entering directory `/home/tools/freesurfer/bin_git_gcc4.8.1/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_20b6c.dir/src.cxx.o
/usr/local/gcc-4.8.1/bin/g++    -fopenmp -Wall -Wextra -Werror -Wno-sign-compare -Wno-unused-result -Wno-unused-parameter -Wno-unused-but-set-variable -fPIC -fdata-sections -ffunction-sections -Wl,--gc-sections -DHAS_FLTO   -flto -fno-fat-lto-objects -o CMakeFiles/cmTC_20b6c.dir/src.cxx.o -c /home/tools/freesurfer/bin_git_gcc4.8.1/CMakeFiles/CMakeTmp/src.cxx
cc1plus: error: -fno-fat-lto-objects are supported only with linker plugin.
gmake[1]: *** [CMakeFiles/cmTC_20b6c.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory `/home/tools/freesurfer/bin_git_gcc4.8.1/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_20b6c/fast] Error 2


Source file was:
int main() { return 0; }

I am not sure which message do you need. If this is not enough, please let me know.
Thank you very much for your help.

**Comment by ahoopes** [comment]
Seems like an openmp-related issue. Can you ensure that you have the `build-essential` package installed on your machine? Also, can you upgrade to gcc-4.8.5 and retry? That's what we use

**Comment by YuchuanQiao** [comment]
What do you mean build-essential package? Right now I only got prebuilt packages from https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz. I am not sure if there are some packages missing. 
I tried to use a different version openmp, openmpi-4.0.3 and openmpi-1.8.4.
But I still meet errors when I make a build.
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/realm.cpp:774:0: error: ignoring #pragma omp critical [-Werror=unknown-pragmas]
     #pragma omp critical
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:152:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:179:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:191:0: error: ignoring #pragma omp critical [-Werror=unknown-pragmas]
         #pragma omp critical
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:214:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:239:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:308:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
     #pragma omp parallel for reduction(+:total_area)
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_base.cpp:506:0: error: ignoring #pragma omp atomic [-Werror=unknown-pragmas]
   #pragma omp atomic
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:378:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
     #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_base.cpp:510:0: error: ignoring #pragma omp atomic [-Werror=unknown-pragmas]
   #pragma omp atomic
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:516:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:557:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_metricProperties_faster.cpp:576:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
   #pragma omp parallel for
 ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/mrisurf_defect.cpp:2725:0: error: ignoring #pragma omp critical [-Werror=unknown-pragmas]
      #pragma omp critical
 ^
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1994: utils/CMakeFiles/utils.dir/realm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1708: utils/CMakeFiles/utils.dir/mrisurf_metricProperties_faster.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1604: utils/CMakeFiles/utils.dir/mrisurf_base.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:1630: utils/CMakeFiles/utils.dir/mrisurf_defect.cpp.o] Error 1
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/surfgrad.cpp: In function ‘long double MRIStargetCost(MRIS*, double, int)’:
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/surfgrad.cpp:1936:11: error: ‘tz’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   free(tz);
           ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/surfgrad.cpp:1935:11: error: ‘ty’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   free(ty);
           ^
/home/tools/freesurfer/freesurfer-7.1.0/src/utils/surfgrad.cpp:1934:11: error: ‘tx’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   free(tx);
           ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-for-loop-analysis" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [utils/CMakeFiles/utils.dir/build.make:2189: utils/CMakeFiles/utils.dir/surfgrad.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7326: utils/CMakeFiles/utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_rateallocate':
tcd.c:(.text+0xd69): undefined reference to `__pow_finite'
/usr/local/bin/ld: tcd.c:(.text+0x1153): undefined reference to `__pow_finite'
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_encode_tile':
tcd.c:(.text+0x1a64): undefined reference to `__pow_finite'
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_decode_tile':
tcd.c:(.text+0x27b3): undefined reference to `__pow_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [anatomicuts/CMakeFiles/testOrientationPlanesFromParcellation.dir/build.make:325: anatomicuts/testOrientationPlanesFromParcellation] Error 1
make[1]: *** [CMakeFiles/Makefile2:12615: anatomicuts/CMakeFiles/testOrientationPlanesFromParcellation.dir/all] Error 2
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_rateallocate':
tcd.c:(.text+0xd69): undefined reference to `__pow_finite'
/usr/local/bin/ld: tcd.c:(.text+0x1153): undefined reference to `__pow_finite'
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_encode_tile':
tcd.c:(.text+0x1a64): undefined reference to `__pow_finite'
/usr/local/bin/ld: /home/tools/freesurfer/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_decode_tile':
tcd.c:(.text+0x27b3): undefined reference to `__pow_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [anatomicuts/CMakeFiles/dmri_saveHistograms.dir/build.make:340: anatomicuts/dmri_saveHistograms] Error 1
make[1]: *** [CMakeFiles/Makefile2:12680: anatomicuts/CMakeFiles/dmri_saveHistograms.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

Maybe it is related to the setting of runtime library, libgomp.so.1 and libpthread.so.
Do you have any suggestions?
Thank you.

**Comment by ahoopes** [comment]
`build-essential` is a package that contains a few different development tools. Have you installed all packages listed by our ubuntu [Build Requirements](https://surfer.nmr.mgh.harvard.edu/fswiki/BuildRequirements) guide?

**Comment by YuchuanQiao** [comment]
I carefully check that page, and all tools are installed on Ubuntu.

when I use ccmake, it reports a warning:
 CMake Warning at tkregister2/CMakeLists.txt:5 (add_executable):
   Cannot generate a safe runtime search path for target tkregister2_cmdl
   because files in some directories may conflict with libraries in implicit
   directories:

     runtime library [libgomp.so.1] in /usr/local/gcc-4.8.1/lib64 may be hidden by files in:
       /usr/local/lib
     runtime library [libpthread.so] in /usr/lib64 may be hidden by files in:
       /usr/local/lib

Is this a big issue? How to fix it?

**Comment by ahoopes** [comment]
Is this from a clean cmake configuration? i.e. you cleared the cache before configuring assuming new things were installed (like gcc)? That is a questionable warning that might be related to the errors you're seeing, but I still can't replicate this on ubuntu 18

**Comment by YuchuanQiao** [comment]
I got the same error as I first posted. It is related to the definition of variable fnoLo and fnoHi, which is at the beginning of the function
static MRI_SP *MRISPblur_new(MRI_SP *mrisp_src, MRI_SP *mrisp_dst, float sigma, int fno) {
  int fnoLo_init, fnoHi_init;
.....
int const          fnoLo        = fnoLo_init;
.....
for (fno = fnoLo; fno < fnoHi; fno++)

error message:
/src/utils/mrisp.cpp:2141:3: error: '.count.412' may be used uninitialized in this function

Could you have a check on this function?
thank you.

**Comment by ahoopes** [comment]
The errors you're sending are much more far-reaching than just that variable definition. Can you send your CMakeCache.txt?

**Comment by YuchuanQiao** [comment]
[CMakeCache.txt](https://github.com/freesurfer/freesurfer/files/4747530/CMakeCache.txt)
Here is the CMakeCache.txt.
thank you for the help.

**Comment by ahoopes** [comment]
I'm not entirely sure what the problem is. There's definitely something up with your build environment. Why are things linking to `/usr/local/glibc-2.14.1`? Are you not compiling on ubuntu 18?

**Comment by YuchuanQiao** [comment]
Sorry about this, when I checked the system info, we are using CentOS actually.
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9

The prebuilt packages used are  https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz

I used the following command to setup the environment.

export PATH="/usr/local/cmake-3.17.2-Linux-x86_64/bin:/usr/local/gcc-4.8.1/bin:/usr/local/openmpi-1.8.4/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/gcc-4.8.1/lib64:/usr/local/gcc-4.8.1/lib:/usr/local/mpc-0.8.1/lib:/usr/local/openmpi-1.8.4/lib:/usr/local/glibc-2.14.1/lib"
export LDFLAGS="-L/usr/local/gcc-4.8.1/lib64 -L/usr/local/gcc-4.8.1/lib -L/usr/local/mpc-0.8.1/lib -L/usr/local/openmpi-1.8.4/lib -L/usr/local/glibc-2.14.1/lib"
export CC=/usr/local/gcc-4.8.1/bin/gcc
export CXX=/usr/local/gcc-4.8.1/bin/g++
export Fortran=/usr/local/gcc-4.8.1/bin/gfortran

Do I miss something for the setup?

**Comment by ahoopes** [comment]
Oh okay, next time please create a new issue if your errors are unrelated to the initial topic. Anyway, after v6, freesurfer requires C++11, which isn't supported by default on centos6. @buildqa when you have a chance can you describe the devtoolset install instructions necessary to build FS on c6?

**Comment by YuchuanQiao** [comment]
Sorry about this, as I did not realize the system difference until you emphasize ubuntu 18.
I try to add -std=c++11 to cmake_CXX_FLAGES, and generate a solution. The problem is as same as I posted previously.

**Comment by buildqa** [comment]
On CetnOS6 we use scl and devtoolset-3 to create the environment to build the current post 6.X source (now officially 7.x.x release) with gcc 4.9.2.  Scl will set the environment including LD_LIBRARY_PATH, PATH etc. so the 4.9.2 compilers and libraries will be found.  You should start with a clean shell before running the command "scl enable devtoolset-3 /bin/bash" to get a new shell setup with the gcc 4.9.2 tools. So do not set the environment variables you listed above before running that scl command.   To get scl and devtoolset-3 on your machine, I would try an install command like "sudo yum install scl-utils.x86_64 devtoolset-3-gcc.x86_64 devtoolset-3-gcc-c++.x86_64 devtoolset-3-gcc-gfortran.x86_64 devtoolset-3-binutils.x86_64"

**Comment by YuchuanQiao** [comment]
@buildqa @ahoopes Thank you for the helpful suggestions. Our IT suggests me to use Ubuntu system for the compilation because they have a maintenance problem with CentOS. I tried on Ubuntu system on a new machine and it works. Thank you very much.
