### ISSUE TITLE
Building error during make

### ISSUE THREAD

**Issue by KrowosDogg** [freesurfer/freesurfer#731]
* gcc 7.4.0
* Operating system: Ubuntu 18.04.3 LTS

### Summary
I am trying to build latest freesurfer version available at dev branch without annex and face the error, which can be seen below. Building it with the following cmake command and following make: 

```
cmake . \
       -DBUILD_GUIS=OFF -DCMAKE_INSTALL_PREFIX="/home/surfer/build" \
       -DFS_PACKAGES_DIR="/home/surfer/packages" \
       -DGFORTRAN_LIBRARIES="/usr/lib/gcc/x86_64-linux-gnu/7.4.0/libgfortran.so" \
       -DGLIB_CONFIG_INCLUDE_DIR="/usr/lib/x86_64-linux-gnu/glib-2.0/include/"

make
```
### Actual behavior
```
Scanning dependencies of target utils
[ 14%] Building CXX object utils/CMakeFiles/utils.dir/afni.cpp.o
[ 14%] Building CXX object utils/CMakeFiles/utils.dir/annotation.cpp.o
/home/surfer/freesurfer/utils/annotation.cpp: In function ‘int MRISdivideAnnotation(MRI_SURFACE*, int*)’:
/home/surfer/freesurfer/utils/annotation.cpp:398:5: error: ‘_div’ directive writing 4 bytes into a region of size between 1 and 1024 [-Werror=format-overflow=]
 int MRISdivideAnnotation(MRI_SURFACE *mris, int *nunits)
     ^~~~~~~~~~~~~~~~~~~~
/home/surfer/freesurfer/utils/annotation.cpp:398:5: note: directive argument in the range [1, 2147483647]
In file included from /usr/include/stdio.h:862:0,
                 from /home/surfer/freesurfer/utils/annotation.cpp:27:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:34:43: note: ‘__builtin___sprintf_chk’ output between 6 and 1038 bytes into a destination of size 1024
       __bos (__s), __fmt, __va_arg_pack ());
                                           ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-for-loop-analysis’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-absolute-value’ [-Werror]
cc1plus: all warnings being treated as errors
utils/CMakeFiles/utils.dir/build.make:86: recipe for target 'utils/CMakeFiles/utils.dir/annotation.cpp.o' failed
make[2]: *** [utils/CMakeFiles/utils.dir/annotation.cpp.o] Error 1
CMakeFiles/Makefile2:1196: recipe for target 'utils/CMakeFiles/utils.dir/all' failed
make[1]: *** [utils/CMakeFiles/utils.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you

**Comment by melrobin** [comment]
This is a result of using gcc7  and above.  There are numerous places and files that will give these errors.

**Comment by KrowosDogg** [comment]
Ok, I see. How can I set to use specific gcc, for example gcc 5.5.0? Is this version suitable?

**Comment by emtpgeek** [comment]
I am building on Ubuntu 18 using gcc 5.5.0, but I am seeing a few build errors that I will be submitting pull requests for

**Comment by emtpgeek** [comment]
Here are my notes for setting up an U18 system to do a build - haven't tried to build the GUI components yet


sudo mv /usr/bin/python /usr/bin/python~old
sudo ln -s python3.6 /usr/bin/python 
python --version
#	should be 3.5 or greater

 
# Install more packages
sudo -i

    apt-get update

    apt-get install \
        build-essential \
        tcsh \
        libtool-bin \
        libtool \
        automake \
        gfortran \
        libglu1-mesa-dev \
        libfreetype6-dev \
        uuid-dev \
        libxmu-dev \
        libxmu-headers \
        libxi-dev \
        libx11-dev \
        libxml2-utils \
        libxt-dev \
        libjpeg62-dev \
        libxaw7-dev \
        liblapack-dev \
        python3-numpy \
        python3-dev \
        python3-pip

    apt-get install \
        libxss-dev \
        libxft-dev

    apt install libgdcm2-dev libnetcdf-dev tcl-dev tk-dev libgts-dev
        #
        # Installs tcl and tk 8.6
        # I also tried tcl and tk 8.4 and 8.5, did no better at building the packages

        
    apt-get install python-numpy python-nibabel
    pip install -U scikit-learn
        
    apt-get install libboost-all-dev

    locale-gen en_US                            # not in the above page
    
    apt install gcc-5 g++-5 gfortran-5
    apt install gcc-7 g++-7 gfortran-7		# was already there

    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7

    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-5

    update-alternatives --config gcc
        # choose 1 to get gcc-5
	
    exit

# check the gcc version
    gcc --version
    	# should be 5.4.0 approx

# cmake is also needed
#
cmake --version

# The instruction pages are wrong, they recommend sudo apt install cmake
    # DONT DO THIS - this version is too old, need cmake-3.10.2-Linux-x86_64.sh
    # if you do it, undo it by...
    # sudo apt-get purge cmake

# Instead follow https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line/865294
sudo -i
    version=3.10
    build=2
    cd /tmp
    mkdir cmake
    
    cd cmake
    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
    
    tar -xzf cmake-$version.$build.tar.gz
    cd cmake-$version.$build/
    ./bootstrap
    make -j4
    make install

# Do the following for superstitious reasons
    logout and login to get it in your path properly - don't know why this is needed

# ccmake is also needed
#
    sudo apt install cmake-curses-gui

# qt5 is also needed to build the gui
#
sudo apt-get install qt5-default libqt5x11extras5-dev

**Comment by ahoopes** [comment]
Closing as dev now compiles successfully on ubuntu 18 thanks to @emtpgeek's recent fixes. Ideally gcc 4.8 should be used unless you're compiling your own external packages. I've updated the [build documentation](https://surfer.nmr.mgh.harvard.edu/fswiki/BuildRequirements) to include instructions on installing and enabling gcc 4.8 on newer ubuntu releases
