### ISSUE TITLE
recon-all doesn't work

### ISSUE THREAD

**Issue by HarlanZhou** [freesurfer/freesurfer#736]
### Platform details:

- FreeSurfer version: FreeSurfer6 
GUN libc version=2.27
- Operating system name and version:Ubuntu18.04

### Summary

i use command to execute recon-all but failed

### Details

harlan@harlan-MS-7C13:/media/harlan/EE408AE0408AAEC1/ubantu/data$ recon-all -s NC001 -all
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
INFO: SUBJECTS_DIR is /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data
Actual FREESURFER_HOME /media/harlan/EE408AE0408AAEC1/ubantu/tool/brain/freesurfer
-rwxrwxrwx 1 harlan harlan 34631 Jan 12 10:56 /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/scripts/recon-all.log
Linux harlan-MS-7C13 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
'/media/harlan/EE408AE0408AAEC1/ubantu/tool/brain/freesurfer/bin/recon-all' -> '/media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/scripts/recon-all.local-copy'
#--------------------------------------------
#@# MotionCor Sun Jan 12 10:57:58 CST 2020
Found 1 runs
/media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/orig/001.mgz
Checking for (invalid) multi-frame inputs...
WARNING: only one run found. This is OK, but motion
correction cannot be performed on one run, so I'll
copy the run to rawavg and continue.

 cp /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/orig/001.mgz /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/rawavg.mgz 

/media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001

 mri_convert /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/rawavg.mgz /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/orig.mgz --conform 

mri_convert.bin /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/rawavg.mgz /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/orig.mgz --conform 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/mri/rawavg.mgz...
--------------------------------------------------------------------------
GNU libc version: 2.27
ERROR: Systems running GNU glibc version greater than 2.15
  require a newly formatted license file (it's free). Please
  download a new one from the following page:
  http://surfer.nmr.mgh.harvard.edu/registration.html
--------------------------------------------------------------------------
Linux harlan-MS-7C13 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s NC001 exited with ERRORS at Sun Jan 12 10:58:02 CST 2020

For more details, see the log file /media/harlan/EE408AE0408AAEC1/ubantu/data/tutorial_data/NC001/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

**Comment by ahoopes** [comment]
You need a newly formatted FS license as described in the error message. You can reregister at http://surfer.nmr.mgh.harvard.edu/registration.html

Closing as this should be posted on the [freesurfer help list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport). We like to reserve the issues page for clear software bugs.
