### ISSUE TITLE
Minor issues in T2-assisted pial surface segmentation

### ISSUE THREAD

**Issue by marcoaqil** [freesurfer/freesurfer#747]
Feel free to close if not useful/relevant.

### Platform details:
- FreeSurfer version: freesurfer-dev built on 03-02-2020
- Operating system name and version: Linux CentOS 7

### Behavior
- Standard-settings T2-assisted pial segmentation appears to cut too deep into gray matter in places where T2 values are compatible with the gray matter range; it does not seem to take into account CSF high T2 values at the cerebellum border. 

- Different -T2_min/max_inside/outside values set from the recon-all command line, or passed to mris_make_surfaces from the expert options file, appear not to be taken into account downstream (according to recon-all log). Possibly because of these lines? https://github.com/freesurfer/freesurfer/blob/77eab10ac0d8679243795f93dffec71dd25fdfca/mris_make_surfaces/mris_place_surface.cpp#L222-L225

### Examples 
**Legend:** smoothwm (yellow line), T2 pial (black line), T1 pial (white line). T2 is shown with jet colormap (red>300), T1 in grayscale.

#### T2-pial too deep
![snapshot5](https://user-images.githubusercontent.com/10636635/73944793-75dea600-48f3-11ea-8630-3002c4e1042e.png)
![snapshot6](https://user-images.githubusercontent.com/10636635/73944796-76773c80-48f3-11ea-96f9-c0477b2c48ef.png)

#### Cerebellum included in gray
![snapshot7](https://user-images.githubusercontent.com/10636635/73944838-8858df80-48f3-11ea-99b4-814bfb7d0629.png)
![snapshot8](https://user-images.githubusercontent.com/10636635/73944840-88f17600-48f3-11ea-9756-9d31053def58.png)

### How to replicate the behavior
recon-all -autorecon-pial -subjid <subjid> -T2 <T2_path> -hires -T2pial (-T2_min/max_inside/outside <val>)

**Comment by vsiless** [comment]
Hi Marco, I'm working on a new version of the T1+T2 pial surface placement. Would you be willing to share this data so I can see if the new version fix this issue?  Please email me at vsiless@mgh.harvard.edu
Thanks!

**Comment by vsiless** [comment]
was a registration issue with bbregister coreg init

**Comment by fredrmag** [comment]
Hi, I am seeing this issue in FreeSurfer 7.1.0, is it fixed in FreeSurfer 7.1.1?

**Comment by marcoaqil** [comment]
it was an issue in a freesurfer-dev version, before 7 came out (see first message). i didnt encounter it in 7.1.0

**Comment by fredrmag** [comment]
Thanks for the reply. Ah, I see now, you used the T2. Sorry, I have the same issue using FLAIR. Maybe I should open a separate issue?

**Comment by marcoaqil** [comment]
yes, I used T2, and this one is closed so probably better to open a new one :)
