### ISSUE TITLE
[macOS]segmentHA_T1.sh with custom subject dir

### ISSUE THREAD

**Issue by lamaresh** [freesurfer/freesurfer#757]
on MacOS when i try to use segmentHA_T1.sh passing a custom subject directory it crashes with this error:

> Error using myMRIread (line 16)
> 
> Error in myMRIread: temporary directory does not exist
> 
> Error in segmentSubjectT1_autoEstimateAlveusML (line 157)

**Comment by aboualiaa** [comment]
Could you please provide more context? Like your setup/environment, The exact invocation command?

**Comment by lamaresh** [comment]
i used: segmentHA_T1.sh subName .
in that folder i previously ran recon-all successfully

i noticed that if I use full path to my custom subjectdir instead of . it works properly. recon-all accept relative path so i think  segmentHA_T1.sh should too

**Comment by ahoopes** [comment]
Closing as this is fixed by https://github.com/freesurfer/freesurfer/commit/36c5a20414454ecc3b6d7d6034825ce8b5d827e5
