### ISSUE TITLE
Issue with finding LICENSE file

### ISSUE THREAD

**Issue by jayashree15** [freesurfer/freesurfer#764]
For general questions, please post to the freesurfer mailing list:

  freesurfer@nmr.mgh.harvard.edu

Please use GitHub issues to report software bugs and to discuss specific code related issues.

When reporting issues, please provide the following information:

---- WHEN REPORTING AN ISSUE CUT HERE and ABOVE ----

### Platform details:

- FreeSurfer version: Freesurfer v 6.0-2017
- Operating system name and version: Linux CentOS 7

### Summary
Issue with finding LICENSE text file

### Actual behavior
recon-all not detecting the LICENSE file, but searching for 'license.txt'

### Expected behavior
To detect LICENSE file in the same directory

### How to replicate the behavior
Run Freesurfer script through HCP (v. 4.3.1).

### Details
I was running the Freesurfer (v 6.0-2017) pipeline and I'm encountering an issue with the recon-all.v6.hires, it was unable to find the 'license.txt' file though it is available as 'LICENSE'. Since I don't have root access I cannot rename that file. Do you know how this occurred.

Please put URL to code or code here (if not too long).

Thank you!

Appreciate your help

**Comment by ahoopes** [comment]
The LICENSE file is a software agreement license, not a freesurfer user license. Please visit https://surfer.nmr.mgh.harvard.edu/registration.html to register a user license. Closing as this is not a development issue.
