### ISSUE TITLE
Problems loading surface in gifti file format

### ISSUE THREAD

**Issue by markusadamek** [freesurfer/freesurfer#766]
### Platform details:
- FreeSurfer version: 
Freeview Version 3.0, Build Mar 18 2020 0028:52
- Operating system name and version:
Ubuntu 18.04 (using WSL)

### Summary
Not able to open gifti Surface file 

### Actual behavior
mrisReadGIFTIfile: malformed data array [2] in file bv_gifti_12_lwhite.surf.gii: num_vertices=3 num_cols=22134 expected nvertices=22134, num_cols=3

### Expected behavior
File can be opened as expected with [Surf Ice](https://www.nitrc.org/frs/?group_id=984)

### How to replicate the behavior
File can be found here:
[bv_gifti_12_lwhite.surf.zip](https://github.com/freesurfer/freesurfer/files/4470823/bv_gifti_12_lwhite.surf.zip)

**Comment by ahoopes** [comment]
This should be fixed in dev now after d1cc436d5a93e7ebbc9e0aebc44931aba9e7752c. Array order was being ignored for column-major vertices.
