### ISSUE TITLE
segmentHA_T2.sh minor error, cat unable to find .txt file

### ISSUE THREAD

**Issue by hfxcarl** [freesurfer/freesurfer#770]
### Platform details:

- FreeSurfer version: freesurfer-darwin-OSX-ElCapitan-dev-20180919-4c582fa 
- Operating system name and version: Mac OS 10.15.4 "Catalina"
- Computer: 2018 MacBookPro 15" with 2.9GHz 6-Core Intel i9 and 32GB RAM

### Summary
Ran command:
 `$ segmentHA_T2.sh <SSID> /path/to/T2w.nii.gz T2wT1w 1 /path/to/SUBJECTS_DIR/`

Works fine, but prints minor error:
> cat: ./SSID/mri/lh.hippoSfVolumes-T2.v21.T2wT1w.txt: No such file or directory
> cat: ./SSID/mri/lh.amygNucVolumes-T2.v21.T2wT1w.txt: No such file or directory
> cat: ./SSID/mri/rh.hippoSfVolumes-T2.v21.T2wT1w.txt: No such file or directory
> cat: ./SSID/mri/rh.amygNucVolumes-T2.v21.T2wT1w.txt: No such file or directory

These files almost matching the name do exist and are likely intended:
> ./SSID/mri/lh.hippoSfVolumes-T1-T2wT1w.v21.txt
> ./SSID/mri/lh.amygNucVolumes-T1-T2wT1w.v21.txt
> ./SSID/mri/rh.hippoSfVolumes-T1-T2wT1w.v21.txt
> ./SSID/mri/rh.amygNucVolumes-T1-T2wT1w.v21.txt

### Details

Here is a bug fix to match actual filename formatting in segmentHA_T2.sh (lines 307-314):
```
  set txt=$SUBJECTS_DIR/$SUBJECTNAME/mri/$hemi.hippoSfVolumes-T1-$ANALYSISID.$SUFFIX.txt
  set stats=$SUBJECTS_DIR/$SUBJECTNAME/stats/hipposubfields.$hemi.T2.$SUFFIX.$ANALYSISID.stats
  echo "# Hippocampal subfield volumes as created by segmentHA_T2.sh" > $stats
  cat $txt | awk '{print NR" "NR"  0 "$2" "$1}' >> $stats
  set txt=$SUBJECTS_DIR/$SUBJECTNAME/mri/$hemi.amygNucVolumes-T1-$ANALYSISID.$SUFFIX.txt
  set stats=$SUBJECTS_DIR/$SUBJECTNAME/stats/amygdalar-nuclei.$hemi.T2.$SUFFIX.$ANALYSISID.stats
  echo "# Amygdala nuclei volumes as created by segmentHA_T2.sh" > $stats
  cat $txt | awk '{print NR" "NR"  0 "$2" "$1}' >> $stats
```

**Comment by ahoopes** [comment]
Thanks! Just pushed a fix (0acd04f) to dev
