### ISSUE TITLE
bf: fs_install_mcr script links to wrong download location

### ISSUE THREAD

**Issue by cjungerius** [freesurfer/freesurfer#773]
### Platform details:

- FreeSurfer version: 
6.0.0

- Operating system name and version:
Ubuntu 18.04

### Summary
fs_install_mcr fails download of R2012b installer.zip from MATLAB runtime download location due to incorrectly formatted link

### Actual behavior
fs_install_mcr exits with an error 

### Expected behavior
fs_install_mcr correctly installs a MATLAB runtime in the freesurfer home folder

### How to replicate the behavior
attempt to install a MATLAB R2012b runtime using fs_install_mcr with any OS

### Details

For my personal install I fixed the issue by changing the format of the link, seen below in my fork of the repository.
It's a small change, hopefully easy to implement. I believe it should still work for all OS and runtime versions.

<https://github.com/cjungerius/freesurfer/commit/283ad5dadf62c7f80886a552cff1f0bca41c782d>

**Comment by cjungerius** [comment]
UPDATE: Upon inspection the issue here is that the format for download files is different for releases up to R2012b and later releases. Perhaps a check on the runtime version is needed?

**Comment by ahoopes** [comment]
Thanks for pointing this out! Fixed in 1e59ba558e4258b23cfc8c175ccaed31f5d5d2c3
