### ISSUE TITLE
FS7 Consistently Crashes at Defect Correction

### ISSUE THREAD

**Issue by hebbianloop** [freesurfer/freesurfer#774]
### Platform details:

- FreeSurfer version:  7
- Operating system name and version: macOS Catalina 10.15.4

### Summary
Cannot successfully run recon-all past defect correction. Tried release 7.0.0b for macOS as well as building from source.

### Actual behavior
Program completes Defect2seg but crashes after mris_remesh with error

`\n mris_remesh --remesh --iters 3 --input /Users/admin/Documents/Dissertation/master/data/tpl-MNIPediatricAsym/sub-tpl-MNIPediatricAsym/ses-cohort1/freesurfer/tpl-MNIPediatricAsym_cohort-1_res-1_fs7/surf/lh.orig.premesh --output /Users/admin/Documents/Dissertation/master/data/tpl-MNIPediatricAsym/sub-tpl-MNIPediatricAsym/ses-cohort1/freesurfer/tpl-MNIPediatricAsym_cohort-1_res-1_fs7/surf/lh.orig \n
/usr/bin/time: illegal option -- o
usage: time [-lp] command.
@#@FSLOADPOST 2020:05:01:18:38:53 mris_remesh N 7 2.64 2.12 1.92
make: *** [/Users/admin/Documents/Dissertation/master/data/tpl-MNIPediatricAsym/sub-tpl-MNIPediatricAsym/ses-cohort1/freesurfer/tpl-MNIPediatricAsym_cohort-1_res-1_fs7/surf/lh.orig] Error 1`

The crash leaves an "IsRunning" file in the scripts folder.

### Expected behavior
Run to completion.

### How to replicate the behavior
Run recon-all on tplMNI152PediatricAsym_cohort-1_res-1_T[12]w

### Details

Please put URL to code or code here (if not too long).

**Comment by ahoopes** [comment]
Seems like you might be using the beta version? This should be fixed in the actual 7.0.0 release. Please let us know if this isn't the case!

**Comment by hebbianloop** [comment]
That's right! I believe I'm using the beta, when does the 7.0.0 release come out and where can I access it if is already out?

**Comment by ahoopes** [comment]
Okay, that's relieving. And released yesterday! Here's the [download page](https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall)

**Comment by hebbianloop** [comment]
Can confirm, downloaded mac os release and was able to run without issues. Thank you!! Very happy with this new release.
