### ISSUE TITLE
fs_time issue when running recon-all -base

### ISSUE THREAD

**Issue by devDonnn** [freesurfer/freesurfer#776]
### Platform details:

- FreeSurfer version: 7.0.0
- Operating system name and version: Linux RHEL7

### Summary
Cannot complete recon-all -base processing.

### Actual behavior
Stops the processing and throws: 
> fs_time: Undefined variable

### Expected behavior
Should not stop the processing in case /usr/bin/time does not exist.

### How to replicate the behavio
Run recon-all -base processing where /usr/bin/time does not exist.

### Details

It turns out this happens when _/usr/bin/time_ does not exist and recon-all -base step is run. The problem is that in _rca-base-init_ file, the fs_time is not initialized at the beginning as it is in the recon-all script where `set fs_time = "";`. Due to the fact that /usr/bin/time does not exist, the following code snippet does not initialize fs_time either:

> if ($DoTime) then
>     fs_time ls >& /dev/null
>     if ( ! $status) set fs_time=(fs_time)
> endif

Therefore, all subsequent calls to $fs_time result in undefined variable error.

**Comment by ahoopes** [comment]
Thanks for finding this. I just pushed a fix to dev (75be2e3), and this will be included in the next patched release. In the meantime, you can disable `fs_time` in `recon-all` entirely by setting the environment variable `export FS_TIME_ALLOW=0`
