### ISSUE TITLE
rca-config fails with -hires

### ISSUE THREAD

**Issue by chrisadamsonmcri** [freesurfer/freesurfer#790]
For general questions, please post to the freesurfer mailing list:

  freesurfer@nmr.mgh.harvard.edu

Please use GitHub issues to report software bugs and to discuss specific code related issues.

When reporting issues, please provide the following information:

---- WHEN REPORTING AN ISSUE CUT HERE and ABOVE ----

### Platform details:

- FreeSurfer version: 7.0.0
- Operating system name and version: Ubuntu 20.04

### Summary

recon-all -hires -s 10160-PS0579-10-1 -sd `pwd` -autorecon2-wm
usage: rca-config [-h] [-gca GCA] [-gca-skull GCASKULL] [-ants-n3] [-no-ants-n4] [-no-ants-denoise] [-no-remesh] [-decimate] [-decimation-area DECIMATIONFACEAREA] [-rip-wmsa] [-rip-lesion]
rca-config: error: argument -h/--help: ignored explicit argument 'ires'
ERROR: could not configure recon-all parameters

### Actual behavior

recon-all -hires -s SUBJID -sd `pwd` -autorecon2-wm
usage: rca-config [-h] [-gca GCA] [-gca-skull GCASKULL] [-ants-n3] [-no-ants-n4] [-no-ants-denoise] [-no-remesh] [-decimate] [-decimation-area DECIMATIONFACEAREA] [-rip-wmsa] [-rip-lesion]
rca-config: error: argument -h/--help: ignored explicit argument 'ires'
ERROR: could not configure recon-all parameters

### Expected behavior

Doesn't fail.

### How to replicate the behavior

Run recon-all with -hires.

### Details

Fix by changing line 62 in $FREESURFER_HOME/python/scripts/rca-config

parser = argparse.ArgumentParser(allow_abbrev=False, add_help=False)

Please put URL to code or code here (if not too long).

**Comment by ahoopes** [comment]
I can't replicate this at all, even in an ubuntu20 container. Can you send the contents of `$FREESURFER_HOME/build-stamp.txt`? Also, we highly recommend you upgrade to freesurfer 7.1 if possible to prevent possible [input conforming issues](https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes).

**Comment by chrisadamsonmcri** [comment]
It was a local build from a git fork. But I used the 7.0.0 tag and didn't change any of the source files.
I will upgrade to 7.1

**Comment by ahoopes** [comment]
Closing as this issue is inactive and unreproducible. @chrisadamsonmcri please feel free to reopen if you see this problem again.
