### ISSUE TITLE
lh.white Open with Notepad is garbled, so how to solve this issue?

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#799]
For general questions, please post to the freesurfer mailing list:

  freesurfer@nmr.mgh.harvard.edu

Please use GitHub issues to report software bugs and to discuss specific code related issues.

When reporting issues, please provide the following information:

---- WHEN REPORTING AN ISSUE CUT HERE and ABOVE ----

### Platform details:

- FreeSurfer version: 
- Operating system name and version:

### Details

Please put URL to code or code here (if not too long).

**Comment by ahoopes** [comment]
`lh.white` is a binary surface file - it can't be opened in a text editor. Use `freeview` to visualize any surface meshes.

**Comment by tanjia123456** [comment]
thank you very much!  I have used other ways to extract information
