### ISSUE TITLE
stats2table: import csv problems

### ISSUE THREAD

**Issue by butellyn** [freesurfer/freesurfer#802]
### Platform details:

- FreeSurfer version: 6.0.1
- Operating system name and version: ubuntu:xenial-20200114 (Containerized in a docker image)

### Summary
I am trying to use `asegstats2table` and `aparcstats2table` to get my stats files into csvs. I've run into a couple of issues, one of which I can't figure out how to resolve. The first issue was that they are written in python2, while many other programs within freesurfer are written in python3. Once I figured this problem out, I just called the scripts with python2. I am now stuck on the `import csv` line within `asegstats2table`. 

### Actual behavior
When I call `asegstats2table` with python2, I get the following error:
`Traceback (most recent call last):
  File "/opt/freesurfer/bin/asegstats2table", line 8, in <module>
    import csv
ImportError: No module named csv`

`csv` is part of the python standard library, so it shouldn't be necessary to install it (https://docs.python.org/3/library/csv.html), but I am also unable to install it. When I run `pip install csv`, I get the following error: 
`ERROR: Could not find a version that satisfies the requirement csv (from versions: none)
ERROR: No matching distribution found for csv`

### Expected behavior
I expect to get a csv of the specified measure by running:
`python2 ${FREESURFER_HOME}/bin/asegstats2table -i ${subj}/stats/wmparc.stats --delimiter comma --meas volume --skip --all-segs --tablefile wmparc_stats.csv`.
You can build the docker image using this code: https://github.com/PennBBL/freeqc-fw-hpc. If you do so, you'll have to bind your freesurfer license for it to work.

**Comment by ahoopes** [comment]
Yeah the python scripts in v6 are bit of a mess, but for the most part they all assume the default is python 2. This has been sorted out in v7.

Anyway, it sounds to me like this is an issue with an incomplete python2 install. `csv` is a system module that should always come installed. I would suggest running `apt-get -y install python2.7` in your container to ensure you have everything you need. That should get things working.
