### ISSUE TITLE
rh.white template to fsaverage5 conmand

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#806]
Hello, please ask a question. For bert/surf/rh.white in the file generated by freesurfer, because there are too many rh.white vertices generated directly (130000+), what command can be used to register it to the fsaverage5 space, so that the number of fixed points is reduced to 10000 +?

**Comment by ahoopes** [comment]
Closing as not a bug. Please post this type of question to the freesurfer mailing list.
