### ISSUE TITLE
Freesurfer singularity container pid namespace causes conflict with temp directories using pid in name

### ISSUE THREAD

**Issue by ibrwr** [freesurfer/freesurfer#810]
Hello,
I am running Freesurfer 7.1.1 in a neurodocker container. I am running into the problem that temp directories are often defined with the process id in the temp directory name while internally multiple containers on the same host can have the same pid inside the container due to pid namespaces. These leads to freesurfer sessions that are running simultaneously on the same host occasionally using the same temp directory name and overwriting data of other sessions.

The lines in the scripts that define the temporary directory names like this are similar to this one in avi2talxfm:

set tmpdir = /tmp/calcxfm.$$

The $$ will be replace with the PID, which is not unique as seen from the host that has multiple containers running. I think a possible solution would be to make the directory as follows instead of with mkdir:

mktemp -d ${tmpdir}_XXXXXX

This would keep the pid information in the tmp directory name, but also adding a random string to make sure the directory name is unique. A grep on the scripts listed quite some places where this way of making temp directories occurs though, and I did not check to see if this would be a problem in compiled code.

Background: I actually first tried to solve this problem outside of freesurfer, but I can not switch off pid namespaces due to restrictions on an older kernel. Before using a container in the first place, I tried installing the Freesurfer 7.1.1 on our centos 6.4 kernel but it gave an error with some runtime libraries being too old and unfortunately I can not update these. 

Thank you for your time and looking forward to hearing your view on this issue. 

Iman

### Platform details:

- FreeSurfer version: 7.1.1
- Operating system name and version: singularity container centos 7, running on host with centos 6.4

**Comment by ahoopes** [comment]
There are definitely some improvements to be made in freesurfer's temp file handling, i.e. this problem you bring up is an issue, and in general, many people would benefit from having the ability to globally set the tmp root path. There's a bit of a current effort (somewhat low priority) to have temporary file/folder creation be handled by a specialized FS tool, but as you mention, there are sooo many scripts that hardcode paths to `/tmp/$$`. On the upside, only a handful of these utilities are used frequently and it wouldn't be too difficult to fix up the higher-priority ones in time for a new 7.1 patch release.

For reference, it'd be helpful to compile a list of most frequently used scripts that run into this issue. Here's a quick list of what comes to mind, but I'm sure I'm missing some:

```
# utils
aparcstatsdiff
asegstatsdiff
fscalc
fslregister
fsl_rigid_register

# recon utils
defect2seg
longmc
mergeseg
mri_motion_correct.fsl
mri_nu_correct.mni
mris_preproc
pctsurfcon
samseg2recon
sratio
tkregisterfv

# trac scripts
trac-all
trac-preproc
orientLAS
xfmrot
xhemi-tal
epidewarp.fsl
```

If you come across any other cases, please let us know.

**Comment by ibrwr** [comment]
Thanks for you attention to this issue. I think a special tool for this would be great, since it allows for easy customization. 

Unfortunately I do not know much about FS internals and frequency of tools used, I typically just run the recon-all command. But let me know if I can help somehow in solving / testing this issue.

**Comment by pwighton** [comment]
Hi @ibrwr ,

> These leads to freesurfer sessions that are running simultaneously on the same host occasionally using the same temp directory name and overwriting data of other sessions.

I don't think I understand how files created in one container are being seen from inside another. Is it possible the `/tmp` directory is being bind mounted across multiple containers?

**Comment by ibrwr** [comment]
That is indeed the case. It is a default system wide setting with singularity containers. But more recent versions of singularity offer two ways around this: either system wide disabling of pid namespaces or user binding of paths, which would allow each container to bind to a different tmp folder. We are currently still stuck still with this old version of singularity  due to a (very) old kernel version but I imagine most people will run a  more recent version these days and have ways around this.

**Comment by pwighton** [comment]
Got it. Thanks for the clarification!

**Comment by ahoopes** [comment]
I've updated almost every tool to adopt a new FS temp file framework (56074b28d403551f5aeb7a14eff1427236a34ac4). Nothing should be hardcoded to `/tmp` anymore and temp files do not use PID in the path. Default temporary directories are defined by the POSIX standard `TMPDIR`, `TMP`, `TEMPDIR`, or `TEMP` env vars and can be overwritten globally by the freesurfer-specific `FS_TMPDIR` env var. There are a few scripts that have not been updated, but they are uncommonly used tools that should probably be removed from the distribution anyway.
