### ISSUE TITLE
ITK adaptive denoising module 

### ISSUE THREAD

**Issue by ntustison** [freesurfer/freesurfer#816]
Hey all, 

Just an FYI---sorry it took me so long to do this but I just pushed the [denoising filter to ITK as a module](https://github.com/InsightSoftwareConsortium/ITK/pull/2018) to get more eyes on it, especially after its incorporation into FreeSurfer.  I'm guessing it will be included as a remote module sometime soon-ish but just wanted y'all to be on the lookout because, if past experience is any indication, we will probably get some performance improvements once the ITK community starts looking at it.

Nick

**Comment by ahoopes** [comment]
Okay wonderful! Thanks Nick. Will keep an eye out
Andrew
