### ISSUE TITLE
some issues with freesurfer

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#819]
Hello, freesurfer
why is it garbled when I open the labels/.annot file with Notepad?
 In addition, how to open .annot files with freeview? 
Finally, how to modify the value in vertex_label?
my freesurfer version : freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c

**Comment by tanjia123456** [comment]
The label information of annoatation is in the view column, but my version does not have this function. What is the matter?

**Comment by ahoopes** [comment]
The output is garbled for the reason given to your question in https://github.com/freesurfer/freesurfer/issues/799. Please post this type of question on the [FS mailing list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport), not on our issues page. Closing as duplicated by https://github.com/freesurfer/freesurfer/issues/820.
