### ISSUE TITLE
POSIX compliant pathname resolution

### ISSUE THREAD

**Issue by pwighton** [freesurfer/freesurfer#82]
Several FreeSurfer binaries use MRISwrite() (and it's relatives) to write surface files.  When only a filename is given (with no path), MRISwrite() resolves the path the directory of the input surface.

In order to increase FreeSurfer's interoperability, I've created a patch that will resolve filenames with no path to the current working directory (as per [POSIX 4.11](http://pubs.opengroup.org/onlinepubs/009604499/basedefs/xbd_chap04.html))

This patch affects the following binaries in the recon-all stream: `mris_smooth`, `mris_jacobian`, `mris_inflate`, `mris_register` and `mris_sphere`.

In order to not break any related tools or scripts, the behavior is only enabled if the FS_POSIX environment variable is set.  

I'll generate and link to a pull request and tests shortly.

**Comment by zkaufman** [comment]
@pwighton Ill test these this week and accept the PR if all goes well. Any preference on if I squash the PR (into a single commit) or keep the history intact? Ill generally squash but Im happy to preserve commit history if you think its useful.

**Comment by pwighton** [comment]
Thanks @zkaufman!  I'm ok with whatever you think is best.  Squash away!
