### ISSUE TITLE
The non-existent field'numEntries' is referenced.(write_annotation.m)

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#825]
hello, when i use the write_annotation.m, the error message occurs: 
`The non-existent field'numEntries' is referenced.

Error write_annotation (line 62)
count = fwrite(fp, int32(ct.numEntries),'int');

Error test_1 (line 13)
write_annotation('rh.aparc.a2009s.annot', c, b, ct)`
How to solve the non-existent field'numEntries' is referenced？

**Comment by ahoopes** [comment]
Seems to me like `ct` is not a true colortable structure. The documentation in `write_annotation.m` specifies what you need. Your question is being discussed on the mailing list. Please don't double-post.
