### ISSUE TITLE
mri_surf2surf  :Cannot allocate memory

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#835]
Hello,Fs 
when I use mri_surf2surf command, the following error appears:
`setenv SUBJECTS_DIR /home/tj/application/freesurfer/subjects
cd /home/tj/application/freesurfer/subjects/OASIS-TRT-20-18/surf
mri_surf2surf --srcsubject OASIS-TRT-20-1 --sval thickness --src_type curv --trgsubject fsaverage5 --trgsurfval /home/tj/application/freesurfer/subjects/min_template/OASIS-TRT-20-1-target/thickness --trg_type curv --hemi rh 

sysname  Linux
hostname bme01
machine  x86_64
user     tj
srcsubject = OASIS-TRT-20-1
srcval     = thickness
srctype    = curv
trgsubject = fsaverage5
trgval     = /home/tj/application/freesurfer/subjects/min_template/OASIS-TRT-20-1-target/thickness
trgtype    = curv
srcsurfreg = sphere.reg
trgsurfreg = sphere.reg
srchemi    = rh
trghemi    = rh
frame      = 0
fwhm-in    = 0
fwhm-out   = 0
label-src  = (null)
label-trg  = (null)
OKToRevFaceOrder  = 1
UseDualHemi = 0
Reading source surface reg /home/tj/application/freesurfer/subjects/OASIS-TRT-20-1/surf/rh.sphere.reg
TAGskip: tag=1601402226, failed to calloc 1931488256 bytes!

Cannot allocate memory
`
Do you know what cause this? memory not enough? how to solve the problem? Thanks.

**Comment by ahoopes** [comment]
It can't allocate ~2GB. How much memory do you have?

**Comment by tanjia123456** [comment]
Do you know what command to see how much memory I have? I Can't find it.

**Comment by tanjia123456** [comment]
`tj@bme01:~/application/freesurfer/subjects$ free
              total        used        free      shared  buff/cache   available
Mem:      131673804     1384208    92913144        2416    37376452   129226640
Swap:       8388604      170900     8217704
`

**Comment by ahoopes** [comment]
Are these in 1024-byte units? If so, you have plenty of memory. What's the output of `free -m`?

Can you run `mris_info /home/tj/application/freesurfer/subjects/OASIS-TRT-20-1/surf/rh.sphere.reg`

**Comment by tanjia123456** [comment]
Can't run the command, will occurs same problem:
TAGskip: tag=1601402226, failed to calloc 1931488256 bytes!
Cannot allocate memory

I don't know how to solve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freesurfer/freesurfer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 凌晨3:18
收件人:&nbsp;"freesurfer/freesurfer"<freesurfer@noreply.github.com&gt;;
抄送:&nbsp;"1248742467"<1248742467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [freesurfer/freesurfer] mri_surf2surf  :Cannot allocate memory (#835)





 
Are these in 1024-byte units? If so, you have plenty of memory.
 
Can you run mris_info /home/tj/application/freesurfer/subjects/OASIS-TRT-20-1/surf/rh.sphere.reg

**Comment by tanjia123456** [comment]
When I use swapon --show
NAME      TYPE SIZE   USED PRIO
/swap.img file   8G 165.1M   -2

**Comment by ahoopes** [comment]
Can you upload the surface reg file to our [FTP server](https://surfer.nmr.mgh.harvard.edu/fswiki/FtpFileExchange) so we can debug it a bit? Thanks

**Comment by tanjia123456** [comment]
Hello, I can't upload these files, so, could you please download from the https://osf.io/wzqmg/. what's more, the lh.area lh.volume lh.jsc_white can't match the surface(148298,146833) in the HLN-12-1 file.

**Comment by ahoopes** [comment]
It looks like this file is just corrupted. I would reach out to the owner of that data.
