### ISSUE TITLE
A possible bug in MRIfindBrightNonWM() in mri2.cpp

### ISSUE THREAD

**Issue by hsjunn** [freesurfer/freesurfer#836]
### Platform details:

- FreeSurfer version: 7.1.1
- Operating system name and version: N/A

### Summary

`MRIdilateThreshLabel()`'s argument/return value seems to be misused

### Actual behavior

N/A (source reading only)

### Expected behavior

N/A (source reading only)

### How to replicate the behavior

N/A (source reading only)

### Details

In a call to `MRIdilateThreshLabel()` at `mri2.cpp`:5809,
`mri_dst` argument (the third one) is passed as `NULL`.

`MRIdilateThreshLabel()` allocates a new mri instance,
operates upon it, and then returns that instance
when passed `mri_dst` arg is NULL.

But the caller is simply ignoring `MRIdilateThreshLabel()`'s return value,
thereby voiding `MRIdilateThreshLabel()`'s all work
and leaking the allocated mri instance.

It seems the intended behavior can be obtained
by passing `mri_dst` set to `mri_labeled`.

**Comment by ahoopes** [comment]
Good find! Thanks for bringing this to our attention. The leak has been fixed by 76e19689e193e24de4498d2c90deaa60b4db3097.
