### ISSUE TITLE
Minor issues in FLAIR-assisted pial surface segmentation

### ISSUE THREAD

**Issue by fredrmag** [freesurfer/freesurfer#849]
Please close if not useful/relevant. 

#### FreeSurfer version: `7.1.0`:
* Buildstamp: `freesurfer-linux-centos7_x86_64-7.1.0-20200511-813297b`
* Architecture:  `Linux c1-40 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

#### FreeSurfer version `6.0.1`:
* Buildstamp: `freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a`
* Architecture: `c1-40 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Behaviour:
* FLAIR assisted pial segmentation seems to undershoot the pial surface. Possibly related to https://github.com/freesurfer/freesurfer/issues/747. 
* Comparing FLAIR assisted pial segmentation between FS6.0.1 and FS7.1.0, shows that the behaviour exists for FS7.1.0 and not FS6.0.1.

#### FS7.1.0
**Legend**: white (red line), FLAIR pial (black line), T1 pial (white line). FLAIR and T1 is shown in grayscale.

**T1**
![image](https://user-images.githubusercontent.com/21278572/112138297-a6ee6880-8bd1-11eb-80ea-ef1d559c7f55.png)

**FLAIR**
![image](https://user-images.githubusercontent.com/21278572/112138392-bec5ec80-8bd1-11eb-88e5-554c749e0fad.png)

#### FS6.0.1 vs. FS7.1.0
**Legend**:  FLAIR pial FS6.0.1 (red line), FLAIR pial FS7.1.0 (yellow line). FLAIR and T1 is shown in grayscale.

**T1**
![image](https://user-images.githubusercontent.com/21278572/112142138-7d840b80-8bd6-11eb-92c4-a67115ff8858.png)

**FLAIR**
![image](https://user-images.githubusercontent.com/21278572/112140301-22e9b000-8bd4-11eb-8e0e-e22fe61bb39d.png)

### How to replicate the behavior
recon-all  -s <subjid> -i <T1w_path> -FLAIR <FLAIR_path> -FLAIRpial

Edit: Wrong T1 image for FS6 vs. FS7.1.0

**Comment by ahoopes** [comment]
@fredrmag closing this as we like to reserve the github issues page for known software bugs and hard failures. For any soft errors or undesirable results, please open up a conversation on the [freesurfer mailing list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport). Thanks!

**Comment by dngreve** [comment]
The source of this bug has been tracked down and fixed. If you have v 7.{0,1,2,3), you can create a $SUBJECTS_DIR/global-expert-options.txt file with this line "PlaceMMPialSurf --mm_min_inside 50 --mm_max_inside 200 --mm_min_outside 10 --mm_max_outside 50" (no quotes)
