### ISSUE TITLE
mri_segment -- bug parsing CLI options (error present in example)

### ISSUE THREAD

**Issue by dangom** [freesurfer/freesurfer#853]
Changing the `-wm_low`, as shown in the [FS documentation example](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_segment) does not currently work, since the option is ignored if passed after the input and output file arguments:

```shell
> mri_segment brainmask.mgz wm_test.mgz -wm_low 97
WHITE_MATTER_MEAN 110
wsize 11
wm_low 80
...
```

Passing the option as a first argument works:

```shell
> mri_segment -wm_low 97 brainmask.mgz wm_test.mgz 
using white lolim = 97.0
WHITE_MATTER_MEAN 110
wsize 11
wm_low 97
...
```

The documentation also states that wm_low is 90 per default, but stdout says 80.
Issue does not affect recon-all as parameters are passed before in/out arguments.

__
```
You are running this version of FreeSurfer:

  freesurfer-linux-centos7_x86_64-7.1.1-20200723-8b40551
```

**Comment by ahoopes** [comment]
The cmdline arg processing in `mri_segment` is rather old and requires optional flags to precede all positional arguments. Updating this is on a long list of TODOs, but in the meantime I've clarified the wiki and code documentation a bit in ec2c723ee8. I've also added some sanity checks to print more helpful information when the incorrect command syntax is used.

As for the wm range, the default `wm_low` is actually 90, but when no segmentation file is provided, the variability is widened by dropping `wm_low` by 10. I've added a message to make this more clear.
