### ISSUE TITLE
recon-all does not pass user segmentation parameters to mris_autodet_gwstats

### ISSUE THREAD

**Issue by dangom** [freesurfer/freesurfer#856]
Hi devs,

I've been trying to improve the surface reconstruction (particularly in V1) of data acquired in Bay 5 using a dual-echo MPRAGE. I notice that, for some subjects, the white matter surfaces tend to be include a lot of gray matter, and so I thought that one potential solution to the issue would be to adjust the `seg_wlo` and `seg_ghi` values to improve the WM segmentation.
Although that does work, and leads to decent starting `?h.orig` surfaces, the subsequent preaparc surfaces may look really bad if the values passed to the segmentation aren't taken into account. Here is an illustration (orig in black, default preaparc in green, and red coloured surfaces show the effect of adjusting `--min_gray_at_white_border`):

<img width="996" alt="image" src="https://user-images.githubusercontent.com/7881842/118030534-f68d1d00-b354-11eb-9720-53542326548f.png">

In this particular subject, the default values end up leading to WM surfaces been pushed outwards towards CSF. If I adjust the `min_gray_at_white_border`, mimicking `seg_ghi`, then things start to look better (red surfaces).

My question is: what would be the correct FS behaviour in this case? Should `seg_wlo` and `seg_ghi` also be passed to `mris_autodet_gwstats`? Or should parameters for `mris_autodet_gwstats` be exposed independently? 
Is this potentially a small bug/edge-case or is there a case for keeping the defaults?

Here's the code I used to generate these surfaces:

```sh
root="/cluster/osc/data/fhr"
fsdir="derivatives/freesurfer"
for i in {80..110..5}; do

    output_gw="${root}/tmp/autodet-tests/autodet.gw.stats.min-GWB${i}.rh.dat"
    mris_autodet_gwstats  \
        --o "${output_gw}" \
        --i "${root}/${fsdir}/fhr01/mri/brain.finalsurfs.mgz" \
        --wm "${root}/${fsdir}/fhr01/mri/wm.mgz" \
        --surf "${root}/${fsdir}/fhr01/surf/rh.orig" \
        --min_gray_at_white_border "${i}"

    output_surf="${root}/tmp/autodet-tests/rh.white.preaparc.min-GWB${i}"
    mris_place_surface \
        --adgws-in "${output_gw}" \
        --max-cbv-dist 3 \
        --wm "${root}/${fsdir}/fhr01/mri/wm.mgz" \
        --invol "${root}/${fsdir}/fhr01/mri/brain.finalsurfs.mgz" \
        --rh \
        --i "${root}/${fsdir}/fhr01/surf/rh.orig" \
        --o "${output_surf}" \
        --white \
        --seg "${root}/${fsdir}/fhr01/mri/aseg.presurf.mgz" \
        --nsmooth 3 --threads 8 &

done
```

**Comment by dngreve** [comment]
Fixed.
