### ISSUE TITLE
Misleading description on docker hub

### ISSUE THREAD

**Issue by commandercool** [freesurfer/freesurfer#858]
Hello Freesurfer team!

First of all - many thanks for providing the official docker image for freesurfer 7.

There is a minor misleading piece in the description on docker hub though. It says add the following to include license:
```
COPY license /opt/freesurfer/.license
```

But you actually need to copy it in `/usr/local/freesurfer/.license`.

**Comment by ahoopes** [comment]
Good call! Just fixed it. Thanks
