### ISSUE TITLE
FREESURFER_HOME: Undefined variable even though it's defined.

### ISSUE THREAD

**Issue by bassamanator** [freesurfer/freesurfer#861]
Hi there,

When I `sudo recon-all -s mybrain -all -i aalim-brainscan.nii.gz` I get a strange error `FREESURFER_HOME: Undefined variable.` even though 
```
$ echo $FREESURFER_HOME
/opt/freesurfer
```
The [Test your FreeSurfer Installation](https://surfer.nmr.mgh.harvard.edu/fswiki/rel6downloads) worked just fine.
```
$ mri_convert sample-001.mgz sample-001.nii.gz
mri_convert.bin sample-001.mgz sample-001.nii.gz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from sample-001.mgz...
TR=7.25, TE=3.22, TI=600.00, flip angle=7.00
i_ras = (-0, -1, -0)
j_ras = (-0, 0, -1)
k_ras = (-1, 0, 0)
writing to sample-001.nii.gz...
```
What am I doing wrong here? 

>freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
>Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.36-2-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by arovai** [comment]
Sudo does not by default preserve the environment variables. See e.g. [this page](https://www.petefreitag.com/item/877.cfm). So when calling sudo, you're using another environment, in which FREESURFER_HOME is undefined. To check this you can type:

`sudo echo $FREESURFER_HOME`

It should produce an error.

I personally prefer to avoid sudo when I can...
