### ISSUE TITLE
Unable to control voxel edit/recon edit menu in WSLg with Ubuntu

### ISSUE THREAD

**Issue by akimbler** [freesurfer/freesurfer#878]
Hey All,

I'm currently trying to use `freeview` in WSLg on Windows 11 Dev and I'm running in to an annoying bug. When trying to initiate Voxel Edit/Recon Edit mode, the menu launches, but it's impossible to interact with. None of the selections work, and even the minimize/window/close functions on the menu fail to work. The main `freeview` however, appears to work fine and can be navigated as normal, only these spawned submenus seem to be "frozen.

**Comment by ahoopes** [comment]
@buildqa any ideas? Unfortunately, getting things working on WSL can be a bit of a struggle.

**Comment by buildqa** [comment]
We have not tested the FS 7.2.0 release (or the dev branch) on Windows 11 running in WSL.   Our latest documentation is for WSL2 on Windows 10 and that includes some troubleshooting tips which can be found here, https://surfer.nmr.mgh.harvard.edu/fswiki/FS7_wsl_ubuntu   We assume the Xming X-Windows server is being run on the Windows host.  Maybe you could check the settings on that page and also let us know if you are running Xming.

**Comment by buildqa** [comment]
Have not heard anything back about this one in a while so closing.
