### ISSUE TITLE
nf: [request/idea] multiple overlays in Freeview

### ISSUE THREAD

**Issue by gretatuckute** [freesurfer/freesurfer#900]
Hi, first of all thank you for the wonderful code framework. We are wondering -- it does not seem to be possible to show multiple overlays (e.g., on a surface) in Freeview at the same time? Are we missing a functionality? If not, that would be incredibly useful.

Thank you!
Greta

**Comment by uhussai7** [comment]
Work around is to reload the same surface for each of the multiple overlays and then play around with the opacity of the different surfaces.

**Comment by gretatuckute** [comment]
Thanks for the tip @uhussai7 !

**Comment by dngreve** [comment]
I don't know what you mean by multiple overlays at the same time. They are overlays, so they lay on top of each other, which means they necessarily obscure each other. Do you want to merge them in some way?

**Comment by gretatuckute** [comment]
@dngreve Thanks for the reply, Doug! Yes, true -- however, often overlays are either i) constrained to certain regions, and it is useful to be able to overlay several at once, or ii) it is useful to view the overlap between whole-brain overlays. In that sense, there is no need to merge them, simply allow for multiple overlays at once with the possibility to change the opacity. Does that make sense?

**Comment by buildqa** [comment]
Closing out given no follow up since our last response.
