### ISSUE TITLE
Freeview (7.2.0) crashes

### ISSUE THREAD

**Issue by JunhongYu** [freesurfer/freesurfer#911]
I used to be able to use freeview without any issues. However, now it crashes everytime i load any brain volumes. As you can see from the attached screenshot, it hanged at 99%. I recalled this problem started appearing after i've done quite a bit of cropping on several brain volumes.

![Capture](https://user-images.githubusercontent.com/34126910/149742172-2089834e-5adc-48d9-8670-df50790c162a.PNG)
%

**Comment by ahoopes** [comment]
@GerardYu can you post this to the [FreeSurfer mailing list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport) instead. As mentioned in the template, we reserve GitHub issues for tracking progress on known bugs and features, and you're likely to get more visibility on the list. When you post there, can you provide some more information like what operating system you're using and whether or not this issue exists with other FreeSurfer versions (like 7.1).

Thanks! I'm going to close this for now.
