### ISSUE TITLE
lta_convert transformation matrices between FreeSurfer and FSL depends on ENV variable

### ISSUE THREAD

**Issue by m-reuter** [freesurfer/freesurfer#916]
Behaviour of the conversion code depends on the value of the environment variable FSLOUTPUTTYPE which can be ANALYZE or NIFTI. The behaviour is described in:

https://github.com/freesurfer/freesurfer/blob/7cabf800a277b00d6499fc756d464ccfda46e774/utils/mri.cpp#L1046

So depending on the type, there could be a left-right flip. 

We should at least add a description of this to the help text of lta_convert , optimally it should be a required command line parameter instead of setting the environment variable. 

This issue is here mainly for documentation and can be resolved as soon as we have at least added a detailed description to lta_convert and potentially other places that read or write an FSL transformation matrix.

**Comment by ahoopes** [comment]
Agreed. Also, I feel like `FSLOUTPUTTYPE`, in addition to all the other default env settings in the sourcing scripts, are ripe for producing bugs and annoying-to-track discrepancies. Though I guess the workings of `FSLOUTPUTTYPE` are somewhat out of our control.

Ideally, FreeSurfer would have internal 'default' settings and the only time to set an env var would be when overriding something.

Anyway, we can update the documentation.

**Comment by buildqa** [comment]
Please let us know if this is still an issue, otherwise we will look to close out.

**Comment by buildqa** [comment]
Please post to the freesurfer list, freesurfer@nmr.mgh.harvard.edu, if you would like to follow up on this.
