### ISSUE TITLE
singularity pull of freesurfer docker image

### ISSUE THREAD

**Issue by zyzhang1992** [freesurfer/freesurfer#942]
singularity pull docker://freesurfer/freesurfer generates the following errors: 

```
singularity pull docker://r/freesurfer/freesurfer
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://r/freesurfer/freesurfer: reading manifest latest in [docker.io/r/freesurfer/freesurfer](http://docker.io/r/freesurfer/freesurfer): errors:
denied: requested access to the resource is denied
unauthorized: authentication required

and

```
```
singularity pull docker://freesurfer/freesurfer
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://freesurfer/freesurfer: reading manifest latest in docker.io/freesurfer/freesurfer: manifest unknown: manifest unknown
```

However the following worked just fine: 

`singularity pull docker://freesurfer/freesurfer:7.2.0`

Thanks you!

**Comment by avnishks** [comment]
Hi,

When pulling a docker image, if you don't specify an image tag it will default to the `latest` tag, i.e. `freesurfer:latest`.
But we don't have an image with the [latest tag in the repo](https://hub.docker.com/r/freesurfer/freesurfer/tags), hence the error you are seeing. 

Its best to specify the tag as you do in the final command that ran successfully, i.e.
`singularity pull docker://freesurfer/freesurfer:7.2.0`
