### ISSUE TITLE
Freesurfer build error on Ubuntu

### ISSUE THREAD

**Issue by jonathandubois** [freesurfer/freesurfer#951]
I get the below error when trying to build freesurfer on Ubuntu 20.04 with gcc version 4.8.5 
Not sure it makes a difference, but ubuntu is running virtually on a mac with UTM

error: 
[ 28%] Building CXX object utils/CMakeFiles/utils.dir/cluster.cpp.o
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_rateallocate':
tcd.c:(.text+0xd69): undefined reference to `__pow_finite'
/usr/bin/ld: tcd.c:(.text+0x1153): undefined reference to `__pow_finite'
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_encode_tile':
tcd.c:(.text+0x1a64): undefined reference to `__pow_finite'
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_decode_tile':
tcd.c:(.text+0x27b3): undefined reference to `__pow_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [anatomicuts/CMakeFiles/testOrientationPlanesFromParcellation.dir/build.make:305: anatomicuts/testOrientationPlanesFromParcellation] Error 1
make[1]: *** [CMakeFiles/Makefile2:12902: anatomicuts/CMakeFiles/testOrientationPlanesFromParcellation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object utils/CMakeFiles/utils.dir/cma.cpp.o
[ 29%] Building CXX object utils/CMakeFiles/utils.dir/cmat.cpp.o
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_rateallocate':
tcd.c:(.text+0xd69): undefined reference to `__pow_finite'
/usr/bin/ld: tcd.c:(.text+0x1153): undefined reference to `__pow_finite'
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_encode_tile':
tcd.c:(.text+0x1a64): undefined reference to `__pow_finite'
/usr/bin/ld: /home/jdubois/Documents/freesurfer_dev_build_031022/packages/itk/4.13.0/lib/libitkgdcmopenjp2-4.13.a(tcd.c.o): in function `opj_tcd_init_decode_tile':
tcd.c:(.text+0x27b3): undefined reference to `__pow_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [anatomicuts/CMakeFiles/dmri_saveHistograms.dir/build.make:320: anatomicuts/dmri_saveHistograms] Error 1
make[1]: *** [CMakeFiles/Makefile2:13046: anatomicuts/CMakeFiles/dmri_saveHistograms.dir/all] Error 2

**Comment by hjmjohnson** [comment]
In a partially related issue, ITK 4.13.0 was hard coded for the maximum version allowed of 8.  ITK 4.13.3 allows upto GCC 10.

Ubuntu 20.04 is shipped with gcc 9 by default.

```
#download 
wget https://github.com/InsightSoftwareConsortium/ITK/releases/download/v4.13.3/InsightToolkit-4.13.3.tar.gz 

#uncompress
tar -xzvf InsightToolkit-4.13.3.tar.gz

# mv
mv InsightToolkit ITK

#recompress
tar -czvf itk-4.13.3.tar.gz ITK

# move to freesurfer
mv itk-4.13.3.tar.gz freesurfer/packages/source

# update freesurfer/packages/build_packages.py with new ITK version numbers


```

**Comment by buildqa** [comment]
We currently install the gcc8 compilers on Ubuntu 20 and build the dev branch with those.

**Comment by buildqa** [comment]
There is a thread about using compilers older than gcc7 on Ubuntu 20 under, https://askubuntu.com/questions/1235819/ubuntu-20-04-gcc-version-lower-than-gcc-7
But you may have to revert various system libraries to older versions to get this to work.  We can't really support building freesurfer this way.
