### ISSUE TITLE
Building on arm64

### ISSUE THREAD

**Issue by maedoc** [freesurfer/freesurfer#964]
I'm building Freesurfer on arm64 Linux (in Docker on macOS to support m1).  I don't want to report these items as bugs but to note that it was a short path to success, with stumbling blocks related to use of SSE2 arithmetic and one odd type limit error:

Affine matrix headers: (a) `affine.h` uses SSE2 but could be disabled by renaming a CPP flag to `AFFINE_MATRIX_DO_NOT_USE_SSE` or similar;  (b) `affine.hpp` implements vector and matrix products with SSE2 and I just commented the arithmetic out to move on to other build issues, but it should be easy to provide scalar implementations of those or use arm's neon intrinsics. 

Then, this change is required. 
```diff
diff --git a/utils/fio.cpp b/utils/fio.cpp
index 59eaa87..eab1519 100644
--- a/utils/fio.cpp
+++ b/utils/fio.cpp
@@ -961,7 +961,7 @@ int fio_mkdirp(const char *path, mode_t mode)
 int fio_FileHasCarriageReturn(const char *fname)
 {
   FILE *fp;
-  char c;
+  int c;
   int n;
 ```
because the compiler reports that (apparently on arm) the comparison, a few lines down, of `char c == EOF` will always be false.  `int` seems like a usable choice.

Lastly, in a few places, CMake's put SSE2 related flags that should be removed, but I did it by hand since I'm not sure where it's hard coded in the CMake stuff.

I did not run tests yet since the affine matrix implementation should be done of course, but it seems easily doable.

**Comment by maedoc** [comment]
I tried to drop [this shim](https://github.com/DLTcollab/sse2neon) in for SSE2 support, but there are some warnings around strict aliasing of SIMD operations treated as errors, so it doesn't work.

**Comment by chhsiao1981** [comment]
hi @maedoc ～

I tried dropping in [the shim that you mentioned](https://github.com/DLTcollab/sse2neon) with the following code snippet
and it seems solving the SSE2 issue on m1.

```
+++ b/include/affine.hpp
@@ -19,7 +19,16 @@
 #ifndef AFFINE_HPP
 #define AFFINE_HPP

-#include <xmmintrin.h>
+#ifdef __x86_64__
+  #include <xmmintrin.h>
+#else
+  #define SSE2NEON_PRECISE_MINMAX 1
+  #define SSE2NEON_PRECISE_DIV 1
+  #define SSE2NEON_PRECISE_SQRT 1
+  #define SSE2NEON_PRECISE_DP 1
+  #include "sse2neon.h"
+#endif //__x86_64__
+

index aedee8866e..1259c8683f 100644
--- a/include/affine.h
+++ b/include/affine.h
@@ -25,8 +25,16 @@
 #endif

 #ifdef AFFINE_MATRIX_USE_SSE
-#include <xmmintrin.h>
-#endif
+  #ifdef __x86_64__
+    #include <xmmintrin.h>
+  #else
+    #define SSE2NEON_PRECISE_MINMAX 1
+    #define SSE2NEON_PRECISE_DIV 1
+    #define SSE2NEON_PRECISE_SQRT 1
+    #define SSE2NEON_PRECISE_DP 1
+    #include "sse2neon.h"
+  #endif //__x86_64__
+#endif //AFFINE_MATRIX_USE_SSE


--- a/histo_register/ParticleVideoLib/sample/bak_makefile
+++ b/histo_register/ParticleVideoLib/sample/bak_makefile
@@ -3,6 +3,7 @@ OPTLEVEL=2
 WARNFLAGS=-Wall -Wstrict-aliasing -Werror
 INCLUDE=-I. -I$(SBL)/include -I$(PVL)/include -I$(OPENCV)/include
-OPTFLAGS=-msse2 -mfpmath=sse -march=i686
+#OPTFLAGS=-msse2 -mfpmath=sse -march=i686
+OPTFLAGS=

--- a/histo_register/SimpleBaseLib/build/bak_makefile
+++ b/histo_register/SimpleBaseLib/build/bak_makefile
@@ -3,7 +3,8 @@ CPP=g++
 OPTLEVEL=2
 WARNFLAGS=-Wall -Wstrict-aliasing -Werror
 INCLUDE=-I../include -I$(OPENCV)/include
-OPTFLAGS=-msse2 -mfpmath=sse
+# OPTFLAGS=-msse2 -mfpmath=sse
+OPTFLAGS=
 CONFIGFLAGS=-DUSE_OPENCV -DUSE_CDT -DUSE_ZLIB #-D_DEBUG

--- a/histo_register/bak_makefile
+++ b/histo_register/bak_makefile
@@ -5,7 +5,8 @@ CPP=g++
 OPTLEVEL=2
 WARNFLAGS=-Wall -Wstrict-aliasing #-Werror
 INCLUDE=-I. -I$(SBL)/include -I$(SBL)/external -I$(PVL)/include -I$(OPENCV)/include
-OPTFLAGS=-msse2 -mfpmath=sse
+#OPTFLAGS=-msse2 -mfpmath=sse
+OPTFLAGS=
```

I can compile successfully without freeview.

However, it seems like freeview requires very old version of PETSc (2.3.3),
which requires python2 and not available (not even compilable from source) on m1.

I tried to update the source code of freesurfer with the newest version of PETSc (3.17.2, available from homebrew),
but then got segfault and warning from PETSc with complaining about openmpi.

**Comment by maedoc** [comment]
:+1: very cool, tho surprising that freeview depends on PETSc.  I would personally not mind using the x86_64 freeview on macOS, it seems to work fine.  Here, I was in particular interested in getting the computational parts of FreeSurfer working on arm64 so it can run inside Docker, which your patch addresses.

**Comment by martin-g** [comment]
+1 for better support for Linux ARM64 !
My employer is willing to donate Linux ARM64 VM that could be used for development needs and as a CI agent.
Please let me know if the project maintainers are interested !

**Comment by buildqa** [comment]
We've made some progress supporting arm64 for silicon Mac (darwin_arm64), but I'm not sure what can be done for linux_arm64, i.e., I'm unaware we have any arm64 linux hardware in house for that.   I would probably start with Ubuntu for linux_arm64 since we already support Ubuntu for linux_x86_64.

**Comment by maedoc** [comment]
if you have a Dockerfile for building from source, and you have a silicon Mac with Docker installed, then you have a arm64 linux hardware to test on.  This was actually the use case I was after, since we want to build/test our container based workflows with recent Mac laptops.  I realise that's an annoying ask, but I could help write/test the Dockerfile.

**Comment by buildqa** [comment]
Thanks for this tip.   Out current silicon mac is limited resource wise but I hope to improve that.

**Comment by pwighton** [comment]
@maedoc, I have an [open pull request to neurodocker](https://github.com/ReproNim/neurodocker/pull/445) to support compling FreeSurfer from source.

E.g the following command 
```
docker run pwighton/neurodocker:20220414 generate docker \
    --base-image ubuntu:xenial \
    --pkg-manager apt \
    --yes \
    --freesurfer \
      method=source
``` 

Will generate [this dockefile](https://pastebin.com/TMj9rmn5) that compiles FreeSurfer from source

**Comment by maedoc** [comment]
interesting, but it uses prebuilt stuff for centos7:
```
&& wget -q -c http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz -O - | tar -xz -C /opt/freesurfer-pkg \
```
I suspect this includes ITK and other stuff? idk 

also, at least wrt macOS Docker support, this may not be forever an issue: it seems that macOS users can/will be able to mount some Rosetta magic into the Linux for on-the-fly translation as well.  I saw this in UTM's docs, eventually available for Docker maybe? https://docs.getutm.app/advanced/rosetta/

**Comment by pwighton** [comment]
Ah yes, it does use pre-compiled packages, for ITK and others, but I think ITK is the only required package.

I think it should be possible to replace those pre-complied packages with packages built from source using [`build_packages.py`](https://github.com/freesurfer/freesurfer/blob/dev/packages/build_packages.py)

**Comment by pwighton** [comment]
Actually `build_packages.py` is intel only (thanks @buildqa).  

I have some [old notes for compiling for ppc64](https://github.com/pwighton/fs-ppc64/tree/master) which compiles itk from source

**Comment by buildqa** [comment]
We've noted the request for supporting linux_arm64 along with other requests we receive to support different platforms/OS's.  But we can't promise or provide a timeline for what other platforms/OS's will be supported in the future.

**Comment by dneary** [comment]
> Then, this change is required.
> 
> ```diff
> diff --git a/utils/fio.cpp b/utils/fio.cpp
> index 59eaa87..eab1519 100644
> --- a/utils/fio.cpp
> +++ b/utils/fio.cpp
> @@ -961,7 +961,7 @@ int fio_mkdirp(const char *path, mode_t mode)
>  int fio_FileHasCarriageReturn(const char *fname)
>  {
>    FILE *fp;
> -  char c;
> +  int c;
>    int n;
> ```
> 
> because the compiler reports that (apparently on arm) the comparison, a few lines down, of `char c == EOF` will always be false. `int` seems like a usable choice.

Interestingly, this is because a C `char` on Arm64 platforms is `unsigned char`, while on x86 it is `signed char`. This is "implementation defined" in the C standard. You can fix this in a cross-platform way by defining the variable explicitly as `signed char c` . That said, `getchar` returns `int`, and `EOF` is also an `int` - usually defined as -1.

I landed here because apparently there is still not an Arm64 native build for Freesurfer built in releases - could availability of compute resources help?

Dave.

**Comment by buildqa** [comment]
The online arm64 silicon Mac development build is waiting on various fixes/updates including python code in order for all the tools to work.    I don't have an estimate for when dev and testing will have a more release ready apple silicon build, or if/when arm64 Intel can be added.

**Comment by martin-g** [comment]
Apologies for commenting in a closed issue!

About:
> `char c == EOF`

It is recommended to use `feof(FILE *stream)` instead of `c == EOF`.
https://www.tutorialspoint.com/c_standard_library/c_function_feof.htm

**Comment by buildqa** [comment]
close as not planned
