### ISSUE TITLE
rca-config error on Ubuntu 20.04

### ISSUE THREAD

**Issue by alx080** [freesurfer/freesurfer#972]
Dear freesurfer team,

right now I'm getting this error with your newest build 25-04-22, running FastSurfer, I hadn't this error with the build dated 19-04-2022.
Recent fastsurfer dev build,2 RTX6000 16CPU, command: ./run_fastsurfer.sh --t1 /home/ubuntu/moya/data/x.nii --sd /home/ubuntu/moya/output --sid x --parallel --threads 16

========= Creating filled from brain (brainfinalsurfs, wm.asegedit, wm)  =======
 
recon-all -s ID58postOP1 -asegmerge -normalization2 -maskbfs -segmentation -fill -threads 16 -itkthreads 16
usage: rca-config [-h] [-gca GCA] [-gca-skull GCASKULL] [-ants-n3]
                  [-no-ants-n4] [-no-ants-denoise] [-no-remesh] [-decimate]
                  [-decimation-area DECIMATIONFACEAREA] [-rip-wmsa]
                  [-rip-lesion] [-first-peak-d1] [-no-defects-cortex]
                  [-samseg] [-synthseg]
rca-config: error: ambiguous option: -s could match -samseg, -synthseg
ERROR: could not configure recon-all parameters
Command exited with non-zero status 1
@#@FSTIME  2022:04:25:17:48:48 recon-all N 11 e 0.07 S 0.01 U 0.05 P 95% M 11900 F 0 R 3564 W 0 c 2 w 31 I 0 O 0 L 1.76 2.10 1.80
@#@FSLOADPOST 2022:04:25:17:48:48 recon-all N 11 1.76 2.10 1.80

Could you tell me how to fix this?

BR, Alexander

**Comment by m-reuter** [comment]
Thanks for letting us know. What is your docker build command? 

Also please be aware that dev is experimental and can be broken any time. Use stable for production.

**Comment by alx080** [comment]
It's running without docker on ubuntu 20.04, I'm trying running FreeSurfer 7.2.0 right now to be sure.

Edit: No error when using fs 7.2.0 or the dev build that was released a week ago.

**Comment by m-reuter** [comment]
Dev has been modified to work together with FreeSurfer 7.2, but we are still testing this and are investigating some issues, so it should not be used yet for any real analysis. 

If I understand correctly you are running the FastSurfer dev branch together with an installed FreeSurfer 7.2 and are seeing the reported issue, right? And you see no error when running FreeSurfer 7.2 stand alone? 

So the error you are seeing has to do with the python version. Python on Ubuntu 20.04 is newer and does not work with freesurfer. FreeSurfer, for that reason and many others, therefore distributes their own python  environment with an older version. What I currently do not understand is, why it works stand alone, and not in conjunction with FastSurfer. Maybe try sourcing FreeSurfer via its setup script and then run fastsurfer?

**Comment by m-reuter** [comment]
Also, FastSurfer dev has not had any commits since April 11, so if it worked April 19, it should work now. Something else on your system must have changed in the meantime.

**Comment by alx080** [comment]
After upgrading to a new 16-CPU machine I've downloaded your latest build today. You're right as I'm not seeing errors when running FreeSurfer 7.2, but I'm running either 7.2 or the dev build. As I said the error happened only when running the 25-04-22 build, I hadn't had it when running it some days ago...
I'm running it every time together with FastSurfer, my setup isn't really changing, that's why I thought it's due to the new version. My installation, except the FreeSurfer version installation stayed the same.
I can try to do a new clean install, but that's what I did every time with 7.2, and the two dev builds:
`
## startingamachine
sudo apt-get update
sudo apt-get upgrade

## gpu driver
sudo apt-get remove --purge '^nvidia-.*'
sudo apt-get remove --purge '^libnvidia-.*'
sudo apt-get remove --purge '^cuda-.*'
sudo apt-get install linux-headers-$(uname -r)
wget https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda_11.6.2_510.47.03_linux.run
sudo sh cuda_11.6.2_510.47.03_linux.run

## pip
sudo apt install python3-pip

## python3-testresources
sudo apt-get install -y python3-testresources

## Clone FastSurfer repo
git clone -b dev https://github.com/deep-mi/fastsurfer.git
cd fastsurfer
export FASTSURFER_HOME=$PWD

# Install python dependencies
sudo apt install python3-setuptools
#or
pip3 install setuptools --force
python3 -m pip install --user --trusted-host pypi.python.org --prefer-binary -r requirements.txt

## scikit-sparse installation
#(nano ~/.bashrc and export PATH=$PATH:/home/$USER/.local/bin)
#(rename pkg_resources to pkg_resources_back in lib/python3.8/site-packages)
sudo apt-get install libsuitesparse-dev
pip install scikit-sparse==0.4.4

## freesurfer-dev installation
!! insert freesurfer license.txt and change build-stamp to 7.2.0
wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev/freesurfer-linux-ubuntu18_x86_64-dev.tar.gz
tar -xzvf freesurfer-linux-ubuntu18_x86_64-dev.tar.gz
apt-get install csh tcsh
## freesurfer-7.2.0 instllation
wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.2.0/freesurfer-linux-ubuntu18_amd64-7.2.0.tar.gz
tar -xzvf freesurfer-linux-ubuntu18_x86_64-7-2-0.tar.gz


## bashrc
nano $HOME/.bashrc
#Added by me.
export PATH="$HOME/FastSurfer:$PATH"
export FREESURFER_HOME=$HOME/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
export SUBJECTS_DIR=$HOME/moya/output
export FASTSURFER_HOME=$HOME/fastsurfer
echo "Paths loaded"


##rename
find /home/ubuntu/moya/data -iname '*.nii' -execdir mv -i '{}' orig.nii \;

# run FastSurfer
#singlesubject
cd fastsurfer
./run_fastsurfer.sh --t1 /home/ubuntu/moya/data/*/orig.nii --sd /home/ubuntu/moya/output --sid * --parallel --threads 16

!! see multiple.sh
# multile subjects
#!/bin/bash
export FREESURFER_HOME=$HOME/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

cd /home/ubuntu/fastsurfer
datadir=/home/ubuntu/moya/data
fastsurferdir=/home/ubuntu/moya/output
mkdir -p $fastsurferdir/logs # create log dir for storing nohup output log (optional)

while read p ; do
  echo $p
  nohup ./run_fastsurfer.sh --t1 $datadir/$p/orig.nii \
                            --parallel --threads 16 --sid $p --sd $fastsurferdir > $fastsurferdir/logs/out-${p}.log &
  sleep 90s
done < /home/ubuntu/moya/subjects_list.txt`

**Comment by m-reuter** [comment]
You can try to install via conda (same as we do in our docker makefiles). Also this whole discussion needs to be moved to FastSurfer as it is not a FreeSurfer issue.

**Comment by m-reuter** [comment]
Some updates: 
To see if this is an issue even in FreeSurfer (without FastSurfer) you would need to run a command that specifies only one hemisphere. Eg. something fast like `recon-all -s $subject -hemi lh -surfvolume ` on an existing subject. 
What happens is, in newer python versions rca-config will understand the "-hemi" as "-h" for help plus "-e -m -i" and will be confused. This did not happen with python 3.6. If you see similar errors, this issue can stay here in FreeSurfer repo as it is a problem that should be addressed here for future python upgrades.

There is also an easy fix: we just need to switch off the -h help flag in rca-config like so: 

`sed -i 's/allow_abbrev=False/allow_abbrev=False,add_help=False/' rca-config`

**Comment by alx080** [comment]
Changing in line 535 in recon-surf.sh (fastsurfer/recon-surf)
`cmd="recon-all -s $subject -asegmerge -normalization2 -maskbfs -segmentation -fill $fsthreads"`
to
`cmd="recon-all -subject $subject -asegmerge -normalization2 -maskbfs -segmentation -fill $fsthreads"`
fixed the problem for me 😅

**Comment by m-reuter** [comment]
Interesting, then I take everything back and this is not the "-hemi" problem which I had encountered. Still it is very strange that this is problematic only in that line, as we use  the "-s" flag in lots of places. Line 535 is the first time we call recon-all, but we do so multiple times afterwards (e.g. line 604). In those lines it does not complain? Its probably best we change everything to -subject. Thanks.

**Comment by alx080** [comment]
I tried your suggested `recon-all -s $subject -hemi lh -surfvolume` command using `-subjects` . Actually I changed all `-s`to `-subject` in recon_surf.sh, so it is possible that the problem would have occurred there as well.

**Comment by m-reuter** [comment]
I updated fastsurfer dev accordingly, just in case it helps you and others. Still not sure why this happens on your system and not in our Ubuntu 20.04 docker images and neither when running freesurfer stand-alone. 
Given that it is fixed for you, we can close this here.
