### ISSUE TITLE
Use --MI to process infant freesurfer would fail

### ISSUE THREAD

**Issue by johnccshen** [freesurfer/freesurfer#976]
https://github.com/freesurfer/freesurfer/blob/2995ded957961a7f3704de57eee88eb6cc30d52d/infant/infant_recon_all#L545

When I run infant freesurfer using the command below would fail the process with an error message 
ERROR: Flag --gmwm unrecognized.

It seems that find_neighbors_byMI_extended.csh does not support the flag, --gmwm.

The command I used is `infant_recon_all --s subject001 --age 24 --MI`

**Comment by buildqa** [comment]
If this is still an issue, then please post this to the freesurfer help list, freesurfer@nmr.mgh.harvard.edu, as more users/developers are likely to see it there.

**Comment by buildqa** [comment]
Please post to the above list if still an issue.
