### ISSUE TITLE
What is the difference between Volume (WM Parcellation) and Subcortical Volume (aseg.stats)?

### ISSUE THREAD

**Issue by wjddyd66** [freesurfer/freesurfer#978]
In the file downloaded from ADNI, it was confirmed that the label is different for each version for the same ROI.

For example) 
Freesurfer 6.0
ID | FLDNAME | TBLNAME | CRFNAME | QUESTION | TEXT
-- | -- | -- | -- | -- | --
-4 | ST21SV | UCSFFSX6 | Cross-Sectional FreeSurfer (6.0) | -4 | Subcortical Volume (aseg.stats) of LeftChoroidPlexus

Freesurfer 5.1
ID | FLDNAME | TBLNAME | CRFNAME | QUESTION | TEXT
-- | -- | -- | -- | -- | --
-4 | ST21SV | UCSFFSX51 | Cross-Sectional FreeSurfer (5.1) | -4 | Subcortical Volume (aseg.stats) of LeftChoroidPlexus

Freesurfer 4.3
ID | FLDNAME | TBLNAME | CRFNAME | QUESTION | TEXT
-- | -- | -- | -- | -- | --
-4 | ST21SV | UCSFFSX | Cross-Sectional FreeSurfer (FreeSurfer Version 4.3) | -4 | Volume (WM Parcellation) of LeftChoroidPlexus

</body>

</html>

It has been confirmed that the current ROI (LeftChoroidPlexus) values ​​are all the same if the same Subject.
**However, I do not know exactly whether this area is the WM volume or the Subcortical volume.**
I don't know what value to set it to. (Most seem to be done with subcortical volume.)

**Comment by dngreve** [comment]
Please post these general questions to the FS list. But to answer your question, the aseg has a single label for cortex and a single label for WM. Cortex and WM are subsegmented in wmparc
