### ISSUE TITLE
Permission error for `samseg/20Subjects_smoothing2_down2_smoothingForAffine2`

### ISSUE THREAD

**Issue by ltirrell** [freesurfer/freesurfer#980]
The contents of:
`distribution/average/samseg/20Subjects_smoothing2_down2_smoothingForAffine2.tar.gz`
has permissions that could cause an error for users not in the group that built FreeSurfer. 

After extracting and building, the permissions are:
```
drwxr-s---  2 cmet cmet  4096 May  4 22:25 ./average/samseg/20Subjects_smoothing2_down2_smoothingForAffine2
```
while all other built directories have read/execute permissions for all users.

Currently I run `find $FREESURFER_HOME -type d -exec chmod a+rx {} +` as a workaround in our build process.

**Comment by buildqa** [comment]
I think this has been fixed as of 6/14 such that when installed those subdirs now look like:

drwxrwxr-x. 20Subjects_smoothing2_down2_smoothingForAffine2/
drwxrwxr-x. 20Subjects_smoothing2_down2_smoothingForAffine2_lesion_wm_prior/
drwxrwxr-x. 20Subjects_smoothing2_down2_smoothingForAffine2_lesion/

**Comment by buildqa** [comment]
Please re-open if there is still any issue.
