### ISSUE TITLE
Error with mri_surf2surf: could not read surface

### ISSUE THREAD

**Issue by margotwagner** [freesurfer/freesurfer#982]
I am trying to run the FreeSurferPipelineBatch using the example data provided (subject 100307).

Currently, I am getting an error while running `FreeSurferPipeline.sh`.

The error is

Reading source surface reg   

> /nadata/cnl/home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/100307/surf/lh.white.preaparc 
No such file or directory
mri_surf2surf: could not read surface /nadata/cnl/home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/100307/surf/lh.white.preaparc
No such file or directory

This occurs after FreeSurferPipeline.sh calls mri_surf2surf using the following command

> `mri_surf2surf --s 100307 --hemi lh --sval-xyz white.preaparc --surfreg white.preaparc --reg transforms/rawavg2conf.dat rawavg.cmdc.mgz --tval-xyz rawavg.cmdc.mgz --tval white.preaparc.rawavg`

Generally --surfreg makes the surface, and the current `FreeSurferPipeline.sh` script states that

#The ?h.white.deformed surfaces are used in FreeSurfer BBR registrations for fMRI and diffusion and have been moved into the HCP's T1w space so that BBR produces a transformation containing only the minor adjustment to the registration.

There does not appear to be a file anywhere that matches "lh.white.preaparc", "preaparc", or "white". The listed surf files are lh.orig.nofix, lh.smoothwm.nofix, lh.inflated.nofix, lh.qsphere.nofix, lh.orig, lh.inflated, lh.defect_labels, lh.defect_bordered, lh.defect_chull.

I am using FreeSurfer version 6
Attached is the output file.
[FreeSurferPipelineOutput.txt](https://github.com/freesurfer/freesurfer/files/8681797/FreeSurferPipelineOutput.txt)

**Comment by dngreve** [comment]
Have you asked the HCP people for guidance? Also, please post these kinds of questions to the FS list and not github, which is for source code related issues. thanks!
