### ISSUE TITLE
Bug: mris_register -L label initialisation broken in FS7

### ISSUE THREAD

**Issue by m-reuter** [freesurfer/freesurfer#994]
This bug affects FS 7.* and dev when mris_register is called with a label for guiding the alignment. 

In the context of #520 reorganisation a new global sphere alignment has been developed. See https://github.com/freesurfer/freesurfer/blob/dev/utils/mrisurf_deform.cpp#L4765
It is possible to switch on a slightly updated version of the old routine (from FS 6.0) via an environment variable. 

Both the old and the new routine do not treat the external cost correctly. In the updated old routine this part was simply dropped (keeping ext_ssd fixed) and in the new routine not added. The external cost (ext_ssd) needs to be updated for each rotation and added to the overall ssd, as it needs to be simultaneously minimised. It is, for example, used when mris_register is called with a -L (label initialisation). It was working correctly in FS6.0. 

Two things will need to be fixed: 

1. the old code (I will put in a pull request for that)
2. the new code which resides in https://github.com/freesurfer/freesurfer/blob/dev/utils/MRISrigidBodyAlignGlobal.cpp will also need to be updated. 

For the new code I have no clue how one could evaluate the external cost function for each rotation, so someone else would need to take a look.

**Comment by yhuang43** [comment]
I checked in a fix to compute external cost for the new code after each rotation:
https://github.com/freesurfer/freesurfer/commit/e82afd222d2b433e4ef791b8294dd54c1c59c370
